use super::*;
use image::{Rgba,RgbaImage,GrayImage,Luma};
use base64::Engine;
#[derive(Serialize)]#[serde(rename_all="camelCase")]
pub struct CanvasPreview {data_url:String,width:u32,height:u32,bytes:usize}
fn mask_preview(mask:GrayImage)->RgbaImage {
 let image=image::DynamicImage::ImageLuma8(mask);
 if image.width()>1200||image.height()>1200 {image.thumbnail(1200,1200).to_rgba8()} else {image.to_rgba8()}
}
fn rgba(s:&Option<String>)->Rgba<u8>{match s {Some(c)=>Rgba([u8::from_str_radix(&c[1..3],16).unwrap(),u8::from_str_radix(&c[3..5],16).unwrap(),u8::from_str_radix(&c[5..7],16).unwrap(),255]),None=>Rgba([0,0,0,0])}}
pub(super) fn paint(mask:&Mask,w:u32,h:u32)->Result<GrayImage>{
 let mut image=GrayImage::from_pixel(w,h,Luma([if mask.base{255}else{0}]));let mut budget=0u64;
 for s in &mask.strokes {
  let target=if s.restore{255.}else{0.};let mut stamp=|x:f64,y:f64,r:f64|->Result<()>{
   let x0=(x-r).floor().max(0.) as u32;let y0=(y-r).floor().max(0.) as u32;let x1=(x+r).ceil().max(0.).min(w as f64) as u32;let y1=(y+r).ceil().max(0.).min(h as f64) as u32;
   budget+=u64::from(x1.saturating_sub(x0))*u64::from(y1.saturating_sub(y0));if budget>300_000_000{return Err("creative_limit".into());}
   for yy in y0..y1 {for xx in x0..x1 {let d=((xx as f64+0.5-x).powi(2)+(yy as f64+0.5-y).powi(2)).sqrt()/r;if d<=1.{let strength=if d<=s.hardness{1.}else{(1.-d)/(1.-s.hardness).max(0.0001)}*s.opacity;let p=image.get_pixel_mut(xx,yy);p[0]=(f64::from(p[0])*(1.-strength)+target*strength).round() as u8;}}}Ok(())
  };
  if matches!(s.shape,Shape::Brush){let r=(s.size*w.min(h) as f64/2.).max(0.5);let mut previous=s.points[0];stamp(previous[0]*w as f64,previous[1]*h as f64,r)?;for p in s.points.iter().skip(1){let dx=(p[0]-previous[0])*w as f64;let dy=(p[1]-previous[1])*h as f64;let count=((dx*dx+dy*dy).sqrt()/(r/3.).max(1.)).ceil().max(1.) as usize;for i in 1..=count {let t=i as f64/count as f64;stamp((previous[0]+(p[0]-previous[0])*t)*w as f64,(previous[1]+(p[1]-previous[1])*t)*h as f64,r)?;}previous=*p;}}
  else {let a=s.points[0];let b=s.points[1];let x0=(a[0].min(b[0])*w as f64).max(0.) as u32;let x1=(a[0].max(b[0])*w as f64).max(0.).min(w as f64) as u32;let y0=(a[1].min(b[1])*h as f64).max(0.) as u32;let y1=(a[1].max(b[1])*h as f64).max(0.).min(h as f64) as u32;budget+=u64::from(x1.saturating_sub(x0))*u64::from(y1.saturating_sub(y0));if budget>300_000_000{return Err("creative_limit".into());}for y in y0..y1{for x in x0..x1{let nx=(x as f64/w as f64-(a[0]+b[0])/2.)/((a[0]-b[0]).abs()/2.).max(1e-9);let ny=(y as f64/h as f64-(a[1]+b[1])/2.)/((a[1]-b[1]).abs()/2.).max(1e-9);if matches!(s.shape,Shape::Rectangle)||nx*nx+ny*ny<=1.{let p=image.get_pixel_mut(x,y);p[0]=(f64::from(p[0])*(1.-s.opacity)+target*s.opacity).round() as u8;}}}}
 }if mask.inverted{for p in image.pixels_mut(){p[0]=255-p[0];}}Ok(image)
}
fn composite(dst:&mut Rgba<u8>,src:[f64;4],opacity:f64,blend:Blend){let sa=src[3]*opacity;let da=f64::from(dst[3])/255.;let alpha=sa+da*(1.-sa);if alpha<=0.{return;}for k in 0..3{let s=src[k];let d=f64::from(dst[k])/255.;let b=match blend{Blend::Normal=>s,Blend::Multiply=>s*d,Blend::Screen=>s+d-s*d,Blend::Overlay=>if d<=0.5{2.*s*d}else{1.-2.*(1.-s)*(1.-d)}};dst[k]=(((1.-sa)*da*d+(1.-da)*sa*s+sa*da*b)/alpha*255.).round().clamp(0.,255.) as u8;}dst[3]=(alpha*255.).round() as u8;}
fn sample(i:&RgbaImage,x:f64,y:f64)->[f64;4]{let x=x-0.5;let y=y-0.5;let ix=x.floor() as i64;let iy=y.floor() as i64;let fx=x-ix as f64;let fy=y-iy as f64;let mut out=[0.;4];for (dx,dy,f) in [(0,0,(1.-fx)*(1.-fy)),(1,0,fx*(1.-fy)),(0,1,(1.-fx)*fy),(1,1,fx*fy)]{let px=(ix+dx).clamp(0,i.width() as i64-1) as u32;let py=(iy+dy).clamp(0,i.height() as i64-1) as u32;let p=i.get_pixel(px,py);let a=f64::from(p[3])/255.;for k in 0..3{out[k]+=f64::from(p[k])/255.*a*f;}out[3]+=a*f;}if out[3]>0.{for k in 0..3{out[k]/=out[3];}}out}
pub(super) fn render(p:&Project,d:&Canvas,width:u32,height:u32)->Result<RgbaImage>{
 validate(&Creative{revision:0,image:Some(d.clone()),video:None},&p.assets)?;size(width,height)?;let mut out=RgbaImage::from_pixel(width,height,rgba(&d.background));let mut decoded=0u64;let sx=width as f64/d.width as f64;let sy=height as f64/d.height as f64;let mut work=0u64;
 for l in d.layers.iter().filter(|l|l.visible&&l.opacity>0.) {let(_,_,f,_pins)=Projects::creative_source(p,&l.asset_id)?;let(mut input,profile)=gallery::render_rgba(f,&l.operations)?;if profile{return Err("creative_profile".into());}decoded+=u64::from(input.width())*u64::from(input.height());if decoded>128_000_000{return Err("creative_limit".into());}
 if let Some(m)=&l.mask{let mask=paint(m,input.width(),input.height())?;for (p,m) in input.pixels_mut().zip(mask.pixels()){p[3]=((u16::from(p[3])*u16::from(m[0])+127)/255) as u8;}}
 let angle=l.rotation.to_radians();let co=angle.cos();let si=angle.sin();let cx=l.x+l.width/2.;let cy=l.y+l.height/2.;let rx=(co.abs()*l.width+si.abs()*l.height)/2.;let ry=(si.abs()*l.width+co.abs()*l.height)/2.;let x0=((cx-rx)*sx).floor().max(0.) as u32;let x1=((cx+rx)*sx).ceil().max(0.).min(width as f64) as u32;let y0=((cy-ry)*sy).floor().max(0.) as u32;let y1=((cy+ry)*sy).ceil().max(0.).min(height as f64) as u32;work+=u64::from(x1.saturating_sub(x0))*u64::from(y1.saturating_sub(y0));if work>256_000_000{return Err("creative_limit".into());}
 for y in y0..y1{for x in x0..x1{let dx=(x as f64+0.5)/sx-cx;let dy=(y as f64+0.5)/sy-cy;let u=(co*dx+si*dy)/l.width+0.5;let v=(-si*dx+co*dy)/l.height+0.5;if (0. ..1.).contains(&u)&&(0. ..1.).contains(&v){composite(out.get_pixel_mut(x,y),sample(&input,u*input.width() as f64,v*input.height() as f64),l.opacity,l.blend);}}}
 }Ok(out)
}
#[tauri::command]
pub async fn canvas_preview(id:String,document:Canvas,format:String,quality:u8,export_size:Option<[u32;2]>,mask_layer:Option<String>,state:tauri::State<'_,Arc<Projects>>)->Result<CanvasPreview>{let permit=gallery::editor_permit().await?;let p=state.inner().clone();tauri::async_runtime::spawn_blocking(move||{let _permit=permit;let p=p.creative_snapshot(&id)?;let size=export_size.unwrap_or([document.width,document.height]);let scale=(1200./size[0].max(size[1]) as f64).min(1.);let(w,h)=((size[0] as f64*scale).round().max(1.) as u32,(size[1] as f64*scale).round().max(1.) as u32);let image=if let Some(id)=mask_layer{validate(&Creative{revision:0,image:Some(document.clone()),video:None},&p.assets)?;let l=document.layers.iter().find(|l|l.id==id).ok_or("creative_source")?;let(_,_,f,_pins)=Projects::creative_source(&p,&l.asset_id)?;let (input,_)=gallery::render_rgba(f,&l.operations)?;let m=paint(&l.mask.clone().unwrap_or(Mask{base:true,inverted:false,strokes:vec![]}),input.width(),input.height())?;mask_preview(m)}else{render(&p,&document,w,h)?};let(w,h)=image.dimensions();let bytes=gallery::encode_rgba(image,&format,quality)?;Ok(CanvasPreview{data_url:format!("data:image/{};base64,{}",if format=="jpeg"{"jpeg"}else{"png"},base64::engine::general_purpose::STANDARD.encode(&bytes)),width:w,height:h,bytes:bytes.len()})}).await.map_err(err)?}
#[tauri::command]
pub async fn canvas_export(id:String,document:Canvas,format:String,quality:u8,width:u32,height:u32,state:tauri::State<'_,Arc<Projects>>,core:tauri::State<'_,Arc<Core>>,catalog:tauri::State<'_,Arc<gallery::GalleryCatalog>>)->Result<String>{let permit=gallery::editor_permit().await?;let p=state.inner().clone();let c=catalog.inner().clone();let root=gallery::root(&core)?;tauri::async_runtime::spawn_blocking(move||{let _permit=permit;let p=p.creative_snapshot(&id)?;let bytes=gallery::encode_rgba(render(&p,&document,width,height)?,&format,quality)?;c.export_project_edit(&root,"Composition",&bytes,serde_json::json!({"project":id,"canvas":document}),&format)}).await.map_err(err)?}
#[cfg(test)]mod tests{use super::*;
 #[test]fn small_mask_preview_preserves_dimensions_and_exact_grayscale(){let mask=GrayImage::from_fn(100,80,|x,_|Luma([if x<50{0}else{255}]));let preview=mask_preview(mask);assert_eq!(preview.dimensions(),(100,80));for (x,_,p) in preview.enumerate_pixels(){let value=if x<50{0}else{255};assert_eq!(p.0,[value,value,value,255]);}}

 #[test]fn masks_blends_and_transforms_have_real_pixels(){let mut d=Rgba([100,100,100,255]);composite(&mut d,[0.5,0.5,0.5,1.],1.,Blend::Multiply);assert_eq!(d,Rgba([50,50,50,255]));let m=Mask{base:true,inverted:false,strokes:vec![Stroke{shape:Shape::Rectangle,restore:false,size:0.2,hardness:1.,opacity:1.,points:vec![[0.,0.],[0.5,1.]]}]};let i=paint(&m,10,10).unwrap();assert_eq!(i.get_pixel(2,5)[0],0);assert_eq!(i.get_pixel(7,5)[0],255);let inverse=paint(&Mask{inverted:true,..m},10,10).unwrap();assert_eq!(inverse.get_pixel(2,5)[0],255);}
}
