use super::*;
pub mod media;
pub use media::{video_frame,media_prepare,media_status,media_cancel,media_info};
use std::{process::{Command,Stdio},os::windows::process::CommandExt,sync::atomic::{AtomicBool,Ordering},time::{Duration,Instant},io::{BufRead,BufReader},thread};
use tauri::{Manager,http::{Request,Response}};
use base64::Engine;
#[tauri::command]
pub async fn caption_read(path:String)->Result<String>{let privacy_epoch=crate::privacy::epoch();let privacy_result=(async {tauri::async_runtime::spawn_blocking(move||{let p=Path::new(&path);if p.extension().and_then(|s|s.to_str()).is_none_or(|s|!s.eq_ignore_ascii_case("srt")){return Err("project_path".into());}let mut f=gallery::lock_file(p)?;if f.metadata().map_err(err)?.len()>1024*1024{return Err("creative_limit".into());}let mut text=String::new();f.read_to_string(&mut text).map_err(err)?;Ok(text)}).await.map_err(err)?}).await;crate::privacy::finish(privacy_epoch,privacy_result)}
#[tauri::command]
pub async fn caption_write(path:String,text:String)->Result<()>{tauri::async_runtime::spawn_blocking(move||{let p=Path::new(&path);if text.len()>1024*1024||p.extension().and_then(|s|s.to_str()).is_none_or(|s|!s.eq_ignore_ascii_case("srt")){return Err("project_path".into());}let _pins=gallery::directory_guards(p.parent().ok_or("project_path")?)?;let mut f=OpenOptions::new().create_new(true).write(true).open(p).map_err(|_|"project_collision")?;f.write_all(text.as_bytes()).map_err(err)?;f.sync_all().map_err(err)}).await.map_err(err)?}
#[derive(Clone,Serialize,Deserialize)]#[serde(rename_all="camelCase")]
pub struct VideoJob {pub id:String,pub name:String,pub status:String,pub progress:f64,pub error:Option<String>,pub output:Option<String>,pub preview:bool,pub directory:String,pub project_id:String,pub timeline:Timeline,pub format:String,pub bitrate:u32}
pub struct VideoEngine {media:media::MediaTools,state:Mutex<(Connection,Vec<VideoJob>)>,runtime:PathBuf,busy:AtomicBool,cancel:AtomicBool}
impl VideoEngine {
 pub fn new(config:&Path,runtime:PathBuf)->Result<Arc<Self>>{let db=Connection::open(config.join("video-jobs.sqlite3")).map_err(err)?;db.execute_batch("PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS video_jobs(id TEXT PRIMARY KEY,json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS media_cache(id TEXT PRIMARY KEY,json TEXT NOT NULL)").map_err(err)?;let jobs={let mut q=db.prepare("SELECT json FROM video_jobs ORDER BY rowid DESC LIMIT 30").map_err(err)?;let rows=q.query_map([],|r|r.get::<_,String>(0)).map_err(err)?;let mut jobs=vec![];for row in rows{let mut j:VideoJob=serde_json::from_str(&row.map_err(err)?).map_err(err)?;if j.status=="running"{j.status="interrupted".into();j.error=Some("video_interrupted".into());}jobs.push(j);}jobs};Ok(Arc::new(Self{state:Mutex::new((db,jobs)),media:media::MediaTools::new(),runtime,busy:AtomicBool::new(false),cancel:AtomicBool::new(false)}))}
 pub fn stop(&self){self.media.stop();self.cancel.store(true,Ordering::SeqCst);}
 fn update(&self,id:&str,mutate:impl FnOnce(&mut VideoJob)){if let Ok(mut s)=self.state.lock(){if let Some(j)=s.1.iter_mut().find(|j|j.id==id){mutate(j);let text=serde_json::to_string(j).unwrap_or_default();let _=s.0.execute("INSERT OR REPLACE INTO video_jobs VALUES(?1,?2)",rusqlite::params![id,text]);}}}
 pub(crate) fn runtime(&self)->Result<(PathBuf,Vec<File>)>{let manifest:serde_json::Value=serde_json::from_str(include_str!("../../../video-runtime.json")).map_err(err)?;let mut pins=gallery::directory_guards(&self.runtime)?;for (name,hash) in manifest["files"].as_object().ok_or("video_runtime")?{if name.contains(['/', '\\', ':']){return Err("video_runtime".into());}let mut f=gallery::lock_file(&self.runtime.join(name)).map_err(|_|"video_runtime")?;if digest(&mut f)?!=hash.as_str().unwrap_or(""){return Err("video_runtime".into());}pins.push(f);}Ok((self.runtime.clone(),pins))}
}
#[derive(Clone,Serialize)]#[serde(rename_all="camelCase")]
pub struct Probe {pub duration:f64,pub width:u32,pub height:u32,pub audio:bool,pub video:bool}
fn command(path:&Path)->Command{let mut c=Command::new(path);c.creation_flags(0x08000000).stdin(Stdio::null());c}
fn capture(mut c:Command)->Result<Vec<u8>>{let mut child=c.stdout(Stdio::piped()).stderr(Stdio::null()).spawn().map_err(|_|"video_runtime")?;let guard=match crate::image_engine::ProcessGroup::attach(&child){Ok(g)=>g,Err(e)=>{let _=child.kill();let _=child.wait();return Err(e);}};let mut pipe=child.stdout.take().ok_or("video_runtime")?;let reader=thread::spawn(move||{let mut b=vec![];let _=(&mut pipe).take(1024*1024).read_to_end(&mut b);b});let start=Instant::now();let status=loop{if let Some(s)=child.try_wait().map_err(err)?{break s;}if start.elapsed()>Duration::from_secs(30){let _=child.kill();let _=child.wait();return Err("video_timeout".into());}thread::sleep(Duration::from_millis(30));};drop(guard);let bytes=reader.join().map_err(|_|"video_runtime")?;if !status.success(){return Err("video_decode".into());}Ok(bytes)}
pub(crate) fn probe(runtime:&Path,path:&Path)->Result<Probe>{let mut c=command(&runtime.join("ffprobe.exe"));c.args(["-v","error","-protocol_whitelist","file,pipe","-format_whitelist","mov,matroska,webm,mp3,wav,flac,ogg,image2,png_pipe,jpeg_pipe,bmp_pipe","-show_entries","format=duration:stream=codec_type,width,height,duration","-of","json"]).arg(path);let j:serde_json::Value=serde_json::from_slice(&capture(c)?).map_err(|_|"video_decode")?;let streams=j["streams"].as_array().ok_or("video_decode")?;let v=streams.iter().find(|s|s["codec_type"]=="video");let duration=j["format"]["duration"].as_str().and_then(|s|s.parse::<f64>().ok()).unwrap_or(0.);if !duration.is_finite()||duration>86400.{return Err("video_decode".into());}Ok(Probe{duration,width:v.and_then(|v|v["width"].as_u64()).unwrap_or(0) as u32,height:v.and_then(|v|v["height"].as_u64()).unwrap_or(0) as u32,audio:streams.iter().any(|s|s["codec_type"]=="audio"),video:v.is_some()})}
pub(super) fn duration(t:&Timeline)->f64{t.clips.iter().map(|c|c.start+(c.source_out-c.source_in)/c.speed).chain(t.captions.iter().map(|c|c.end)).fold(0.,f64::max)}
fn number(x:f64)->String{format!("{x:.6}")}
fn expression(keys:&[Keyframe],get:fn(&Keyframe)->f64,time:&str)->String{let mut value=number(get(keys.last().unwrap()));for pair in keys.windows(2).rev(){let(a,b)=(&pair[0],&pair[1]);let line=format!("{}+({})*({time}-{})/{}",number(get(a)),number(get(b)-get(a)),number(a.time),number(b.time-a.time));value=format!("if(lt({time},{}),{line},{value})",number(b.time));}value}
fn build(t:&Timeline,sources:&[(Asset,PathBuf,File,Vec<File>)],probes:&[Probe],work:&Path,format:&str,bitrate:u32,preview:bool,runtime:&Path,frame:bool)->Result<Command>{
 let total=if frame{0.1}else{duration(t)};bounded(total,0.04,3600.)?;let (w,h)=if preview {let scale=(854./t.width as f64).min(480./t.height as f64).min(1.);(((t.width as f64*scale/2.).round() as u32*2).max(2),((t.height as f64*scale/2.).round() as u32*2).max(2))}else{(t.width,t.height)};let ratio=w as f64/t.width as f64;
 let mut c=command(&runtime.join("ffmpeg.exe"));c.current_dir(work).args(["-hide_banner","-nostdin","-v","error","-n","-max_alloc","268435456","-filter_complex_threads","2"]);
 for (i,clip) in t.clips.iter().enumerate(){let a=&sources[i].0;let p=&probes[i];if a.kind!="image"&&(!p.duration.is_finite()||clip.source_out>p.duration+0.1){return Err("video_range".into());}if frame&&a.kind!="image"{c.args(["-ss",&number(clip.source_in)]);}if a.kind=="image"{c.args(["-loop","1","-framerate",&t.fps.to_string()]);}c.args(["-protocol_whitelist","file,pipe","-format_whitelist","mov,matroska,webm,mp3,wav,flac,ogg,image2,png_pipe,jpeg_pipe,bmp_pipe","-threads","2"]).arg("-i").arg(&sources[i].1);}
 let mut filters=vec![format!("color=c=0x{}:s={w}x{h}:r={}:d={},format=rgba[v0]",&t.background[1..],t.fps,number(total)),format!("anullsrc=r=48000:cl=stereo,atrim=duration={}[a0]",number(total))];let mut audios=vec!["[a0]".to_string()];let mut video_index=0;
 for tr in &t.tracks {if tr.muted{continue;}for (i,clip) in t.clips.iter().enumerate().filter(|(_,c)|c.track_id==tr.id){let p=&probes[i];let len=(clip.source_out-clip.source_in)/clip.speed;let keys=&clip.keyframes;
 if !tr.audio&&p.video{let scale=expression(keys,|k|k.scale,"t");let alpha=expression(keys,|k|k.opacity,"T");let rotate=expression(keys,|k|k.rotation,"t");let fit=(w as f64/p.width.max(1) as f64).min(h as f64/p.height.max(1) as f64);let iw=(p.width as f64*fit).round().max(2.);let ih=(p.height as f64*fit).round().max(2.);
 let mut f=format!("[{i}:v]trim=start={}:end={},setpts=(PTS-STARTPTS)/{},fps={},scale=w='max(2,trunc({iw}*({scale})/2)*2)':h='max(2,trunc({ih}*({scale})/2)*2)':eval=frame,setsar=1,format=rgba,lutrgb=r='clip((val-128)*{contrast}+128+255*{brightness},0,255)':g='clip((val-128)*{contrast}+128+255*{brightness},0,255)':b='clip((val-128)*{contrast}+128+255*{brightness},0,255)',hue=s={saturation}",number(if frame{0.}else{clip.source_in}),number(if frame{0.1}else{clip.source_out}),number(if frame{1.}else{clip.speed}),t.fps,brightness=number(clip.brightness),contrast=number(clip.contrast),saturation=number(clip.saturation));
 if clip.blur>0.{f.push_str(&format!(",gblur=sigma={}",number(clip.blur)));}f.push_str(&format!(",rotate=angle='({rotate})*PI/180':ow='ceil(hypot(iw,ih)/2)*2':oh=ow:c=none,format=rgba,geq=r='r(X,Y)':g='g(X,Y)':b='b(X,Y)':a='alpha(X,Y)*({alpha})'"));if clip.fade_in>0.{f.push_str(&format!(",fade=t=in:st=0:d={}:alpha=1",number(clip.fade_in)));}if clip.fade_out>0.{f.push_str(&format!(",fade=t=out:st={}:d={}:alpha=1",number(len-clip.fade_out),number(clip.fade_out)));}f.push_str(&format!(",setpts=PTS+{}/TB[clip{i}]",number(clip.start)));filters.push(f);
 let x=expression(keys,|k|k.x,&format!("(t-{})",number(clip.start)));let y=expression(keys,|k|k.y,&format!("(t-{})",number(clip.start)));filters.push(format!("[v{video_index}][clip{i}]overlay=x='(W-w)/2+({x})*{ratio}':y='(H-h)/2+({y})*{ratio}':enable='gte(t,{})*lt(t,{})':eof_action=pass:repeatlast=0[v{}]",number(clip.start),number(clip.start+len),video_index+1));video_index+=1;
 }
 if p.audio&&!frame {let volume=expression(keys,|k|k.volume,"t");let mut f=format!("[{i}:a]atrim=start={}:end={},asetpts=PTS-STARTPTS",number(clip.source_in),number(clip.source_out));let mut speed=clip.speed;while speed<0.5{f.push_str(",atempo=0.5");speed/=0.5;}while speed>2.{f.push_str(",atempo=2");speed/=2.;}f.push_str(&format!(",atempo={},volume='{}':eval=frame",number(speed),volume));if clip.fade_in>0.{f.push_str(&format!(",afade=t=in:d={}",number(clip.fade_in)));}if clip.fade_out>0.{f.push_str(&format!(",afade=t=out:st={}:d={}",number(len-clip.fade_out),number(clip.fade_out)));}f.push_str(&format!(",adelay={}:all=1[a{}]",(clip.start*1000.).round() as u64,i+1));filters.push(f);audios.push(format!("[a{}]",i+1));}
 }}
 let font=PathBuf::from(std::env::var_os("WINDIR").unwrap_or("C:\\Windows".into())).join("Fonts/segoeui.ttf");let font=font.to_string_lossy().replace('\\',"/").replace(':',"\\:");
 for (i,caption) in t.captions.iter().enumerate(){fs::write(work.join(format!("caption-{i}.txt")),&caption.text).map_err(err)?;filters.push(format!("[v{video_index}]drawtext=fontfile='{font}':textfile='caption-{i}.txt':expansion=none:fontcolor={}:fontsize={}:x=(w-text_w)/2:y=(h-text_h)*{}:box=1:boxcolor=black@0.6:boxborderw=8:enable='gte(t,{})*lt(t,{})'[v{}]",caption.color,(caption.size as f64*ratio).round().max(8.),number(caption.y),number(caption.start),number(caption.end),video_index+1));video_index+=1;}
 filters.push(format!("{}amix=inputs={}:duration=longest:normalize=0,alimiter=limit=0.95,atrim=duration={}[audio]",audios.join(""),audios.len(),number(total)));filters.push(format!("[v{video_index}]format=yuv420p[video]"));fs::write(work.join("filter.txt"),filters.join(";\n")).map_err(err)?;
 if frame{filters.retain(|f|!f.contains("anullsrc=")&&!f.contains("amix="));fs::write(work.join("filter.txt"),filters.join(";\n")).map_err(err)?;c.args(["-/filter_complex","filter.txt","-map","[video]","-frames:v","1","-c:v","png","-threads","1","-f","image2"]).arg("render.png");return Ok(c);}c.args(["-/filter_complex","filter.txt","-map","[video]","-map","[audio]","-t",&number(total),"-threads","2","-map_metadata","-1"]);
 match format{"mp4"=>{c.args(["-c:v","libopenh264","-b:v",&format!("{}k",if preview{2000}else{bitrate}),"-c:a","aac","-b:a","192k","-movflags","+faststart"]);},"webm"=>{c.args(["-c:v","libvpx-vp9","-b:v",&format!("{}k",if preview{1500}else{bitrate}),"-deadline","realtime","-cpu-used","6","-row-mt","1","-c:a","libopus","-b:a","128k"]);},_=>return Err("creative_parameters".into())};c.args(["-progress","pipe:1","-nostats"]).arg(format!("render.{format}"));Ok(c)
}
fn execute(engine:&VideoEngine,p:Project,job:&VideoJob,gallery_root:&Path)->Result<String>{
 let(runtime,_runtime_pins)=engine.runtime()?;let work=Path::new(&job.directory);let _pins=gallery::directory_guards(work)?;let mut sources=vec![];let mut probes=vec![];for clip in &job.timeline.clips{if engine.cancel.load(Ordering::SeqCst){return Err("video_cancelled".into());}let source=Projects::creative_source(&p,&clip.asset_id)?;let probed=probe(&runtime,&source.1)?;if probed.width>16384||probed.height>16384{return Err("creative_limit".into());}probes.push(probed);sources.push(source);}
 let log=OpenOptions::new().write(true).create_new(true).open(work.join("render.log")).map_err(err)?;let mut c=build(&job.timeline,&sources,&probes,work,&job.format,job.bitrate,job.preview,&runtime,false)?;let mut child=c.stdout(Stdio::piped()).stderr(log).spawn().map_err(|_|"video_runtime")?;let _guard=match crate::image_engine::ProcessGroup::attach(&child){Ok(g)=>g,Err(e)=>{let _=child.kill();let _=child.wait();return Err(e);}};let pipe=child.stdout.take().ok_or("video_runtime")?;let(tx,rx)=std::sync::mpsc::channel();let reader=thread::spawn(move||{for line in BufReader::new(pipe).lines().map_while(std::result::Result::ok){if let Some(s)=line.strip_prefix("out_time_us="){if let Ok(v)=s.parse::<f64>(){let _=tx.send(v/1e6);}}}});let start=Instant::now();let total=duration(&job.timeline);let status=loop{if engine.cancel.load(Ordering::SeqCst)||start.elapsed()>Duration::from_secs(4*3600){let _=child.kill();let _=child.wait();let _=reader.join();return Err(if engine.cancel.load(Ordering::SeqCst){"video_cancelled"}else{"video_timeout"}.into());}for time in rx.try_iter(){engine.update(&job.id,|j|j.progress=(time/total).clamp(0.,0.99));}if let Some(s)=child.try_wait().map_err(err)?{break s;}thread::sleep(Duration::from_millis(80));};let _=reader.join();if !status.success(){return Err("video_encode".into());}
 let output=work.join(format!("render.{}",job.format));let check=probe(&runtime,&output)?;if !check.video||!check.audio||check.duration<total-0.15{return Err("video_encode".into());}if engine.cancel.load(Ordering::SeqCst){return Err("video_cancelled".into());}
 if project_restricted(&p){crate::privacy::mark(&output)?;}if job.preview{return Ok(output.to_string_lossy().into());}let name=format!("Timeline-{}.{}",&job.id[..8],job.format);let path=gallery::copy_one_named(gallery_root,gallery_root,&output,&name)?;Ok(gallery_root.join(path).to_string_lossy().into())
}
#[tauri::command]
pub async fn video_probe(id:String,asset_id:String,state:tauri::State<'_,Arc<Projects>>,engine:tauri::State<'_,Arc<VideoEngine>>)->Result<Probe>{let privacy_epoch=crate::privacy::epoch();let privacy_result=(async {let p=state.inner().clone();let e=engine.inner().clone();tauri::async_runtime::spawn_blocking(move||{let p=p.creative_snapshot(&id)?;let(_,path,_file,_pins)=Projects::creative_source(&p,&asset_id)?;let(runtime,_pins)=e.runtime()?;probe(&runtime,&path)}).await.map_err(err)?}).await;crate::privacy::finish(privacy_epoch,privacy_result)}
#[tauri::command]
pub async fn video_start(id:String,timeline:Timeline,format:String,bitrate:u32,preview:bool,state:tauri::State<'_,Arc<Projects>>,engine:tauri::State<'_,Arc<VideoEngine>>,core:tauri::State<'_,Arc<Core>>)->Result<VideoJob>{let privacy_epoch=crate::privacy::epoch();let privacy_result=(async {let p=state.creative_snapshot(&id)?;validate(&Creative{revision:0,image:None,video:Some(timeline.clone())},&p.assets)?;if !["mp4","webm"].contains(&format.as_str())||!(500..=50000).contains(&bitrate){return Err("creative_parameters".into());}let e=engine.inner().clone();if e.busy.compare_exchange(false,true,Ordering::SeqCst,Ordering::SeqCst).is_err(){return Err("video_busy".into());}e.cancel.store(false,Ordering::SeqCst);let prepare=(||{let base=PathBuf::from(core.storage_paths()?.temporary).join("video-renders");fs::create_dir_all(&base).map_err(err)?;let _pins=gallery::directory_guards(&base)?;let job_id=uuid();let directory=base.join(&job_id);fs::create_dir(&directory).map_err(err)?;if project_restricted(&p){crate::privacy::protect_path(&directory)?;}let job=VideoJob{id:job_id,name:p.name.clone(),status:"running".into(),progress:0.,error:None,output:None,preview,directory:directory.to_string_lossy().into(),project_id:id,timeline,format,bitrate};let mut s=e.state.lock().map_err(err)?;s.0.execute("INSERT INTO video_jobs VALUES(?1,?2)",rusqlite::params![job.id,serde_json::to_string(&job).map_err(err)?]).map_err(err)?;s.1.insert(0,job.clone());Ok::<_,String>((job,gallery::root(&core)?))})();let(job,root)=match prepare{Ok(v)=>v,Err(error)=>{e.busy.store(false,Ordering::SeqCst);return Err(error);}};let j=job.clone();thread::spawn(move||{let result=(||{let _admission=crate::resources::shared().acquire(&j.id,"video",1024*1024*1024,false,&e.cancel).map_err(|v|if v=="resource_cancelled"{"video_cancelled".into()}else{v})?;execute(&e,p,&j,&root)})();let _=e.register_render_files(&j);e.update(&j.id,|job|match result{Ok(path)=>{job.status="completed".into();job.progress=1.;job.output=Some(path);},Err(error)=>{job.status=if error=="video_cancelled"{"cancelled"}else{"failed"}.into();job.error=Some(error);}});e.busy.store(false,Ordering::SeqCst);});Ok(job)}).await;crate::privacy::finish(privacy_epoch,privacy_result)}
#[tauri::command]pub fn video_jobs(engine:tauri::State<'_,Arc<VideoEngine>>)->Result<Vec<VideoJob>>{let privacy_epoch=crate::privacy::epoch();let privacy_result=(||{if crate::privacy::locked()&&crate::privacy::has_protected(){return Ok(vec![]);}Ok(engine.state.lock().map_err(err)?.1.clone())})();crate::privacy::finish(privacy_epoch,privacy_result)}
#[tauri::command]pub fn video_cancel(id:String,engine:tauri::State<'_,Arc<VideoEngine>>)->Result<()>{if engine.state.lock().map_err(err)?.1.iter().any(|j|j.id==id&&j.status=="running"){engine.stop();}Ok(())}
pub fn protocol(ctx:tauri::UriSchemeContext<'_,tauri::Wry>,req:Request<Vec<u8>>,responder:tauri::UriSchemeResponder){let e=ctx.app_handle().state::<Arc<VideoEngine>>().inner().clone();let label=ctx.webview_label().to_string();tauri::async_runtime::spawn_blocking(move||{let result=(||{if label!="main"{return None;}let id=req.uri().path().trim_matches('/');let s=e.state.lock().ok()?;let j=s.1.iter().find(|j|j.id==id&&j.status=="completed")?;let output=PathBuf::from(j.output.as_ref()?);let root=fs::canonicalize(output.parent()?).ok()?;let name=output.file_name()?.to_str()?;let(mut parts,body)=req.into_parts();parts.uri=format!("/{}/{}",gallery::root_id(&root),base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(name)).parse().ok()?;Some(gallery::response(&root,&label,Request::from_parts(parts,body)))})();responder.respond(result.unwrap_or_else(||Response::builder().status(404).body(vec![]).unwrap()));});}
#[cfg(test)]mod tests{use super::*;#[test]fn keyframe_interpolation_is_numeric_and_duration_accounts_for_speed(){let k=Keyframe{time:0.,x:0.,y:0.,scale:1.,rotation:0.,opacity:1.,volume:1.};let mut end=k.clone();end.time=2.;end.x=100.;assert!(expression(&[k,end],|k|k.x,"t").contains("100.000000"));assert_eq!(number(1.5),"1.500000");}}
