import assert from 'node:assert/strict';
import {promises as fs} from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,timeout=30000){const end=Date.now()+timeout;while(Date.now()<end){if(await fn())return;await pause(80);}throw new Error('Editor condition timed out');}
const hash=b=>createHash('sha256').update(b).digest('hex');
export async function checkEditor({getPage,invoke,stop,launch,artifactRoot,record}){
 let page=getPage();const gallery=(await invoke('bootstrap')).paths.gallery;const folder=path.join(gallery,'Editor19');await fs.mkdir(folder,{recursive:true});
 // Real raster fixture with transparent pixels and colored geometry, not AI output.
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=320;c.height=180;const x=c.getContext('2d');x.fillStyle='#20b890';x.fillRect(40,30,250,130);x.fillStyle='#af86f5';x.fillRect(70,50,85,90);x.fillStyle='#ffa83c';x.beginPath();x.arc(235,85,30,0,Math.PI*2);x.fill();return c.toDataURL().split(',')[1];});
 const source=path.join(folder,'source.png');await fs.writeFile(source,Buffer.from(png,'base64'));const original=hash(await fs.readFile(source));
 const list=()=>invoke('gallery_list',{query:{folder:'Editor19',search:'',kind:'all',recursive:true,offset:0}});
 async function open(){await page.getByRole('button',{name:'Gallery',exact:true}).first().click();await page.getByLabel('Search files',{exact:true}).fill('Editor19/source.png');const card=page.locator('[data-gallery-path="Editor19/source.png"]');await card.click();await until(async()=>await card.getAttribute('aria-pressed')==='true');await page.getByRole('button',{name:'Edit image',exact:true}).click();await page.getByRole('button',{name:'90° right',exact:true}).waitFor();await until(async()=>await page.getByRole('button',{name:'Close editor',exact:true}).isEnabled());}
 const editor=()=>page.getByRole('dialog',{name:'Image editor',exact:true});
 async function dimensions(w,h){await until(async()=>(await editor().locator('.editor-footer').innerText()).includes(`${w} × ${h} px`)&&await editor().getByRole('button',{name:'Close editor',exact:true}).isEnabled());}
 async function click(name){await editor().getByRole('button',{name,exact:true}).click();await until(()=>editor().getByRole('button',{name:'Close editor',exact:true}).isEnabled());}
 await open();await dimensions(320,180);await click('90° right');await dimensions(180,320);await editor().locator('.editor-stage').focus();await page.keyboard.press('Control+z');await dimensions(320,180);await page.keyboard.press('Control+y');await dimensions(180,320);await click('Flip horizontal');
 for(const [label,value] of [['X',10],['Y',20],['Crop width',100],['Crop height',150]])await editor().getByLabel(label,{exact:true}).fill(String(value));await click('Apply crop');await dimensions(100,150);
 await editor().getByLabel('Width',{exact:true}).fill('200');assert.equal(await editor().getByLabel('Height',{exact:true}).inputValue(),'300');await click('Apply size');await dimensions(200,300);
 await page.screenshot({path:path.join(artifactRoot,'editor19-dark.png')});
 await click('Export as variant');await until(async()=>(await list()).entries.length===2);let listing=await list();const variant=listing.entries.find(e=>e.path!=='Editor19/source.png');const output=await fs.readFile(path.join(gallery,variant.path));assert.equal(output.readUInt32BE(16),200);assert.equal(output.readUInt32BE(20),300);
 const query={rootId:listing.rootId,target:{path:variant.path,fileId:variant.fileId,version:variant.thumbnailVersion}};const family=await invoke('gallery_lineage',{query});assert.equal(family.versions.length,2);assert(family.versions.every(v=>v.available));const node=family.versions.find(v=>v.node.operation==='edit').node;assert.equal(node.edit.length,4);assert(node.parent);assert.equal(hash(await fs.readFile(source)),original);
 const transparent=await page.evaluate(async data=>{const img=new Image();img.src=`data:image/png;base64,${data}`;await img.decode();const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const x=c.getContext('2d');x.drawImage(img,0,0);const b=x.getImageData(0,0,c.width,c.height).data;let count=0;for(let i=3;i<b.length;i+=4)if(b[i]<255)count++;return count;},output.toString('base64'));assert(transparent>0);
 record('Native editor rotates, flips, crops, resizes with aspect lock and Ctrl+Z/Y; PNG has real 200×300 pixels/alpha, source hash unchanged, persistent available parent/recipe');
 await editor().getByLabel('Format',{exact:true}).selectOption('jpeg');await editor().getByLabel('JPEG quality',{exact:true}).press('Home');for(let n=1;n<25;n++)await editor().getByLabel('JPEG quality',{exact:true}).press('ArrowRight');await click('Export as variant');listing=await list();const jpeg=listing.entries.find(e=>e.path.endsWith('.jpg'));assert(jpeg);const jpg=await fs.readFile(path.join(gallery,jpeg.path));assert.equal(jpg.readUInt16BE(0),0xffd8);assert.equal(hash(await fs.readFile(source)),original);
 record('Native JPEG export writes a separate real JPEG with selected quality, while retaining the source');
 await click('90° left');await dimensions(300,200);await click('Close editor');await editor().getByRole('button',{name:'Continue editing',exact:true}).click();await dimensions(300,200);
 await invoke('plugin:window|close',{label:'main'});await page.getByRole('dialog',{name:'Close Local Studio?',exact:true}).waitFor();assert((await page.getByRole('dialog',{name:'Close Local Studio?',exact:true}).innerText()).includes('Image edits have not been exported'));await page.getByRole('dialog',{name:'Close Local Studio?',exact:true}).getByRole('button',{name:'Cancel',exact:true}).click();
 await stop(false);await launch();page=getPage();await open();await editor().getByRole('button',{name:'Resume draft',exact:true}).click();await dimensions(300,200);await click('Undo');await dimensions(200,300);await click('Flip vertical');assert(await editor().getByRole('button',{name:'Redo',exact:true}).isDisabled());
 record('Real process termination preserves the explicit-resume draft and undo history; consolidated close warning can cancel; new edits remove the redo branch');
 await click('Close editor');await editor().getByRole('button',{name:'Keep draft and close',exact:true}).click();await open();await editor().getByRole('button',{name:'Discard draft',exact:true}).click();await dimensions(320,180);
 await click('Drag crop in image');const box=await editor().locator('.editor-picture').boundingBox();await page.mouse.move(box.x+box.width*.25,box.y+box.height*.25);await page.mouse.down();await page.mouse.move(box.x+box.width*.75,box.y+box.height*.75,{steps:6});await page.mouse.up();assert.equal(await editor().getByLabel('Crop width',{exact:true}).inputValue(),'160');assert.equal(await editor().getByLabel('Crop height',{exact:true}).inputValue(),'90');await click('Apply crop');await dimensions(160,90);
 await editor().getByLabel('Lock aspect ratio',{exact:true}).uncheck();await editor().getByLabel('Width',{exact:true}).fill('123');await editor().getByLabel('Height',{exact:true}).fill('87');await click('Apply size');await dimensions(123,87);
 await page.screenshot({path:path.join(artifactRoot,'editor19-crop.png')});await click('Close editor');await editor().getByRole('button',{name:'Discard and close',exact:true}).click();
 record('Pointer crop maps displayed coordinates to exact pixels; unlocked resize, keep/resume and discard paths work');
 listing=await list();const src=listing.entries.find(e=>e.path==='Editor19/source.png');const request={query:{rootId:listing.rootId,target:{path:src.path,fileId:src.fileId,version:src.thumbnailVersion}},operations:[]};
 await assert.rejects(invoke('editor_export',{request:{...request,query:{...request.query,target:{...request.query.target,version:'stale'}}},format:'png',quality:90}),/gallery_changed/);
 await assert.rejects(invoke('editor_preview',{request:{...request,operations:[{type:'crop',x:319,y:0,width:2,height:1}]}}),/editor_crop/);
 await assert.rejects(invoke('editor_preview',{request:{...request,operations:[{type:'resize',width:16384,height:16384}]}}),/editor_limit/);
 await assert.rejects(invoke('editor_preview',{request:{...request,query:{...request.query,target:{...request.query.target,path:'../escape.png'}}}}),/gallery_path/);
 assert.equal(hash(await fs.readFile(source)),original);record('Typed native IPC rejects stale source, escaping paths, out-of-bounds crops and excessive allocations without changing originals');
 const snapshot=await invoke('bootstrap');await invoke('save_settings',{settings:{...snapshot.settings,theme:'light',uiScale:1.25,shortcuts:{...snapshot.settings.shortcuts,undo:'Ctrl+U',redo:'Ctrl+R'}}});await page.reload();await open();await click('90° right');await dimensions(180,320);await editor().locator('.editor-stage').focus();await page.keyboard.press('Control+u');await dimensions(320,180);await page.keyboard.press('Control+r');await dimensions(180,320);await page.screenshot({path:path.join(artifactRoot,'editor19-light-125.png')});await click('Close editor');await editor().getByRole('button',{name:'Discard and close',exact:true}).click();
 record('Editor works in light theme at 125% with persisted custom undo/redo shortcuts');
}
