import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {randomUUID,createHash} from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
const pause=ms=>new Promise(r=>setTimeout(r,ms));async function until(f,timeout=120000){const end=Date.now()+timeout;while(Date.now()<end){if(await f())return;await pause(150);}throw Error('AI24 condition timed out');}
export async function checkAi24(ctx){
 const {invoke,artifactRoot,record}=ctx;let page=ctx.getPage();const root=path.resolve(import.meta.dirname,'..');const normalized=p=>p.replaceAll('\\','/').replace(/^\/\/\?\//,'').toLowerCase();
 async function workers(){const {stdout}=await promisify(execFile)('powershell',['-NoProfile','-Command',"Get-CimInstance Win32_Process -Filter \"Name='llama-server.exe' OR Name='llama.exe' OR Name='whisper-cli.exe'\" | Select-Object ProcessId,ExecutablePath | ConvertTo-Json -Compress"],{windowsHide:true});const value=stdout.trim()?JSON.parse(stdout):[];return (Array.isArray(value)?value:[value]).filter(p=>p.ExecutablePath&&normalized(p.ExecutablePath).startsWith(normalized(artifactRoot)+'/'));}
 async function shot(name){const c=await page.context().newCDPSession(page);const{data}=await c.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:false});await fs.writeFile(path.join(artifactRoot,name),Buffer.from(data,'base64'));await c.detach();}
 async function dialogs(){await page.evaluate(()=>{const original=window.fetch;window.saveValue=null;window.fetch=(input,options)=>{const u=new URL(typeof input==='string'?input:input.url),c=decodeURIComponent(u.pathname).slice(1);if(u.hostname==='ipc.localhost'&&['plugin:dialog|save','plugin:dialog|message'].includes(c))return Promise.resolve(new Response(JSON.stringify(c.endsWith('|message')?'Ok':window.saveValue),{headers:{'Content-Type':'application/json','Tauri-Response':'ok'}}));return original.call(window,input,options);};});}
 const model=await invoke('ai_import',{path:process.env.LOCAL_STUDIO_TEST_CHAT_MODEL||path.join(root,'.tools/test-models24/qwen2.5-1.5b-instruct-q4_k_m.gguf'),kind:'chat'});assert.equal(model.catalogId,'qwen25-1.5b-q4');assert.equal(model.bytes,1117320736);
 const plan=await invoke('ai_download_plan',{catalogId:'whisper-base'});assert.equal(plan.download.totalBytes,147951465);assert.equal(plan.download.files[0].sha256,'60ed5bc3dd14eea856493d334349b405782ddcaf0028d4b5df4088345fba2efe');assert(normalized(plan.download.destination).startsWith(normalized((await invoke('bootstrap')).paths.visionModels)));
 const download=await invoke('download_start',{planId:plan.id});await until(async()=>{const d=(await invoke('download_list')).find(d=>d.id===download.id);if(['failed','invalid'].includes(d.status))throw Error(JSON.stringify(d));return d.status==='completed';},240000);const speech=await invoke('ai_adopt_download',{downloadId:download.id});assert.equal(speech.catalogId,'whisper-base');
 record('Real pinned GGUF import verifies catalog hash; explicit Whisper download uses the existing verified download queue, intended speech model directory and adoption path');
 await page.getByRole('button',{name:'Assistant',exact:true}).first().click();await page.getByLabel('Chat model',{exact:true}).selectOption(model.id);await page.getByRole('button',{name:'Load model',exact:true}).click();await until(async()=>{const s=await invoke('assistant_status');if(s.error)throw Error(s.error);return s.phase==='ready';});
 async function send(text,language='en',studioTools=true){const before=(await invoke('assistant_status')).messages.length;await invoke('assistant_send',{text,language,studioTools});await until(async()=>{const s=await invoke('assistant_status');if(s.error)throw Error(s.error);return s.phase==='ready'&&s.messages.length>=before+2;});return (await invoke('assistant_status')).messages.at(-1);}
 await page.getByLabel('Message',{exact:true}).fill('Reply in English with one short sentence: what is a subtitle?');await page.getByRole('button',{name:'Send',exact:true}).click();await until(async()=>{const s=await invoke('assistant_status');if(s.error)throw Error(s.error);return s.phase==='ready'&&s.messages.at(-1)?.role==='assistant';});assert((await invoke('assistant_status')).messages.at(-1).text.length>15);
 const german=await send('Antworte auf Deutsch in einem Satz: Wozu dient ein Video-Proxy?','de',false);assert.match(german.text,/Video|Vorschau|Datei|Bearbeit|Proxy/i);
 const hardware=await send('Use get_hardware now and report my actual CPU and RAM.');const h=hardware.tools.find(t=>t.name==='get_hardware');assert(h,h?.text);assert(h.result.cpu);assert(h.result.totalMemoryBytes>1e9);await assert.rejects(invoke('assistant_clear',{confirmed:false}),/ai_confirmation/);
 record('Actual CPU llama.cpp inference answers English/German; model emits a real get_hardware tool call and receives measured hardware; chat deletion requires explicit confirmation');
 const fixtureRoot=process.env.LOCAL_STUDIO_TEST_SPEECH_FIXTURES||path.join(root,'.artifacts');const spoken=path.join(fixtureRoot,'speech24-en.wav'),spokenDe=path.join(fixtureRoot,'speech24-de.wav');const original=createHash('sha256').update(await fs.readFile(spoken)).digest('hex');await invoke('gallery_import',{folder:'',sources:[spoken]});const found=await send('Use search_gallery with query speech24-en and report the matching filename.');const search=found.tools.find(t=>t.name==='search_gallery');assert(search);assert(search.result.entries.some(e=>e.name==='speech24-en.wav'));
 const sd=process.env.LOCAL_STUDIO_TEST_SDXL_MODEL||String.raw`D:\LocalAI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\Juggernaut-XL_v9_RunDiffusionPhoto_v2.safetensors`;await fs.access(sd);await invoke('model_scan_start',{path:path.dirname(sd)});await until(async()=>(await invoke('model_library_list')).scan.status!=='running');const entry=(await invoke('model_library_list')).entries.find(e=>normalized(e.path)===normalized(sd));assert(entry);
 const proposal=await send(`Use prepare_image_job exactly once with modelId ${entry.id}, prompt "a red boat on a quiet lake", negativePrompt "text", width 512, height 768, steps 12, guidance 5, seed 42, sampler "euler". This only prepares settings; do not generate.`);assert(proposal.proposal,JSON.stringify(proposal));assert.equal(proposal.proposal.height,768);assert.equal(normalized(proposal.proposal.modelPath),normalized(sd));assert.equal((await invoke('image_jobs')).length,0);await page.getByRole('button',{name:'Apply settings to image Studio',exact:true}).click();await until(async()=>(await invoke('image_workspace')).workspace.request?.prompt==='a red boat on a quiet lake');assert.equal((await invoke('image_jobs')).length,0);
 record('Model-driven gallery metadata search returns the actual imported file; a real SDXL model produces a validated prepared job, UI applies its parameters, and no generation or download starts implicitly');
 await page.getByRole('button',{name:'Assistant',exact:true}).first().click();await invoke('assistant_send',{text:'Write a very long detailed tutorial with 100 numbered paragraphs about editing videos.',language:'en',studioTools:false});await invoke('assistant_cancel');await until(async()=>{const s=await invoke('assistant_status');return s.phase==='unloaded'&&s.error==='ai_cancelled';});await shot('ai24-assistant.png');
 const history=(await invoke('assistant_status')).messages;await invoke('assistant_load',{modelId:model.id});await until(async()=>(await invoke('assistant_status')).phase==='ready');assert((await workers()).length>0);await ctx.stop(false);await until(async()=>(await workers()).length===0);await ctx.launch();page=ctx.getPage();assert.equal((await invoke('assistant_status')).phase,'unloaded');assert.deepEqual((await invoke('assistant_status')).messages,history);assert.equal((await invoke('ai_models')).length,2);record('Real reply cancellation unloads the server; parent crash kills the loaded worker; restart preserves local history and model registry without silently loading a model');
 let p=await invoke('project_new',{name:'Speech integration',request:null,confirmed:true});p=await invoke('project_add',{sources:[spoken,spokenDe]});const asset=p.assets.find(a=>a.name==='speech24-en.wav'),assetDe=p.assets.find(a=>a.name==='speech24-de.wav');const track={id:randomUUID(),name:'Audio',audio:true,muted:false,locked:false};const metadata=await invoke('video_probe',{id:p.id,assetId:asset.id});const clip={id:randomUUID(),assetId:asset.id,trackId:track.id,name:asset.name,start:3,sourceIn:0,sourceOut:metadata.duration,speed:1.25,fadeIn:0,fadeOut:0,blur:0,brightness:0,contrast:1,saturation:1,keyframes:[{time:0,x:0,y:0,scale:1,rotation:0,opacity:1,volume:1}]};const timeline={width:640,height:360,fps:30,background:'#000000',tracks:[track],clips:[clip],captions:[]};p=await invoke('project_creative_save',{id:p.id,expected:0,creative:{revision:0,image:null,video:timeline}});
 await page.reload();await page.getByRole('button',{name:'Studio',exact:true}).first().click();await page.getByRole('tab',{name:'Video editor',exact:true}).click();await page.getByRole('button',{name:asset.name,exact:true}).click();await page.getByText('Automatic captions · local',{exact:true}).click();await page.getByLabel('Speech model',{exact:true}).selectOption(speech.id);await page.getByLabel('Spoken language',{exact:true}).selectOption('en');await page.getByRole('button',{name:'Transcribe clip',exact:true}).click();
 await until(async()=>{const j=(await invoke('transcription_jobs'))[0];if(j?.status==='failed')throw Error(JSON.stringify(j));return j?.status==='completed';});const j=(await invoke('transcription_jobs'))[0];assert(j.captions.length>0);assert.match(j.captions.map(c=>c.text).join(' '),/Local Studio|local studio|computer|pictures/i);assert(j.captions.every(c=>c.start>=3&&c.end<=3+metadata.duration/1.25+.001));assert.equal(j.sourceSha256,original);
 await until(()=>page.getByLabel('Recognized text 1',{exact:true}).count());await page.getByLabel('Recognized text 1',{exact:true}).fill('Reviewed caption in Local Studio.');await page.getByRole('button',{name:'Apply captions to timeline',exact:true}).click();await until(async()=>(await invoke('project_snapshot')).creative.video.captions[0]?.text==='Reviewed caption in Local Studio.');assert.equal((await invoke('project_snapshot')).creative.video.captions.length,j.captions.length);
 await dialogs();const srt=path.join(artifactRoot,'speech-reviewed.srt');await page.evaluate(v=>window.saveValue=v,srt);await page.getByRole('button',{name:'Save SRT',exact:true}).click();await until(()=>fs.stat(srt).then(()=>true,()=>false));assert.match(await fs.readFile(srt,'utf8'),/Reviewed caption/);await page.getByRole('button',{name:'Undo',exact:true}).click();await until(async()=>(await invoke('project_snapshot')).creative.video.captions.length===0);await page.getByRole('button',{name:'Redo',exact:true}).click();await until(async()=>(await invoke('project_snapshot')).creative.video.captions.length===j.captions.length);await page.getByText('Automatic captions · local',{exact:true}).scrollIntoViewIfNeeded();await shot('ai24-transcription.png');
 record('Real English audio is decoded by FFmpeg and recognized by Whisper; timestamps account for clip offset/speed, edited text applies to the timeline in one Undo/Redo step and exports as actual SRT');
 p=await invoke('project_snapshot');const metaDe=await invoke('video_probe',{id:p.id,assetId:assetDe.id});const clipDe={...clip,id:randomUUID(),assetId:assetDe.id,name:assetDe.name,start:0,sourceOut:metaDe.duration,speed:1};p=await invoke('project_creative_save',{id:p.id,expected:p.creative.revision,creative:{...p.creative,video:{...p.creative.video,clips:[...p.creative.video.clips,clipDe]}}});const deJob=await invoke('transcription_start',{id:p.id,clipId:clipDe.id,modelId:speech.id,language:'de'});await until(async()=>{const j=(await invoke('transcription_jobs')).find(j=>j.id===deJob.id);if(j.status==='failed')throw Error(j.error);return j.status==='completed';});const deResult=(await invoke('transcription_jobs')).find(j=>j.id===deJob.id);assert.match(deResult.captions.map(c=>c.text).join(' '),/Studio|Bilder|Videos|Computer|Dateien/i);
 const cancelled=await invoke('transcription_start',{id:p.id,clipId:clipDe.id,modelId:speech.id,language:'de'});await invoke('transcription_cancel',{id:cancelled.id});await until(async()=>(await invoke('transcription_jobs')).find(j=>j.id===cancelled.id).status==='cancelled');assert.equal(createHash('sha256').update(await fs.readFile(spoken)).digest('hex'),original);
 const target=path.join(artifactRoot,'Speech.localstudio');await invoke('project_save',{path:target});await invoke('project_close',{confirmed:true});await invoke('project_open',{path:target,confirmed:true});assert.equal((await invoke('project_snapshot')).creative.video.captions[0].text,'Reviewed caption in Local Studio.');record('Actual German speech is recognized; speech cancellation leaves originals byte-identical and reviewed captions survive saving/reopening a transportable project');
 const settings=(await invoke('bootstrap')).settings;await invoke('save_settings',{settings:{...settings,language:'de',theme:'light',uiScale:1.25}});await page.reload();await page.getByRole('button',{name:'Assistent',exact:true}).first().click();await shot('ai24-german-light-125.png');record('Assistant is available in German/light theme at 125%; model weights remain outside distributable files');
}
