use super::*;
use crate::projects::creative::{Caption,Clip};
use std::io::{BufRead,BufReader};
#[derive(Clone,Serialize,Deserialize)]#[serde(rename_all="camelCase")]
pub struct SpeechJob{pub id:String,pub project_id:String,pub asset_id:String,pub source_sha256:String,pub model_id:String,pub model_sha256:Option<String>,pub name:String,pub language:String,pub clip:Clip,pub status:String,pub phase:String,pub progress:Option<f64>,pub elapsed_ms:u64,pub error:Option<String>,pub captions:Vec<Caption>}
impl AiEngine{
 fn speech_update(&self,id:&str,change:impl FnOnce(&mut SpeechJob))->Result<()> {let mut s=self.speech.lock().map_err(err)?;let j=s.iter_mut().find(|j|j.id==id).ok_or("ai_job_missing")?;change(j);self.db.lock().map_err(err)?.execute("INSERT OR REPLACE INTO speech_jobs VALUES(?1,?2)",rusqlite::params![j.id,serde_json::to_string(j).map_err(err)?]).map_err(err)?;Ok(())}
}
fn run(mut command:Command,cancel:&AtomicBool,mut progress:impl FnMut(f64))->Result<()> {
 let mut child=command.stdout(Stdio::null()).stderr(Stdio::piped()).spawn().map_err(|_|"ai_runtime")?;let guard=match ProcessGroup::attach(&child){Ok(g)=>g,Err(error)=>{let _=child.kill();let _=child.wait();return Err(error)}};
 let mut memory=sysinfo::System::new();memory.refresh_memory();guard.limit_memory((memory.available_memory().saturating_mul(3)/4).min(8*1024*1024*1024) as usize)?;
 let pipe=child.stderr.take().ok_or("ai_runtime")?;let(tx,rx)=std::sync::mpsc::channel();let reader=thread::spawn(move||{for line in BufReader::new(pipe.take(4*1024*1024)).lines().map_while(std::result::Result::ok){if let Some((_,part))=line.split_once("progress ="){if let Some(p)=part.split('%').next().and_then(|s|s.trim().parse::<f64>().ok()){let _=tx.send(p/100.);}}}});
 let start=Instant::now();let result=loop{if cancel.load(Ordering::SeqCst)||start.elapsed()>Duration::from_secs(7200){let _=child.kill();let _=child.wait();break Err(if cancel.load(Ordering::SeqCst){"ai_cancelled"}else{"ai_timeout"}.into());}for p in rx.try_iter(){if p.is_finite(){progress(p.clamp(0.,0.99));}}if let Some(status)=child.try_wait().map_err(err)?{break if status.success(){Ok(())}else{Err("ai_speech_decode".into())};}thread::sleep(Duration::from_millis(80));};drop(guard);let _=reader.join();result
}
struct Work{path:PathBuf,pins:Vec<File>}
impl Drop for Work{fn drop(&mut self){for file in ["audio.wav","transcript.json"]{let _=gallery::delete_owned(&self.path.join(file));}self.pins.clear();let _=fs::remove_dir(&self.path);}}
fn parse_captions(value:Value,clip:&Clip)->Result<Vec<Caption>>{
 let segments=value["transcription"].as_array().ok_or("ai_speech_output")?;if segments.len()>500{return Err("ai_caption_limit".into());}let duration=(clip.source_out-clip.source_in)/clip.speed;let mut captions=vec![];
 for segment in segments{let from=segment["offsets"]["from"].as_f64().ok_or("ai_speech_output")?;let to=segment["offsets"]["to"].as_f64().ok_or("ai_speech_output")?;let text=segment["text"].as_str().ok_or("ai_speech_output")?.trim();if !from.is_finite()||!to.is_finite()||from<0.||to<from||text.len()>2000||text.contains('\0'){return Err("ai_speech_output".into());}let start=(from/1000./clip.speed).min(duration);let end=(to/1000./clip.speed).min(duration);if end-start<0.001||text.is_empty(){continue;}captions.push(Caption{id:uuid(),start:clip.start+start,end:clip.start+end,text:text.into(),size:40,color:"#ffffff".into(),y:0.9});}
 Ok(captions)
}
#[tauri::command]pub fn transcription_jobs(engine:tauri::State<'_,Arc<AiEngine>>)->Result<Vec<SpeechJob>>{Ok(engine.speech.lock().map_err(err)?.clone())}
#[tauri::command]pub fn transcription_cancel(id:String,engine:tauri::State<'_,Arc<AiEngine>>)->Result<()>{if engine.speech.lock().map_err(err)?.iter().any(|j|j.id==id&&j.status=="running"){engine.speech_cancel.store(true,Ordering::SeqCst);}Ok(())}
#[tauri::command]pub fn transcription_start(id:String,clip_id:String,model_id:String,language:String,engine:tauri::State<'_,Arc<AiEngine>>,projects:tauri::State<'_,Arc<Projects>>,video:tauri::State<'_,Arc<VideoEngine>>,core:tauri::State<'_,Arc<Core>>)->Result<SpeechJob>{
 if !["auto","de","en"].contains(&language.as_str()){return Err("ai_parameters".into());}let p=projects.creative_snapshot(&id)?;let clip=p.creative.as_ref().and_then(|c|c.video.as_ref()).and_then(|t|t.clips.iter().find(|c|c.id==clip_id)).cloned().ok_or("creative_source")?;let asset=p.assets.iter().find(|a|a.id==clip.asset_id&&a.kind!="image").ok_or("creative_source")?;
 let e=engine.inner().clone();let v=video.inner().clone();let base=PathBuf::from(core.storage_paths()?.temporary).join("speech-jobs");if e.stopped.load(Ordering::SeqCst)||e.speech_busy.compare_exchange(false,true,Ordering::SeqCst,Ordering::SeqCst).is_err(){return Err("ai_busy".into());}e.speech_cancel.store(false,Ordering::SeqCst);
 let job=SpeechJob{id:uuid(),project_id:id,asset_id:asset.id.clone(),source_sha256:asset.sha256.clone(),model_id,name:asset.name.clone(),language,clip,status:"running".into(),phase:"checking".into(),progress:None,elapsed_ms:0,error:None,model_sha256:None,captions:vec![]};
 let saved=(||{let mut jobs=e.speech.lock().map_err(err)?;e.db.lock().map_err(err)?.execute("INSERT INTO speech_jobs VALUES(?1,?2)",rusqlite::params![job.id,serde_json::to_string(&job).map_err(err)?]).map_err(err)?;jobs.insert(0,job.clone());jobs.truncate(30);Ok::<(),String>(())})();if let Err(error)=saved{e.speech_busy.store(false,Ordering::SeqCst);return Err(error);}let j=job.clone();
 thread::spawn(move||{let start=Instant::now();let result=(||{
  e.speech_update(&j.id,|j|j.phase="waiting".into())?;
  let _admission=crate::resources::shared().acquire(&j.id,"speech",1024*1024*1024,false,&e.speech_cancel).map_err(|v|if v=="resource_cancelled"{"ai_cancelled".into()}else{v})?;
  let(model,_model)=e.model(&j.model_id,"speech")?;e.speech_update(&j.id,|j|j.model_sha256=Some(model.sha256.clone()))?;
  let(runtime,_runtime)=e.runtime("speech")?;let(ffmpeg,_ffmpeg)=v.runtime()?;let(_,source,_source,_pins)=Projects::creative_source(&p,&j.asset_id)?;let metadata=crate::projects::creative::video::probe(&ffmpeg,&source)?;if !metadata.audio{return Err("video_no_audio".into());}if j.clip.source_out>metadata.duration+0.1{return Err("video_range".into());}
  if e.speech_cancel.load(Ordering::SeqCst){return Err("ai_cancelled".into());}fs::create_dir_all(&base).map_err(err)?;let mut pins=gallery::directory_guards(&base)?;let path=base.join(&j.id);fs::create_dir(&path).map_err(err)?;pins.extend(gallery::directory_guards(&path)?);let work=Work{path,pins};
  e.speech_update(&j.id,|j|j.phase="decoding".into())?;let mut c=command(&ffmpeg.join("ffmpeg.exe"));c.current_dir(&work.path).args(["-hide_banner","-nostdin","-v","error","-n","-max_alloc","268435456","-protocol_whitelist","file,pipe","-format_whitelist","mov,matroska,webm,mp3,wav,flac,ogg","-ss",&j.clip.source_in.to_string(),"-threads","2","-i"]).arg(&source).args(["-t",&(j.clip.source_out-j.clip.source_in).to_string(),"-map","0:a:0","-vn","-ac","1","-ar","16000","-c:a","pcm_s16le","-map_metadata","-1","audio.wav"]);run(c,&e.speech_cancel,|_|{})?;
  let _wav=gallery::lock_file(&work.path.join("audio.wav"))?;e.speech_update(&j.id,|j|{j.phase="transcribing".into();j.progress=Some(0.);})?;let mut c=command(&runtime.join("whisper-cli.exe"));c.current_dir(&work.path).args(["--model",&model.path,"--file","audio.wav","--language",&j.language,"--threads","4","--no-gpu","--output-json","--output-file","transcript","--print-progress","--max-len","80","--split-on-word"]);
  run(c,&e.speech_cancel,|p|{let _=e.speech_update(&j.id,|j|{j.progress=Some(p);j.elapsed_ms=start.elapsed().as_millis() as u64;});})?;
  let mut file=gallery::lock_file(&work.path.join("transcript.json"))?;if file.metadata().map_err(err)?.len()>1024*1024{return Err("ai_speech_output".into());}let mut bytes=vec![];file.read_to_end(&mut bytes).map_err(err)?;let captions=parse_captions(serde_json::from_slice(&bytes).map_err(|_|"ai_speech_output")?,&j.clip)?;drop(file);drop(_wav);Ok(captions)
 })();let cancelled=e.speech_cancel.load(Ordering::SeqCst);let _=e.speech_update(&j.id,|j|{j.elapsed_ms=start.elapsed().as_millis() as u64;match result{Ok(captions)if !cancelled=>{j.captions=captions;j.status="completed".into();j.phase="completed".into();j.progress=Some(1.);},_ if cancelled=>{j.status="cancelled".into();j.error=Some("ai_cancelled".into());},Err(error)=>{j.status="failed".into();j.error=Some(error);},_=>{}}});e.speech_busy.store(false,Ordering::SeqCst);
 });Ok(job)
}
#[cfg(test)]mod tests{use super::*;
 #[test]fn timestamps_follow_trim_speed_and_timeline_offset(){let c:Clip=serde_json::from_value(json!({"id":"x","assetId":"a","trackId":"t","name":"n","start":5,"sourceIn":10,"sourceOut":14,"speed":2,"fadeIn":0,"fadeOut":0,"blur":0,"brightness":0,"contrast":1,"saturation":1,"keyframes":[]})).unwrap();let out=parse_captions(json!({"transcription":[{"offsets":{"from":500,"to":2000},"text":" Hallo "},{"offsets":{"from":3000,"to":5000},"text":"Ende"}]}),&c).unwrap();assert_eq!(out[0].start,5.25);assert_eq!(out[0].end,6.);assert_eq!(out[1].end,7.);assert_eq!(out[0].text,"Hallo");assert!(parse_captions(json!({"transcription":[{"offsets":{"from":-1,"to":2},"text":"bad"}]}),&c).is_err());}
}
