import {invoke} from '@tauri-apps/api/core';
import type {ImageRequest} from './image-api';
import type {Caption,Clip,Timeline} from './creative-state';
import type {DownloadPlan} from './download-api';
export interface AiModel{id:string;name:string;kind:'chat'|'speech';path:string;bytes:number;sha256:string;catalogId:string|null}
export interface CatalogModel{id:string;name:string;kind:'chat'|'speech';repo:string;revision:string;file:string;bytes:number;license:string}
export interface ChatLine{id:string;role:string;text:string;tools:{name:string;arguments:unknown;result:unknown}[];proposal:ImageRequest|null}
export interface ChatState{restricted?:boolean;locked?:boolean;phase:string;modelId:string|null;error:string|null;messages:ChatLine[];elapsedMs:number;tokens:number|null}
export interface SpeechJob{id:string;projectId:string;assetId:string;sourceSha256:string;modelId:string;modelSha256:string|null;name:string;language:string;clip:Clip;status:string;phase:string;progress:number|null;elapsedMs:number;error:string|null;captions:Caption[]}
export const ai={catalog:()=>invoke<CatalogModel[]>('ai_catalog'),models:()=>invoke<AiModel[]>('ai_models'),import:(path:string,kind:string)=>invoke<AiModel>('ai_import',{path,kind}),plan:(catalogId:string)=>invoke<DownloadPlan>('ai_download_plan',{catalogId}),adopt:(downloadId:string)=>invoke<AiModel>('ai_adopt_download',{downloadId}),status:()=>invoke<ChatState>('assistant_status'),load:(modelId:string)=>invoke<void>('assistant_load',{modelId}),unload:()=>invoke<void>('assistant_unload'),send:(text:string,language:string,studioTools:boolean)=>invoke<void>('assistant_send',{text,language,studioTools}),cancel:()=>invoke<void>('assistant_cancel'),clear:(confirmed:boolean)=>invoke<ChatState>('assistant_clear',{confirmed}),jobs:()=>invoke<SpeechJob[]>('transcription_jobs'),transcribe:(id:string,clipId:string,modelId:string,language:string)=>invoke<SpeechJob>('transcription_start',{id,clipId,modelId,language}),cancelSpeech:(id:string)=>invoke<void>('transcription_cancel',{id})};
export function mergeTranscript(timeline:Timeline,job:SpeechJob,captions:Caption[],sourceSha:string):Timeline{
 const stable=(value:unknown)=>JSON.stringify(value,(_,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]])):v);
 const clip=timeline.clips.find(c=>c.id===job.clip.id);if(job.status!=='completed'||!clip||stable(clip)!==stable(job.clip)||sourceSha!==job.sourceSha256)throw Error('ai_clip_changed');
 if(!captions.length||timeline.captions.length+captions.length>500||new Set(captions.map(c=>c.id)).size!==captions.length||captions.some(c=>timeline.captions.some(a=>a.id===c.id)))throw Error('ai_caption_limit');
 if(captions.some(c=>!Number.isFinite(c.start)||!Number.isFinite(c.end)||c.start<0||c.end<=c.start||c.end>3600||!c.text.trim()||c.text.length>2000||c.text.includes('\0')))throw Error('ai_speech_output');
 return {...timeline,captions:[...timeline.captions,...captions]};
}
const messages:Record<string,[string,string]>={resource_memory:['Nicht genug freier RAM. Andere Modelle entladen.','Not enough available RAM. Unload other models.'],resource_timeout:['Zu lange auf Ressourcen gewartet.','Resource wait timed out.'],ai_busy:['Eine KI-Aufgabe läuft bereits.','An AI task is already running.'],ai_not_loaded:['Zuerst ein Chatmodell laden.','Load a chat model first.'],ai_model_load:['Das Modell konnte nicht geladen werden. GGUF-Kompatibilität und freien RAM prüfen.','Could not load the model. Check GGUF compatibility and free RAM.'],ai_memory:['Zu wenig freier Arbeitsspeicher für Modell und Kontext.','Not enough available memory for model and context.'],ai_model_invalid:['Kein unterstütztes GGUF- oder Whisper-GGML-Modell.','Not a supported GGUF or Whisper GGML model.'],ai_model_changed:['Die Modelldatei wurde verändert oder verschoben. Erneut importieren.','Model file changed or moved. Import it again.'],ai_model_missing:['Modell nicht gefunden.','Model not found.'],ai_cancelled:['Abgebrochen. Bei Chat-Abbruch wird das Modell entladen.','Cancelled. Cancelling chat unloads the model.'],ai_interrupted:['Beim letzten Beenden unterbrochen; bei Bedarf erneut starten.','Interrupted on last exit; start again if needed.'],ai_runtime:['Die geprüfte KI-Laufzeit fehlt. Programm mit allen Runtime-Ordnern aktualisieren.','Verified AI runtime is missing. Update the app with all runtime folders.'],ai_runtime_changed:['Die KI-Laufzeit wurde verändert. Programmdateien erneut installieren.','AI runtime changed. Reinstall the application files.'],ai_inference:['Die lokale Modellberechnung ist fehlgeschlagen.','Local model inference failed.'],ai_context_or_inference:['Der Kontext ist zu groß oder die lokale Berechnung ist fehlgeschlagen. Einen neuen Chat versuchen.','Context is too large or local inference failed. Try a new chat.'],ai_timeout:['Zeitlimit erreicht.','Time limit reached.'],ai_tool_limit:['Zu viele Werkzeugaufrufe. Bitte einen konkreteren Auftrag formulieren.','Too many tool calls. Please make the request more specific.'],ai_image_model:['Für diesen Auftrag wird ein installiertes, vollständiges SDXL-Modell benötigt.','This task requires an installed complete SDXL model.'],ai_clip_changed:['Clip oder Quelle wurde inzwischen verändert. Transkription erneut starten.','Clip or source changed. Transcribe again.'],ai_caption_limit:['Keine neuen Untertitel, bereits übernommen oder Grenze von 500 erreicht.','No new captions, already applied, or the 500-caption limit was reached.'],ai_speech_decode:['Ton konnte nicht dekodiert oder transkribiert werden. Modell und Quelldatei prüfen.','Audio could not be decoded or transcribed. Check model and source.'],ai_speech_output:['Ungültige Untertitelzeiten oder Texte.','Invalid caption times or text.'],video_no_audio:['Dieses Medium enthält keine Tonspur.','This media has no audio track.']};
export const aiError=(e:unknown,de:boolean)=>messages[String(e)]?.[de?0:1]??String(e);
export const aiPhase=(s:string,de:boolean)=>({unloading:['Modell wird entladen','Unloading model'],waiting:['Wartet auf Ressourcen','Waiting for resources'],loading:['Modell wird geprüft und geladen','Checking and loading model'],ready:['Bereit · lokal auf CPU','Ready · local CPU'],running:['Antwort wird berechnet','Generating reply'],unloaded:['Modell entladen','Model unloaded'],checking:['Quelle und Modell prüfen','Checking source and model'],decoding:['Ton vorbereiten','Preparing audio'],transcribing:['Sprache erkennen','Transcribing'],completed:['Fertig','Completed'],cancelled:['Abgebrochen','Cancelled'],failed:['Fehlgeschlagen','Failed'],interrupted:['Unterbrochen','Interrupted']} as Record<string,string[]>)[s]?.[de?0:1]??s;
