import {describe,it,expect} from 'vitest';import {mergeTranscript,type SpeechJob} from './ai-api';import {newTimeline,defaultPose,uid,type Clip,type Caption} from './creative-state';
describe('transcript application preserves the exact source and current edits',()=>{
 const timeline=newTimeline();const clip:Clip={id:uid(),assetId:uid(),trackId:timeline.tracks[0].id,name:'speech',start:5,sourceIn:10,sourceOut:14,speed:2,fadeIn:0,fadeOut:0,blur:0,brightness:0,contrast:1,saturation:1,keyframes:[defaultPose()]};timeline.clips=[clip];
 const caption:Caption={id:uid(),start:5.25,end:6,text:'Hello',size:40,color:'#ffffff',y:.9};const job={status:'completed',clip:structuredClone(clip),sourceSha256:'abc'} as SpeechJob;
 it('adds reviewed captions while retaining existing captions and source clips',()=>{const existing={...caption,id:uid(),text:'Manual'};const result=mergeTranscript({...timeline,captions:[existing]},job,[caption],'abc');expect(result.captions).toEqual([existing,caption]);expect(result.clips).toBe(timeline.clips);expect(timeline.captions).toEqual([]);});
 it('rejects stale trim/speed/source and repeat application',()=>{expect(()=>mergeTranscript({...timeline,clips:[{...clip,speed:1}]},job,[caption],'abc')).toThrow('ai_clip_changed');expect(()=>mergeTranscript(timeline,job,[caption],'changed')).toThrow('ai_clip_changed');expect(()=>mergeTranscript({...timeline,captions:[caption]},job,[caption],'abc')).toThrow('ai_caption_limit');});
 it('rejects invalid timing and unsafe draft contents',()=>{for(const value of [{...caption,end:5},{...caption,start:NaN},{...caption,end:4000},{...caption,text:'\0'}])expect(()=>mergeTranscript(timeline,job,[value],'abc')).toThrow('ai_speech_output');});
 it('compares clip values independently of JSON property ordering',()=>{const reordered=Object.fromEntries(Object.entries(clip).reverse()) as unknown as Clip;expect(mergeTranscript({...timeline,clips:[reordered]},job,[caption],'abc').captions).toEqual([caption]);});
});
