import {useEffect,useState} from 'react';
import {open} from '@tauri-apps/plugin-dialog';
import {ai,aiError,type AiModel,type CatalogModel} from './ai-api';
import {downloads,activeDownload,type DownloadItem,type DownloadPlan} from './download-api';
export default function AiModels({kind,de,onModels}:{kind:'chat'|'speech';de:boolean;onModels:(models:AiModel[])=>void}){
 const [catalog,setCatalog]=useState<CatalogModel[]>([]),[models,setModels]=useState<AiModel[]>([]),[jobs,setJobs]=useState<DownloadItem[]>([]),[plan,setPlan]=useState<DownloadPlan|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const t=(a:string,b:string)=>de?a:b;
 async function refresh(){const m=(await ai.models()).filter(m=>m.kind===kind);setModels(m);onModels(m);}
 useEffect(()=>{let live=true;void ai.catalog().then(c=>{if(live)setCatalog(c.filter(m=>m.kind===kind));}).catch(e=>setError(aiError(e,de)));void refresh().catch(e=>setError(aiError(e,de)));const poll=()=>void downloads.list().then(j=>{if(live)setJobs(j);}).catch(e=>{if(live)setError(aiError(e,de));});poll();const timer=setInterval(poll,1000);return()=>{live=false;clearInterval(timer);};},[kind]);
 async function run(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();await refresh();}catch(e){setError(aiError(e,de));}finally{setBusy(false);}}
 return <details className="panel ai-models"><summary>{t('Modelle verwalten','Manage models')} · {models.length} {t('lokal','local')}</summary>
 <p>{t('Modelle werden nur auf deinen Wunsch geladen. Danach funktioniert die Berechnung offline. Die GB-Angabe betrifft die Datei; im Arbeitsspeicher wird zusätzlich Platz benötigt.','Models download only when requested. Inference then works offline. GB is file size; additional working memory is required.')}</p>
 {catalog.map(m=><div className="ai-model-row" key={m.id}><div><strong>{m.name}</strong><small>{(m.bytes/1e9).toFixed(2)} GB · {m.license} · {m.repo}</small></div><button className="button secondary" disabled={busy||jobs.some(j=>j.repo===m.repo&&j.revision===m.revision&&j.status!=='cancelled')} onClick={()=>void run(async()=>setPlan(await ai.plan(m.id)))}>{t('Download vorbereiten','Prepare download')}</button></div>)}
 {plan&&<div className="ai-download-review"><p>{plan.download.repo} · {(plan.download.totalBytes/1e9).toFixed(2)} GB<br/>{t('Benötigter freier Speicher','Required free disk space')}: {(plan.additionalBytes/1e9).toFixed(2)} GB</p><p className="project-path">{plan.download.destination}</p><button className="button primary" disabled={busy} onClick={()=>void run(async()=>{await downloads.start(plan.id);setPlan(null);})}>{t('Herunterladen','Download')}</button><button className="button secondary" onClick={()=>setPlan(null)}>{t('Abbrechen','Cancel')}</button></div>}
 {jobs.filter(j=>catalog.some(m=>m.repo===j.repo&&m.revision===j.revision)).map(j=><div className="ai-download-review" key={j.id}><strong>{j.repo}</strong><p>{j.status} · {(j.downloadedBytes/1e9).toFixed(2)} / {(j.totalBytes/1e9).toFixed(2)} GB</p>{activeDownload(j)&&<progress max={j.totalBytes||1} value={j.downloadedBytes}/>}<div className="creative-buttons">{['downloading','queued','verifying'].includes(j.status)&&<button disabled={busy} onClick={()=>void run(()=>downloads.action(j.id,'pause'))}>{t('Pausieren','Pause')}</button>}{['paused','failed'].includes(j.status)&&<button disabled={busy} onClick={()=>void run(()=>downloads.action(j.id,'resume'))}>{t('Fortsetzen','Resume')}</button>}{activeDownload(j)&&<button disabled={busy} onClick={()=>void run(()=>downloads.action(j.id,'cancel'))}>{t('Download abbrechen','Cancel download')}</button>}{j.status==='completed'&&<button disabled={busy||models.some(m=>m.catalogId===catalog.find(c=>c.repo===j.repo)?.id)} onClick={()=>void run(()=>ai.adopt(j.id))}>{t('Modell verwenden','Use model')}</button>}</div>{j.error&&<p role="alert">{j.error}</p>}</div>)}
 <button className="button secondary" disabled={busy} onClick={()=>void run(async()=>{const path=await open({multiple:false,filters:[{name:kind==='chat'?'GGUF':'Whisper GGML',extensions:[kind==='chat'?'gguf':'bin']}]});if(path)await ai.import(path,kind);})}>{t('Vorhandene Modelldatei hinzufügen','Add existing model file')}</button>
 {models.map(m=><p className="project-path" key={m.id}>{m.name} · {(m.bytes/1e9).toFixed(2)} GB · {m.catalogId?t('Katalog-Prüfsumme bestätigt','Catalog checksum verified'):t('Eigene Datei · Kompatibilität beim Laden geprüft','Custom file · compatibility checked on load')}<br/>{m.path}</p>)}
 {busy&&<p role="status">{t('Modell und Dateien werden geprüft …','Checking model and files …')}</p>}{error&&<p role="alert" className="notice warning">{error}</p>}
 </details>;
}
