import {createPortal} from 'react-dom';
import {useWindowFrame} from './WindowFrame';
import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {listen} from '@tauri-apps/api/event';
import type {useProject} from './useProject';
import type {Settings} from './types';
import {menuContext} from './menu-context';
import {shortcutFor} from './shortcuts';
type Props={projects:ReturnType<typeof useProject>;settings:Settings;locked:boolean;workspaceRecovery:boolean;onProjectDetails:()=>void;projectChanged:boolean;onSettings:()=>void;onHelp:()=>void;onAbout:()=>void;onUpdates:()=>void;onZoom:(scale:number)=>void;onError:(e:unknown)=>void};
export default function AppMenu(props:Props){
 const frame=useWindowFrame();const buttons=useRef<(HTMLButtonElement|null)[]>([]);const [opened,setOpened]=useState<number|null>(null);const opening=useRef(false);
 const latest=useRef(props);latest.current=props;const [tick,setTick]=useState(0),[creating,setCreating]=useState(false),[name,setName]=useState('');const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(creating){setName('');dialog.current?.showModal();}},[creating]);
 useEffect(()=>{const change=()=>setTick(n=>n+1);window.addEventListener('menu-context',change);const observer=new MutationObserver(records=>{if(records.some(r=>r.type==='attributes'||[...r.addedNodes,...r.removedNodes].some(n=>n instanceof HTMLElement&&(n.matches('dialog,[aria-modal]')||n.querySelector('dialog,[aria-modal]')))))change();});observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['open','aria-modal']});return()=>{observer.disconnect();window.removeEventListener('menu-context',change);};},[]);
 function enabled(){const p=latest.current;const modal=!!document.querySelector('dialog[open],[aria-modal="true"]');const context=menuContext();const ids:string[]=[];
 if(!modal&&!p.locked){ids.push('settings','help','updates','about','exit','projectDetails');if(p.projects.ready&&!p.projects.busy){ids.push('projectOpen');if(p.projects.project)ids.push('projectClose');if(p.projects.project?.recovery&&!p.projects.project.locked)ids.push('projectRecover');else if(!p.workspaceRecovery&&!p.projects.project?.locked)ids.push('projectNew','projectSave','projectSaveAs','projectAdd');p.projects.recent.forEach((r,i)=>{if(r.available)ids.push(`recent-${i}`);});}}
 if(!p.locked&&(!modal||document.querySelector('.image-editor[open]'))){ids.push('uiZoomIn','uiZoomOut','uiZoomReset');if(context)ids.push(...Object.keys(context.actions));}return ids;
 }
 async function action(id:string){if(!enabled().includes(id))return;const p=latest.current;const view=menuContext()?.actions[id as keyof NonNullable<ReturnType<typeof menuContext>>['actions']];if(view){view();return;}if(id.startsWith('recent-')){const r=p.projects.recent[Number(id.slice(7))];if(r)await p.projects.openPath(r.path);return;}
 switch(id){case'projectDetails':p.onProjectDetails();break;case'projectNew':setCreating(true);break;case'projectOpen':await p.projects.open();break;case'projectSave':await p.projects.save();break;case'projectSaveAs':await p.projects.save(true);break;case'projectAdd':await p.projects.add();break;case'projectRecover':await p.projects.recover();break;case'projectClose':await p.projects.close();break;case'exit':window.dispatchEvent(new Event('local-studio-exit'));break;case'settings':p.onSettings();break;case'help':p.onHelp();break;case'about':p.onAbout();break;case'updates':p.onUpdates();break;case'uiZoomIn':p.onZoom(p.settings.uiScale+.1);break;case'uiZoomOut':p.onZoom(p.settings.uiScale-.1);break;case'uiZoomReset':p.onZoom(1);break;}
 }
 const handler=useRef(action);handler.current=action;
 useEffect(()=>{let disposed=false;let off:(()=>void)|undefined;void listen<string>('app-menu',e=>void handler.current(e.payload).catch(latest.current.onError)).then(fn=>{if(disposed)fn();else off=fn;});const key=(e:KeyboardEvent)=>{if(e.defaultPrevented||e.repeat)return;const command=shortcutFor(e,latest.current.settings.shortcuts);if(command&&['projectNew','projectOpen','projectSaveAs','projectClose'].includes(command)){e.preventDefault();void handler.current(command).catch(latest.current.onError);}};window.addEventListener('keydown',key);return()=>{disposed=true;off?.();window.removeEventListener('keydown',key);};},[]);
 const project=props.projects.project;
 const title=project?`${project.locked?'18+':project.name}${!project.locked&&!project.recovery&&(project.dirty||props.projectChanged)?' *':''} – Local Studio`:'Local Studio';
 const menuState=()=>({de:latest.current.settings.language==='de',enabled:enabled(),shortcuts:latest.current.settings.shortcuts,recent:latest.current.projects.recent.map(r=>r.name),theme:latest.current.settings.theme,title});
 useEffect(()=>{frame.setTitle(title);return()=>frame.setTitle('Local Studio');},[title,frame.setTitle]);
 useEffect(()=>{void invoke('app_menu_update',{state:menuState()}).catch(props.onError);},[props.settings,props.locked,props.workspaceRecovery,props.projects.ready,props.projects.busy,project?.id,project?.recovery,project?.locked,props.projects.recent,title,tick,creating]);
 async function openMenu(group:number){if(opening.current)return;const button=buttons.current[group];if(!button)return;const rect=button.getBoundingClientRect();opening.current=true;setOpened(group);try{await invoke('app_menu_update',{state:{...menuState(),popup:{group,x:rect.left,y:rect.bottom}}});}catch(e){latest.current.onError(e);}finally{opening.current=false;setOpened(null);}}
 const openRef=useRef(openMenu);openRef.current=openMenu;
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.defaultPrevented||document.querySelector('dialog[open],[aria-modal="true"]'))return;if(e.key==='F10'&&!e.shiftKey){e.preventDefault();buttons.current[0]?.focus();return;}if(e.altKey&&!e.ctrlKey&&!e.shiftKey){const keys=latest.current.settings.language==='de'?['d','b','a','h']:['f','e','v','h'];const group=keys.indexOf(e.key.toLowerCase());if(group>=0){e.preventDefault();buttons.current[group]?.focus();void openRef.current(group);}}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const de=props.settings.language==='de';return <>{frame.menuHost&&createPortal(<nav className="window-menubar" role="menubar" aria-label={de?'Hauptmenü':'Main menu'}>{(de?['Datei','Bearbeiten','Ansicht','Hilfe']:['File','Edit','View','Help']).map((label,i)=><button key={i} ref={el=>{buttons.current[i]=el;}} role="menuitem" aria-haspopup="menu" aria-expanded={opened===i} onClick={()=>void openMenu(i)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();void openMenu(i);}if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();buttons.current[(i+(e.key==='ArrowRight'?1:3))%4]?.focus();}if(e.key==='Escape')e.currentTarget.blur();}}>{label}</button>)}</nav>,frame.menuHost)}{creating?<dialog ref={dialog} className="image-exit-dialog project-create-dialog" aria-label={de?'Neues Projekt':'New project'} onCancel={()=>setCreating(false)}><h2>{de?'Neues Projekt':'New project'}</h2><form onSubmit={e=>{e.preventDefault();if(name.trim())void props.projects.create(name.trim()).then(ok=>{if(ok)setCreating(false);});}}><label className="project-name-field">{de?'Projektname':'Project name'}<input autoFocus maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><p>{de?'Aktuelle Studio-Eingaben werden übernommen. Medien können anschließend hinzugefügt werden.':'Current Studio inputs are included. You can add media afterward.'}</p>{props.projects.error&&<p role="alert">{props.projects.error}</p>}<div className="image-dialog-actions"><button type="button" className="button secondary" disabled={props.projects.busy} onClick={()=>setCreating(false)}>{de?'Abbrechen':'Cancel'}</button><button className="button primary" disabled={props.projects.busy||!name.trim()}>{de?'Projekt erstellen':'Create project'}</button></div></form></dialog>:null}</>;
}
