import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {listen} from '@tauri-apps/api/event';
import type {useProject} from './useProject';
import type {Settings} from './types';
import {menuContext} from './menu-context';
import {shortcutFor} from './shortcuts';
type Props={projects:ReturnType<typeof useProject>;settings:Settings;locked:boolean;workspaceRecovery:boolean;onSettings:()=>void;onHelp:()=>void;onAbout:()=>void;onUpdates:()=>void;onZoom:(scale:number)=>void;onError:(e:unknown)=>void};
export default function AppMenu(props:Props){
 const latest=useRef(props);latest.current=props;const [tick,setTick]=useState(0),[creating,setCreating]=useState(false),[name,setName]=useState('');const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(creating){setName('');dialog.current?.showModal();}},[creating]);
 useEffect(()=>{const change=()=>setTick(n=>n+1);window.addEventListener('menu-context',change);const observer=new MutationObserver(records=>{if(records.some(r=>r.type==='attributes'||[...r.addedNodes,...r.removedNodes].some(n=>n instanceof HTMLElement&&(n.matches('dialog,[aria-modal]')||n.querySelector('dialog,[aria-modal]')))))change();});observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['open','aria-modal']});return()=>{observer.disconnect();window.removeEventListener('menu-context',change);};},[]);
 function enabled(){const p=latest.current;const modal=!!document.querySelector('dialog[open],[aria-modal="true"]');const context=menuContext();const ids:string[]=[];
 if(!modal&&!p.locked){ids.push('settings','help','updates','about','exit');if(p.projects.ready&&!p.projects.busy){ids.push('projectOpen');if(p.projects.project)ids.push('projectClose');if(p.projects.project?.recovery)ids.push('projectRecover');else if(!p.workspaceRecovery)ids.push('projectNew','projectSave','projectSaveAs','projectAdd');p.projects.recent.forEach((r,i)=>{if(r.available)ids.push(`recent-${i}`);});}}
 if(!p.locked&&(!modal||document.querySelector('.image-editor[open]'))){ids.push('uiZoomIn','uiZoomOut','uiZoomReset');if(context)ids.push(...Object.keys(context.actions));}return ids;
 }
 async function action(id:string){if(!enabled().includes(id))return;const p=latest.current;const view=menuContext()?.actions[id as keyof NonNullable<ReturnType<typeof menuContext>>['actions']];if(view){view();return;}if(id.startsWith('recent-')){const r=p.projects.recent[Number(id.slice(7))];if(r)await p.projects.openPath(r.path);return;}
 switch(id){case'projectNew':setCreating(true);break;case'projectOpen':await p.projects.open();break;case'projectSave':await p.projects.save();break;case'projectSaveAs':await p.projects.save(true);break;case'projectAdd':await p.projects.add();break;case'projectRecover':await p.projects.recover();break;case'projectClose':await p.projects.close();break;case'exit':window.dispatchEvent(new Event('local-studio-exit'));break;case'settings':p.onSettings();break;case'help':p.onHelp();break;case'about':p.onAbout();break;case'updates':p.onUpdates();break;case'uiZoomIn':p.onZoom(p.settings.uiScale+.1);break;case'uiZoomOut':p.onZoom(p.settings.uiScale-.1);break;case'uiZoomReset':p.onZoom(1);break;}
 }
 const handler=useRef(action);handler.current=action;
 useEffect(()=>{let disposed=false;let off:(()=>void)|undefined;void listen<string>('app-menu',e=>void handler.current(e.payload).catch(latest.current.onError)).then(fn=>{if(disposed)fn();else off=fn;});const key=(e:KeyboardEvent)=>{if(e.defaultPrevented||e.repeat)return;const command=shortcutFor(e,latest.current.settings.shortcuts);if(command&&['projectNew','projectOpen','projectSaveAs','projectClose'].includes(command)){e.preventDefault();void handler.current(command).catch(latest.current.onError);}};window.addEventListener('keydown',key);return()=>{disposed=true;off?.();window.removeEventListener('keydown',key);};},[]);
 useEffect(()=>{void invoke('app_menu_update',{state:{de:props.settings.language==='de',enabled:enabled(),shortcuts:props.settings.shortcuts,recent:props.projects.recent.map(r=>r.name),theme:props.settings.theme}}).catch(props.onError);},[props.settings,props.locked,props.workspaceRecovery,props.projects.ready,props.projects.busy,props.projects.project?.id,props.projects.project?.recovery,props.projects.recent,tick,creating]);
 const de=props.settings.language==='de';return creating?<dialog ref={dialog} className="image-exit-dialog" aria-label={de?'Neues Projekt':'New project'} onCancel={()=>setCreating(false)}><h2>{de?'Neues Projekt':'New project'}</h2><form onSubmit={e=>{e.preventDefault();if(name.trim())void props.projects.create(name.trim()).then(ok=>{if(ok)setCreating(false);});}}><label>{de?'Projektname':'Project name'}<input autoFocus maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><p>{de?'Aktuelle Studio-Eingaben werden übernommen. Medien können anschließend hinzugefügt werden.':'Current Studio inputs are included. You can add media afterward.'}</p>{props.projects.error&&<p role="alert">{props.projects.error}</p>}<div className="image-dialog-actions"><button type="button" className="button secondary" disabled={props.projects.busy} onClick={()=>setCreating(false)}>{de?'Abbrechen':'Cancel'}</button><button className="button primary" disabled={props.projects.busy||!name.trim()}>{de?'Projekt erstellen':'Create project'}</button></div></form></dialog>:null;
}
