import {useEffect,useRef,useState} from 'react';
import {ai,aiError,aiPhase,type AiModel,type ChatState} from './ai-api';
import type {ImageRequest} from './image-api';
import AiModels from './AiModels';
import './ai.css';
export default function AssistantPage({de,onApply,onGallery}:{de:boolean;onApply:(request:ImageRequest)=>void;onGallery:()=>void}){
 const [state,setState]=useState<ChatState|null>(null),[models,setModels]=useState<AiModel[]>([]),[model,setModel]=useState(''),[text,setText]=useState(''),[tools,setTools]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[clear,setClear]=useState(false);const t=(a:string,b:string)=>de?a:b;
 useEffect(()=>{let live=true;const poll=()=>void ai.status().then(s=>{if(live)setState(s);}).catch(e=>{if(live)setError(aiError(e,de));});poll();const timer=setInterval(poll,500);return()=>{live=false;clearInterval(timer);};},[]);
 useEffect(()=>{if(state?.modelId)setModel(state.modelId);else if(!model&&models.length)setModel(models[0].id);},[models,model,state?.modelId]);
 const conversation=useRef<HTMLDivElement>(null);useEffect(()=>{if(conversation.current)conversation.current.scrollTop=conversation.current.scrollHeight;},[state?.messages.length]);
 async function run(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();setState(await ai.status());}catch(e){setError(aiError(e,de));}finally{setBusy(false);}}
 const active=state?.phase==='loading'||state?.phase==='running',loaded=state?.phase==='ready'||active;
 return <section className="assistant-page"><header className="section-heading"><div><h1>{t('Lokaler Assistent','Local assistant')}</h1><p>{t('Chat und Studio-Werkzeuge auf diesem PC. Keine Übertragung deiner Nachrichten oder Medien.','Chat and Studio tools on this PC. Your messages and media are not uploaded.')}</p></div></header>
 <AiModels kind="chat" de={de} onModels={setModels}/><div className="panel"><div className="creative-toolbar"><label>{t('Chatmodell','Chat model')}<select aria-label={t('Chatmodell','Chat model')} value={state?.modelId??model} disabled={!!loaded||busy} onChange={e=>setModel(e.target.value)}><option value="">{t('Modell auswählen','Select model')}</option>{models.map(m=><option key={m.id} value={m.id}>{m.name} · {(m.bytes/1e9).toFixed(2)} GB</option>)}</select></label><button className="button primary" disabled={!model||!!loaded||busy} onClick={()=>void run(()=>ai.load(model))}>{t('Modell laden','Load model')}</button><button className="button secondary" disabled={!loaded||busy} onClick={()=>void run(()=>ai.unload())}>{t('Entladen','Unload')}</button><span role="status">{aiPhase(state?.phase??'unloaded',de)}</span></div><p className="hub-hint">{t('CPU-Betrieb. Zum Modellwechsel zuerst entladen. Der Verlauf bleibt lokal erhalten; nur ein begrenzter letzter Ausschnitt wird als Kontext verwendet.','CPU inference. Unload before switching models. History stays local; only a bounded recent portion is used as context.')}</p></div>
 {(error||state?.error)&&<p role="alert" className="notice warning">{error||aiError(state?.error,de)}</p>}
 <div ref={conversation} className="ai-conversation" aria-label={t('Chatverlauf','Chat history')}>{state?.messages.map(m=><article key={m.id} className={`panel ai-message ${m.role}`}><strong>{m.role==='user'?t('Du','You'):t('Assistent','Assistant')}</strong><p className="ai-message-text">{m.text}</p>{m.tools.map((tool,i)=><details key={i}><summary>{t('Studio-Aktion','Studio action')}: {tool.name}</summary><pre>{JSON.stringify({arguments:tool.arguments,result:tool.result},null,2)}</pre>{tool.name==='search_gallery'&&<button className="button secondary" onClick={onGallery}>{t('Galerie öffnen','Open gallery')}</button>}</details>)}{m.proposal&&<div className="ai-proposal"><strong>{t('Bildauftrag vorbereitet','Image job prepared')}</strong><p>{m.proposal.width} × {m.proposal.height} · {m.proposal.steps} {t('Schritte','steps')} · {m.proposal.sampler}</p><p>{m.proposal.prompt}</p><button className="button primary" disabled={!!active} onClick={()=>onApply(m.proposal!)}>{t('Einstellungen ins Bild-Studio übernehmen','Apply settings to image Studio')}</button><small>{t('Öffnet das Formular; die Generierung startest du dort.','Opens the form; start generation there.')}</small></div>}</article>)}</div>
 <form className="panel ai-compose" onSubmit={e=>{e.preventDefault();if(!text.trim()||state?.phase!=='ready'||busy)return;void run(async()=>{await ai.send(text,de?'de':'en',tools);setText('');});}}><label>{t('Nachricht','Message')}<textarea aria-label={t('Nachricht','Message')} maxLength={8000} value={text} onChange={e=>setText(e.target.value)} placeholder={t('Erkläre meine Hardware oder bereite einen Bildauftrag vor …','Explain my hardware or prepare an image job …')}/></label><label className="ai-check"><input type="checkbox" checked={tools} disabled={!!active} onChange={e=>setTools(e.target.checked)}/>{t('Studio-Werkzeuge erlauben: Hardware, Leistungsmessungen, Präferenzen, lokale Modelle, Galerie-Metadaten und Auftragsvorbereitung','Allow Studio tools: hardware, performance measurements, preferences, local models, gallery metadata and job preparation')}</label><div className="creative-buttons"><button className="button primary" disabled={state?.phase!=='ready'||busy||!text.trim()} type="submit">{t('Senden','Send')}</button>{state?.phase==='running'&&<button type="button" className="button secondary" onClick={()=>void run(()=>ai.cancel())}>{t('Antwort abbrechen und entladen','Cancel reply and unload')}</button>}<button type="button" className="button secondary" disabled={!!active||!state?.messages.length} onClick={()=>setClear(true)}>{t('Chat leeren','Clear chat')}</button></div>{state?.elapsedMs? <small>{(state.elapsedMs/1000).toFixed(1)} s{state.tokens!==null?` · ${state.tokens} tokens`:''}</small>:null}</form>
 {clear&&<div className="modal-backdrop"><div className="setup-dialog" role="dialog" aria-modal="true" aria-label={t('Chat löschen?','Delete chat?')}><h2>{t('Chatverlauf löschen?','Delete chat history?')}</h2><p>{t('Der lokale Verlauf wird gelöscht. Modelle und Medien bleiben erhalten.','Deletes the local chat history. Models and media are kept.')}</p><div className="creative-buttons"><button className="button secondary" onClick={()=>setClear(false)}>{t('Abbrechen','Cancel')}</button><button className="button primary" onClick={()=>void run(async()=>{await ai.clear(true);setClear(false);})}>{t('Verlauf löschen','Delete history')}</button></div></div></div>}
 </section>;
}
