import {useEffect,useRef,useState} from 'react';
import CorrectionControls from './CorrectionControls';
import {editorApi,editorActivity,neutralCorrections,type EditOperation,type EditPreview} from './editor-state';
import {galleryError,type GalleryEntry} from './gallery-api';
import './image-editor.css';
export default function BatchCorrections({entries,rootId,de,onClose}:{entries:GalleryEntry[];rootId:string;de:boolean;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),cancel=useRef(false),gate=useRef(false);
 const [corrections,setCorrections]=useState({...neutralCorrections}),[format,setFormat]=useState<'png'|'jpeg'>('png'),[quality,setQuality]=useState(90),[busy,setBusy]=useState(false),[running,setRunning]=useState(false),[stopping,setStopping]=useState(false),[before,setBefore]=useState<EditPreview|null>(null),[after,setAfter]=useState<EditPreview|null>(null),[results,setResults]=useState<{name:string;path?:string;error?:string}[]>([]),[error,setError]=useState(''),[done,setDone]=useState(false);
 const t=(a:string,b:string)=>de?a:b;
 const query=(e:GalleryEntry)=>({rootId,target:{path:e.path,fileId:e.fileId!,version:e.thumbnailVersion}});
 const ops:EditOperation[]=[{type:'adjust',...corrections}];
 useEffect(()=>{dialog.current?.showModal();return()=>{cancel.current=true;dialog.current?.close();};},[]);
 function stop(){cancel.current=true;setStopping(true);}
 async function preview(){if(gate.current)return;gate.current=true;setBusy(true);setError('');const task=(async()=>{const original=await editorApi.preview(query(entries[0]),[]);const edited=await editorApi.preview(query(entries[0]),ops);setBefore(original);setAfter(edited);})();editorActivity.pending=task;try{await task;}catch(e){setError(galleryError(e,de));}finally{gate.current=false;setBusy(false);editorActivity.pending=null;}}
 async function start(){if(gate.current)return;gate.current=true;cancel.current=false;setBusy(true);setRunning(true);setStopping(false);setDone(false);setResults([]);setError('');editorActivity.cancelBatch=stop;
  const task=(async()=>{for(const entry of entries){if(cancel.current)break;try{const path=await editorApi.export(query(entry),ops,format,quality);setResults(r=>[...r,{name:entry.name,path}]);}catch(e){setResults(r=>[...r,{name:entry.name,error:galleryError(e,de)}]);}}})();editorActivity.pending=task;
  try{await task;}finally{editorActivity.pending=null;editorActivity.cancelBatch=null;gate.current=false;setBusy(false);setRunning(false);setDone(true);}
 }
 return <dialog ref={dialog} className="image-editor batch-corrections" aria-label={t('Bilder korrigieren','Batch image corrections')} onCancel={e=>{e.preventDefault();if(running)stop();else if(!busy)onClose();}}><header className="editor-heading"><div><h2>{t('Bilder korrigieren','Batch image corrections')}</h2><p>{entries.length} {t('ausgewählte Bilder · neue Varianten, Originale bleiben erhalten','selected images · new variants, originals retained')}</p></div><button className="button secondary" disabled={busy} onClick={onClose}>{t('Schließen','Close')}</button></header>
 <div className="editor-layout"><div><div className="editor-comparison batch-preview">{before&&after?<><figure><figcaption>{t('Original','Original')} · {entries[0].name}</figcaption><img src={before.dataUrl} alt={t('Stapel-Originalvorschau','Batch original preview')}/></figure><figure><figcaption>{t('Bearbeitet','Edited')}</figcaption><img src={after.dataUrl} alt={t('Stapel-Bearbeitungsvorschau','Batch edited preview')}/></figure></>:<p>{t('Vorschau für das erste ausgewählte Bild laden.','Load a preview for the first selected image.')}</p>}</div><p>{t('Ein Bild nach dem anderen, mit denselben Korrekturen. Fehler einzelner Dateien stoppen die übrigen nicht. Abbruch stoppt nach dem aktuellen Bild; fertige Varianten bleiben erhalten.','One image at a time using the same corrections. Individual failures do not stop the others. Cancellation stops after the current image; completed variants remain.')}</p><progress max={entries.length} value={results.length}/><p role="status">{results.length} / {entries.length} · {running?t('Verarbeitung läuft','Processing'):done?t('Abgeschlossen','Finished'):t('Bereit','Ready')}{stopping&&` · ${t('Abbruch angefordert','Cancellation requested')}`}</p><ul className="batch-results">{results.map((r,i)=><li key={i} className={r.error?'inline-warning':''}>{r.name}: {r.error??r.path}</li>)}</ul>{done&&<p>{results.filter(r=>r.path).length} {t('Varianten erstellt','variants created')} · {results.filter(r=>r.error).length} {t('Fehler','errors')} · {entries.length-results.length} {t('nicht verarbeitet','not processed')}</p>}</div><aside className="editor-tools"><CorrectionControls value={corrections} onChange={c=>{setCorrections(c);setBefore(null);setAfter(null);}} de={de} disabled={busy}/><button className="button secondary" disabled={busy} onClick={()=>void preview()}>{t('Vorschau laden','Load preview')}</button><fieldset disabled={busy}><label>Format<select aria-label="Batch format" value={format} onChange={e=>setFormat(e.target.value as 'png'|'jpeg')}><option value="png">PNG · Alpha</option><option value="jpeg">JPEG</option></select></label>{format==='jpeg'&&<label>{t('JPEG-Qualität','JPEG quality')}<input type="range" min={1} max={100} value={quality} onChange={e=>setQuality(Number(e.target.value))}/>{quality}</label>}<p>{format==='jpeg'?t('Transparenz wird weiß hinterlegt.','Transparency is flattened on white.'):t('Transparenz bleibt erhalten.','Transparency is retained.')}</p><button className="button primary" disabled={Object.values(corrections).every(v=>v===0)} onClick={()=>void start()}>{t('Varianten erstellen','Create variants')}</button></fieldset>{running&&<button className="button secondary" disabled={stopping} onClick={stop}>{t('Nach aktuellem Bild abbrechen','Cancel after current image')}</button>}{error&&<p role="alert" className="notice warning">{error}</p>}</aside></div></dialog>;
}
