import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {ArrowLeft,ArrowRight,ExternalLink,Home,ImageDown,LoaderCircle,RefreshCw,Tags} from 'lucide-react';
type State={url:string;title:string;loading:boolean;notice:string|null;imageId:number|null;postId:number|null;visible:boolean};
type Bounds={x:number;y:number;width:number;height:number};
let queue:Promise<unknown>=Promise.resolve();
const mutate=<T,>(work:()=>Promise<T>)=>{const result=queue.then(work);queue=result.catch(()=>undefined);return result;};

export default function CivitaiBrowser({de,onImage,onPost,homeUrl='https://civitai.red/images'}:{de:boolean;onImage?:(url:string)=>void;onPost?:(url:string)=>void;homeUrl?:string}){
 const host=useRef<HTMLDivElement>(null),owner=useRef(crypto.randomUUID());const [state,setState]=useState<State|null>(null),[address,setAddress]=useState(homeUrl),[error,setError]=useState('');
 useEffect(()=>{let closed=false,mounted=false,initialized=false,frame=0,previous='';const id=owner.current;const layout=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(closed||!host.current)return;const r=host.current.getBoundingClientRect();const left=Math.max(0,r.left),top=Math.max(0,r.top),right=Math.min(window.innerWidth,r.right),bottom=Math.min(window.innerHeight,r.bottom);const width=right-left,height=bottom-top;if(width<32||height<32){if(mounted){mounted=false;previous='';void mutate(()=>invoke('civitai_browser_hide',{owner:id})).catch(e=>{if(!closed)setError(String(e));});}return;}const bounds:Bounds={x:left,y:top,width,height};const key=JSON.stringify(bounds);if(key===previous)return;previous=key;void mutate(async()=>{if(!mounted){const next=await invoke<State>('civitai_browser_mount',{owner:id,bounds});mounted=true;if(!initialized&&homeUrl!==next.url)await invoke('civitai_browser_action',{owner:id,action:{kind:'visit',url:homeUrl}});initialized=true;if(!closed){setState(next);setAddress(homeUrl===next.url?next.url:homeUrl);}}else await invoke('civitai_browser_layout',{owner:id,bounds});}).catch(e=>{previous='';if(!closed)setError(String(e));});});};const observer=new ResizeObserver(layout);if(host.current)observer.observe(host.current);window.addEventListener('resize',layout);window.addEventListener('scroll',layout,true);layout();let reading=false;const timer=setInterval(()=>{if(!mounted||reading)return;reading=true;void invoke<State>('civitai_browser_state').then(next=>{if(!closed){setState(next);setAddress(next.url);}}).catch(e=>{if(!closed)setError(String(e));}).finally(()=>reading=false);},700);return()=>{closed=true;cancelAnimationFrame(frame);clearInterval(timer);observer.disconnect();window.removeEventListener('resize',layout);window.removeEventListener('scroll',layout,true);void mutate(()=>invoke('civitai_browser_hide',{owner:id})).catch(()=>{});};},[homeUrl]);
 async function action(action:Record<string,unknown>){setError('');try{await mutate(()=>invoke('civitai_browser_action',{owner:owner.current,action}));}catch(e){setError(String(e));}}
 return <div className="civitai-browser"><div className="hf-browser-toolbar"><button type="button" className="icon-button" aria-label={de?'Zurück':'Back'} onClick={()=>void action({kind:'back'})}><ArrowLeft size={15}/></button><button type="button" className="icon-button" aria-label={de?'Vorwärts':'Forward'} onClick={()=>void action({kind:'forward'})}><ArrowRight size={15}/></button><button type="button" className="icon-button" aria-label={de?'Neu laden':'Reload'} onClick={()=>void action({kind:'reload'})}><RefreshCw size={15} className={state?.loading?'spin':''}/></button><button type="button" className="icon-button" aria-label="Home" onClick={()=>void action({kind:'visit',url:homeUrl})}><Home size={15}/></button><form onSubmit={e=>{e.preventDefault();void action({kind:'visit',url:address});}}><input value={address} onChange={e=>setAddress(e.target.value)} spellCheck={false}/><button className="button secondary">{de?'Öffnen':'Go'}</button></form><button type="button" className="icon-button" aria-label={de?'Extern öffnen':'Open externally'} onClick={()=>void action({kind:'openExternal'})}><ExternalLink size={15}/></button>{state?.imageId&&onImage&&<button type="button" className="button primary" onClick={()=>onImage(state.url)}><ImageDown size={15}/>{de?'Dieses Bild übernehmen':'Use this image'}</button>}{state?.postId&&onPost&&<button type="button" className="button primary" onClick={()=>onPost(state.url)}><Tags size={15}/>{de?'Tags übernehmen':'Use tags'}</button>}</div>{error&&<p className="notice warning">{error}</p>}<div ref={host} className="civitai-browser-surface">{!state&&<span><LoaderCircle size={16} className="spin"/>{de?'Browser wird geladen …':'Loading browser …'}</span>}</div></div>;
}
