import {useEffect,useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import {open} from '@tauri-apps/plugin-dialog';
import {Box,Download,FolderOpen,Play,RefreshCw,Square,X} from 'lucide-react';
import {comfyApi,comfyError,type ComfyStatus} from './comfy-api';

export default function ComfySettings({de,promptOnly=false}:{de:boolean;promptOnly?:boolean}){
 const [host]=useState(()=>document.createElement('div'));
 const [status,setStatus]=useState<ComfyStatus|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 async function refresh(){try{setStatus(await comfyApi.status());}catch(e){setError(comfyError(e,de));}}
 useEffect(()=>{void refresh();if(promptOnly){const timer=setInterval(()=>void refresh(),5000);return()=>clearInterval(timer);}},[promptOnly]);
 useLayoutEffect(()=>{if(promptOnly)return;const page=document.querySelector('.settings-page');if(!page)return;host.className='comfy-settings-host';const form=page.querySelector('form');if(form?.nextSibling)page.insertBefore(host,form.nextSibling);else page.appendChild(host);return()=>host.remove();},[promptOnly,host]);
 const prompt=promptOnly&&status&&!status.installed&&!status.dismissed;
 useEffect(()=>{if(prompt&&!dialog.current?.open)dialog.current?.showModal();else if(!prompt&&dialog.current?.open)dialog.current.close();},[prompt]);
 async function run(action:()=>Promise<ComfyStatus|void>){if(busy)return;setBusy(true);setError('');try{const next=await action();if(next)setStatus(next);else await refresh();}catch(e){setError(comfyError(e,de));}finally{setBusy(false);}}
 async function choose(){const path=await open({directory:true,multiple:false,title:de?'Portable ComfyUI auswählen':'Select portable ComfyUI'});if(typeof path==='string')await run(()=>comfyApi.setPath(path));}
 const controls:ReactNode=<><div className="comfy-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>void choose()}><FolderOpen size={16}/>{de?'Vorhandene Installation wählen':'Choose existing installation'}</button><button type="button" className="button secondary" disabled={busy} onClick={()=>void run(()=>comfyApi.download())}><Download size={16}/>{de?'Portable Version herunterladen':'Download portable version'}</button>{status?.installed&&<button type="button" className="button secondary" disabled={busy} onClick={()=>void run(()=>comfyApi.openUpdater())}><RefreshCw size={15}/>{de?'Update-Ordner öffnen':'Open update folder'}</button>}{status?.installed&&!status.running&&<button type="button" className="button primary" disabled={busy} onClick={()=>void run(()=>comfyApi.start())}><Play size={16}/>{de?'ComfyUI starten':'Start ComfyUI'}</button>}{status?.managed&&status.running&&<button type="button" className="button secondary" disabled={busy} onClick={()=>void run(()=>comfyApi.stop())}><Square size={15}/>{de?'ComfyUI beenden':'Stop ComfyUI'}</button>}</div>{error&&<p className="notice warning" role="alert">{error}</p>}</>;
 if(promptOnly)return <dialog ref={dialog} className="comfy-setup-dialog" onCancel={event=>{event.preventDefault();void run(()=>comfyApi.dismiss());}}><div className="section-heading"><h2><Box size={19}/> {de?'ComfyUI einrichten':'Set up ComfyUI'}</h2><button className="icon-button" aria-label={de?'Später':'Later'} onClick={()=>void run(()=>comfyApi.dismiss())}><X size={17}/></button></div><p>{de?'Local Studio kann die portable ComfyUI-Version als lokale Bildengine verwenden. Es wurde keine Installation erkannt.':'Local Studio can use portable ComfyUI as its local image engine. No installation was detected.'}</p><p className="hub-hint">{de?'Der Download stammt direkt vom offiziellen ComfyUI-GitHub-Release. Entpacke ihn anschließend und wähle den Ordner „ComfyUI_windows_portable“. Custom Nodes werden nicht automatisch installiert.':'The download comes directly from the official ComfyUI GitHub release. Extract it, then select the “ComfyUI_windows_portable” folder. Custom nodes are never installed automatically.'}</p>{controls}<button className="text-button" onClick={()=>void run(()=>comfyApi.dismiss())}>{de?'Später in den Einstellungen':'Set up later in Settings'}</button></dialog>;
 const panel=<section className="panel settings-section comfy-settings"><div className="settings-section-title"><Box size={20}/><div><h2>ComfyUI</h2><p>{de?'Lokale portable Engine für Bildgenerierung.':'Local portable engine for image generation.'}</p></div><button type="button" className="text-button" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={14}/>{de?'Prüfen':'Check'}</button></div><dl><div><dt>{de?'Installation':'Installation'}</dt><dd>{status?.path??(de?'Nicht eingerichtet':'Not configured')}</dd></div><div><dt>Status</dt><dd>{status?.running?(de?'Läuft lokal':'Running locally'):(de?'Beendet':'Stopped')} · {status?.endpoint??'127.0.0.1:8188'}</dd></div>{status?.version&&<div><dt>Version</dt><dd>{status.version}</dd></div>}</dl>{controls}<p className="hub-hint">{de?'Updates: Die portable Installation enthält ihren offiziellen Stable-Updater. Local Studio führt ihn vorerst nicht automatisch aus, damit Python-, PyTorch- und Custom-Node-Abhängigkeiten nicht ungeprüft verändert werden.':'Updates: the portable installation includes its official stable updater. Local Studio does not run it automatically yet, so Python, PyTorch and custom-node dependencies are not changed without validation.'}</p></section>;
 return createPortal(panel,host);
}
