import {useEffect,useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import {open} from '@tauri-apps/plugin-dialog';
import {Box,Download,FolderOpen,Play,RefreshCw,Search,Square,X} from 'lucide-react';
import {comfyApi,comfyError,type ComfyStatus,type ComfyVariant} from './comfy-api';

export default function ComfySettings({de,promptOnly=false}:{de:boolean;promptOnly?:boolean}){
 const [host]=useState(()=>document.createElement('div'));
 const [status,setStatus]=useState<ComfyStatus|null>(null);
 const [variant,setVariant]=useState<ComfyVariant>('nvidia');
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 async function refresh(){try{setStatus(await comfyApi.status());}catch(e){setError(comfyError(e,de));}}
 useEffect(()=>{void refresh();if(promptOnly){const timer=setInterval(()=>void refresh(),5000);return()=>clearInterval(timer);}},[promptOnly]);
 useEffect(()=>{if(!busy)return;const timer=setInterval(()=>void refresh(),750);return()=>clearInterval(timer);},[busy]);
 useLayoutEffect(()=>{if(promptOnly)return;const page=document.querySelector('.settings-page');if(!page)return;host.className='comfy-settings-host';const form=page.querySelector('form');if(form?.nextSibling)page.insertBefore(host,form.nextSibling);else page.appendChild(host);return()=>host.remove();},[promptOnly,host]);
 const prompt=promptOnly&&status&&!status.installed&&!status.dismissed;
 useEffect(()=>{if(prompt&&!dialog.current?.open)dialog.current?.showModal();else if(!prompt&&dialog.current?.open)dialog.current.close();},[prompt]);
 async function run(action:()=>Promise<ComfyStatus|void>){if(busy)return;setBusy(true);setError('');try{const next=await action();if(next)setStatus(next);else await refresh();}catch(e){setError(comfyError(e,de));}finally{setBusy(false);}}
 async function install(){setStatus(current=>current?{...current,install:{...current.install,phase:'resolving',variant,error:null}}:current);await run(()=>comfyApi.download(variant));}
 async function choose(){const path=await open({directory:true,multiple:false,title:de?'Portable ComfyUI auswählen':'Select portable ComfyUI'});if(typeof path==='string')await run(()=>comfyApi.setPath(path));}
 const installActive=!!status&&['resolving','downloading','verifying','installing'].includes(status.install.phase);
 const installPercent=status?.install.totalBytes?Math.min(100,Math.floor(status.install.receivedBytes/status.install.totalBytes*100)):0;
 const installLabel=status?.install.phase==='downloading'?(de?`Download ${installPercent} %`:`Download ${installPercent}%`):status?.install.phase==='verifying'?(de?'Download wird geprüft …':'Verifying download …'):status?.install.phase==='installing'?(de?'ComfyUI wird installiert …':'Installing ComfyUI …'):(de?'Release wird geprüft …':'Checking release …');
 const controls:ReactNode=<>
  {!status?.installed&&<label className="field comfy-package"><span>{de?'Paket für deine Grafikkarte':'Package for your graphics card'}</span><select value={variant} disabled={busy} onChange={event=>setVariant(event.target.value as ComfyVariant)}><option value="nvidia">NVIDIA · RTX 20/30/40/50</option><option value="nvidia_legacy">NVIDIA · GTX/älter (CUDA 12.6)</option><option value="amd">AMD Radeon</option><option value="intel">Intel Arc</option></select></label>}
  <div className="comfy-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>void run(()=>comfyApi.detect())}><Search size={16}/>{de?'Nach Installation suchen':'Search for installation'}</button><button type="button" className="button secondary" disabled={busy} onClick={()=>void choose()}><FolderOpen size={16}/>{de?'Ordner selbst wählen':'Choose folder manually'}</button>{!status?.installed&&<button type="button" className={`button primary comfy-install-button${installActive?' is-progress':''}${installActive&&!status.install.totalBytes?' is-indeterminate':''}`} disabled={busy} onClick={()=>void install()} aria-live="polite">{installActive&&<span className="comfy-install-fill" style={{width:`${status.install.phase==='downloading'?installPercent:status.install.phase==='resolving'?12:100}%`}}/>}<span className="comfy-install-label"><Download size={16}/>{installActive?installLabel:(de?'Herunterladen und installieren':'Download and install')}</span></button>}{status?.installed&&<button type="button" className="button secondary" disabled={busy} onClick={()=>void run(()=>comfyApi.openUpdater())}><RefreshCw size={15}/>{de?'Update-Ordner öffnen':'Open update folder'}</button>}{status?.installed&&!status.running&&<button type="button" className="button primary" disabled={busy} onClick={()=>void run(()=>comfyApi.start())}><Play size={16}/>{de?'ComfyUI starten':'Start ComfyUI'}</button>}{status?.managed&&status.running&&<button type="button" className="button secondary" disabled={busy} onClick={()=>void run(()=>comfyApi.stop())}><Square size={15}/>{de?'ComfyUI beenden':'Stop ComfyUI'}</button>}</div>
  {error&&<p className="notice warning" role="alert">{error}</p>}
 </>;
 if(promptOnly)return <dialog ref={dialog} className="comfy-setup-dialog" onCancel={event=>{event.preventDefault();void run(()=>comfyApi.dismiss());}}><div className="section-heading"><h2><Box size={19}/> {de?'ComfyUI einrichten':'Set up ComfyUI'}</h2><button className="icon-button" aria-label={de?'Später':'Later'} onClick={()=>void run(()=>comfyApi.dismiss())}><X size={17}/></button></div><p>{de?'Local Studio verwendet die portable ComfyUI-Version als lokale Bildengine. Es wurde keine Installation erkannt.':'Local Studio uses portable ComfyUI as its local image engine. No installation was detected.'}</p><p className="hub-hint">{de?'Local Studio lädt das passende Paket direkt vom offiziellen ComfyUI-GitHub-Release, prüft seine SHA-256-Prüfsumme und richtet es im lokalen Datenordner ein. Custom Nodes werden nicht installiert.':'Local Studio downloads the matching package directly from the official ComfyUI GitHub release, verifies its SHA-256 checksum and installs it in the local data folder. Custom nodes are not installed.'}</p>{controls}<button className="text-button" disabled={busy} onClick={()=>void run(()=>comfyApi.dismiss())}>{de?'Später in den Einstellungen':'Set up later in Settings'}</button></dialog>;
 const panel=<section className="panel settings-section comfy-settings"><div className="settings-section-title"><Box size={20}/><div><h2>ComfyUI</h2><p>{de?'Lokale portable Engine für Bildgenerierung.':'Local portable engine for image generation.'}</p></div><button type="button" className="text-button" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={14}/>{de?'Prüfen':'Check'}</button></div><dl><div><dt>{de?'Installation':'Installation'}</dt><dd>{status?.path??(de?'Nicht eingerichtet':'Not configured')}</dd></div><div><dt>Status</dt><dd>{status?.running?(de?'Läuft lokal':'Running locally'):(de?'Beendet':'Stopped')} · {status?.endpoint??'127.0.0.1:8188'}</dd></div>{status?.version&&<div><dt>Version</dt><dd>{status.version}</dd></div>}</dl>{controls}<p className="hub-hint">{de?'Updates: Das Update-Center kann den offiziellen stabilen ComfyUI-Core-Updater auf deinen Befehl direkt ausführen. Er darf erforderliche Kernabhängigkeiten anpassen; Custom Nodes bleiben unberührt. „Update-Ordner öffnen“ dient als manueller Ausweichweg.':'Updates: the Update Center can run the official stable ComfyUI core updater directly when you request it. It may adjust required core dependencies; custom nodes remain untouched. “Open update folder” is the manual fallback.'}</p></section>;
 return createPortal(panel,host);
}
