import {invoke} from '@tauri-apps/api/core';
import type {EditOperation} from './editor-state';
import type {StudioProject} from './project-api';
export interface Stroke {shape:'brush'|'rectangle'|'ellipse';restore:boolean;size:number;hardness:number;opacity:number;points:[number,number][]}
export interface Mask {base:boolean;inverted:boolean;strokes:Stroke[]}
export interface Layer {id:string;name:string;assetId:string;x:number;y:number;width:number;height:number;rotation:number;opacity:number;blend:'normal'|'multiply'|'screen'|'overlay';visible:boolean;locked:boolean;group:string|null;operations:EditOperation[];mask:Mask|null}
export interface CanvasDocument {width:number;height:number;background:string|null;layers:Layer[]}
export interface Keyframe {time:number;x:number;y:number;scale:number;rotation:number;opacity:number;volume:number}
export interface Track {id:string;name:string;audio:boolean;muted:boolean;locked:boolean}
export interface Clip {id:string;assetId:string;trackId:string;name:string;start:number;sourceIn:number;sourceOut:number;speed:number;fadeIn:number;fadeOut:number;blur:number;brightness:number;contrast:number;saturation:number;keyframes:Keyframe[]}
export interface Caption {id:string;start:number;end:number;text:string;size:number;color:string;y:number}
export interface Timeline {width:number;height:number;fps:number;background:string;tracks:Track[];clips:Clip[];captions:Caption[]}
export interface Creative {revision:number;image:CanvasDocument|null;video:Timeline|null}
export interface Probe {duration:number;width:number;height:number;audio:boolean;video:boolean}
export interface VideoJob {id:string;name:string;status:'running'|'completed'|'cancelled'|'failed'|'interrupted';progress:number;error:string|null;output:string|null;preview:boolean;projectId:string;timeline:Timeline;format:'mp4'|'webm';bitrate:number}
export interface CanvasPreview {dataUrl:string;width:number;height:number;bytes:number}
export const uid=()=>crypto.randomUUID();
export const defaultPose=():Keyframe=>({time:0,x:0,y:0,scale:1,rotation:0,opacity:1,volume:1});
export const newCanvas=():CanvasDocument=>({width:1280,height:720,background:null,layers:[]});
export const newTimeline=():Timeline=>({width:1280,height:720,fps:30,background:'#000000',tracks:[{id:uid(),name:'Video 1',audio:false,muted:false,locked:false},{id:uid(),name:'Audio 1',audio:true,muted:false,locked:false}],clips:[],captions:[]});
export const length=(c:Clip)=>(c.sourceOut-c.sourceIn)/c.speed;
export const timelineEnd=(t:Timeline)=>Math.max(0,...t.clips.map(c=>c.start+length(c)),...t.captions.map(c=>c.end));
export function poseAt(clip:Clip,time:number):Keyframe{const t=Math.max(0,Math.min(length(clip),time)),keys=clip.keyframes;let a=keys[0];for(const b of keys.slice(1)){if(t<=b.time){const f=(t-a.time)/(b.time-a.time);return Object.fromEntries(Object.keys(a).map(k=>[k,k==='time'?t:a[k as keyof Keyframe]+(b[k as keyof Keyframe]-a[k as keyof Keyframe])*f])) as unknown as Keyframe;}a=b;}return {...a,time:t};}
export function splitClip(clip:Clip,at:number):[Clip,Clip]|null{const t=at-clip.start,d=length(clip);if(t<.04||t>d-.04)return null;const split=poseAt(clip,t);const left={...clip,sourceOut:clip.sourceIn+t*clip.speed,fadeIn:Math.min(clip.fadeIn,t/2),fadeOut:0,keyframes:[...clip.keyframes.filter(k=>k.time<t),{...split,time:t}]};const right={...clip,id:uid(),start:at,sourceIn:left.sourceOut,fadeIn:0,fadeOut:Math.min(clip.fadeOut,(d-t)/2),keyframes:[{...split,time:0},...clip.keyframes.filter(k=>k.time>t).map(k=>({...k,time:k.time-t}))]};return [left,right];}
export function parseSrt(text:string):Caption[]{const time=(s:string)=>{const m=/^(\d{2,}):(\d{2}):(\d{2})[,.](\d{3})$/.exec(s);if(!m||+m[2]>59||+m[3]>59)throw Error('Invalid SRT time');return +m[1]*3600 + +m[2]*60 + +m[3] + +m[4]/1000;};const blocks=text.replace(/^\uFEFF/,'').replaceAll('\r','').trim().split(/\n\s*\n/);if(blocks.length>500)throw Error('Maximum 500 captions');return blocks.filter(Boolean).map(b=>{const lines=b.split('\n');if(/^\d+$/.test(lines[0]))lines.shift();const timing=lines.shift()!.split(/\s*-->\s*/);if(timing.length!==2)throw Error('Invalid SRT');const start=time(timing[0]),end=time(timing[1]),content=lines.join('\n');if(end<=start||end>3600||content.length>4000||!content)throw Error('Invalid SRT range');return {id:uid(),start,end,text:content,size:42,color:'#ffffff',y:.9};});}
export function srtText(captions:Caption[]):string{const time=(s:number)=>{const ms=Math.round(s*1000);return `${Math.floor(ms/3600000).toString().padStart(2,'0')}:${Math.floor(ms/60000)%60}`.replace(/:(\d)$/ ,':0$1')+`:${(Math.floor(ms/1000)%60).toString().padStart(2,'0')},${(ms%1000).toString().padStart(3,'0')}`;};return [...captions].sort((a,b)=>a.start-b.start).map((c,i)=>`${i+1}\n${time(c.start)} --> ${time(c.end)}\n${c.text}\n`).join('\n');}
export const creativeApi={save:(id:string,expected:number,creative:Creative)=>invoke<StudioProject>('project_creative_save',{id,expected,creative}),preview:(id:string,document:CanvasDocument,format='png',quality=90,exportSize:number[]|null=null,maskLayer:string|null=null)=>invoke<CanvasPreview>('canvas_preview',{id,document,format,quality,exportSize,maskLayer}),exportImage:(id:string,document:CanvasDocument,format:string,quality:number,width:number,height:number)=>invoke<string>('canvas_export',{id,document,format,quality,width,height}),probe:(id:string,assetId:string)=>invoke<Probe>('video_probe',{id,assetId}),start:(id:string,timeline:Timeline,format:string,bitrate:number,preview:boolean)=>invoke<VideoJob>('video_start',{id,timeline,format,bitrate,preview}),jobs:()=>invoke<VideoJob[]>('video_jobs'),cancel:(id:string)=>invoke<void>('video_cancel',{id})};
export function creativeError(e:unknown,de:boolean):string{const code=String(e);const map:Record<string,[string,string]>={creative_parameters:['Ungültige Bearbeitungswerte.','Invalid editing values.'],creative_limit:['Die Bearbeitung überschreitet die unterstützten Größen oder Arbeitsschritte.','The edit exceeds supported dimensions or operation limits.'],creative_source:['Eine benötigte Projektquelle fehlt.','A required project source is missing.'],creative_in_use:['Dieses Medium wird noch von Ebenen oder Clips verwendet. Entferne zuerst diese Verweise.','This media is used by layers or clips. Remove those references first.'],creative_profile:['Dieser Ebenenpfad benötigt Bilder ohne eingebettetes ICC-Profil. Die Quelle bleibt unverändert.','Layers currently require images without embedded ICC profiles. The source remains unchanged.'],video_no_audio:['Dieses Medium enthält keine Audiospur.','This media contains no audio stream.'],video_runtime:['Video-Runtime fehlt oder wurde verändert. Programmdateien vollständig aktualisieren.','Video runtime missing or changed. Update all program files.'],video_range:['Der Ausschnitt reicht über das Quellmedium hinaus.','The cut extends beyond the source media.'],video_encode:['Video konnte nicht gerendert werden. Details stehen im lokalen render.log des Auftrags.','Video rendering failed. See the local job render.log for details.'],video_decode:['Dieses Medium kann nicht gelesen werden.','This media cannot be decoded.'],video_busy:['Es läuft bereits ein Videoauftrag.','A video render is already running.'],video_cancelled:['Videoauftrag abgebrochen.','Video render cancelled.'],video_interrupted:['Videoauftrag wurde unterbrochen; erneut starten.','Video render interrupted; start it again.'],video_timeout:['Zeitlimit der Videoverarbeitung erreicht.','Video processing timed out.']};return map[code]?.[de?0:1]??code;}
