import { useEffect,useRef,useState,type PointerEvent } from 'react';
import { galleryApi,galleryError,type GalleryDetail,type GalleryEntry } from './gallery-api';
import { clampView,initialView,wipePosition,type CompareView } from './gallery-compare-view';
import './gallery-compare.css';
import { shortcutFor, type Shortcuts } from './shortcuts';

export default function GalleryCompare({shortcuts,entries,rootId,de,onClose}:{shortcuts:Shortcuts;entries:GalleryEntry[];rootId:string;de:boolean;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [details,setDetails]=useState<GalleryDetail[]|null>(null);const [error,setError]=useState('');const [imageErrors,setImageErrors]=useState<string[]>([]);const [loaded,setLoaded]=useState<string[]>([]);
 const [mode,setMode]=useState<'side'|'wipe'>('side');const [swapped,setSwapped]=useState(false);const [split,setSplit]=useState(50);const [view,setView]=useState<CompareView>(initialView);const [tick,setTick]=useState(0);
 const drag=useRef<{id:number;startX:number;startY:number;view:CompareView;width:number;height:number}|null>(null);const divider=useRef<number|null>(null);
 useEffect(()=>{const el=dialog.current;el?.showModal();return()=>el?.close();},[]);
 useEffect(()=>{let live=true;setDetails(null);setError('');setImageErrors([]);setLoaded([]);void galleryApi.compare({rootId,targets:entries.map(e=>({path:e.path,fileId:e.fileId!,version:e.thumbnailVersion}))}).then(data=>{if(live)setDetails(data);}).catch(e=>{if(live)setError(galleryError(e,de));});return()=>{live=false;};},[rootId,entries,de,tick]);
 const order=swapped?[1,0]:[0,1];const transform=`translate(${view.x*100}%, ${view.y*100}%) scale(${view.zoom})`;
 function startPan(e:PointerEvent<HTMLDivElement>){if(e.button!==0||view.zoom===1)return;const rect=e.currentTarget.getBoundingClientRect();drag.current={id:e.pointerId,startX:e.clientX,startY:e.clientY,view,width:rect.width,height:rect.height};e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault();}
 function pan(e:PointerEvent<HTMLDivElement>){const d=drag.current;if(!d||d.id!==e.pointerId)return;setView(clampView({...d.view,x:d.view.x+(e.clientX-d.startX)/d.width,y:d.view.y+(e.clientY-d.startY)/d.height}));}
 function moveDivider(e:PointerEvent<HTMLDivElement>){if(divider.current!==e.pointerId)return;const rect=e.currentTarget.parentElement!.getBoundingClientRect();setSplit(wipePosition(e.clientX,rect.left,rect.width));}
 function image(index:number){const detail=details?.[index];if(!detail)return null;return <div className="compare-transform" style={{transform}}><img key={detail.url+':'+tick} src={detail.url} alt={`${de?'Vergleichsbild':'Comparison image'} ${index===0?'A':'B'}`} draggable={false} onLoad={()=>setLoaded(old=>old.includes(detail.url)?old:[...old,detail.url])} onError={()=>setImageErrors(old=>old.includes(detail.url)?old:[...old,detail.url])}/></div>;}
 const failed=imageErrors.length>0;const ready=details&&loaded.length===2&&!failed;
 const metadata=(index:number)=>{const e=entries[index],d=details?.[index];return <div className="compare-info"><strong>{index===0?'A':'B'} · {e.name}</strong><small>{e.path}</small>{d?.dimensions&&<small>{d.dimensions.join(' × ')} px · {(e.bytes/1024/1024).toLocaleString(de?'de':'en',{maximumFractionDigits:2})} MiB</small>}{d?.origin&&<small>{d.origin.modelName} · Seed {d.request?.seed}</small>}</div>;};
 return <dialog ref={dialog} className="gallery-compare" aria-label={de?'Bilder vergleichen':'Compare images'} onCancel={e=>{e.preventDefault();onClose();}}>
   <header className="compare-heading"><div><h2>{de?'Bilder vergleichen':'Compare images'}</h2><p className="hub-hint">{de?'Ansichtsvergleich der ausgewählten Dateien. Originale bleiben unverändert.':'Visual comparison of the selected files. Originals remain unchanged.'}</p></div><button className="button secondary" autoFocus onClick={onClose}>{de?'Vergleich schließen':'Close comparison'}</button></header>
   <div className="gallery-actions compare-controls"><button className="button secondary" aria-pressed={mode==='side'} onClick={()=>setMode('side')}>{de?'Nebeneinander':'Side by side'}</button><button className="button secondary" aria-pressed={mode==='wipe'} onClick={()=>setMode('wipe')}>{de?'Schieberegler':'Wipe'}</button><button className="button secondary" disabled={!ready} onClick={()=>setSwapped(v=>!v)}>{de?'A/B tauschen':'Swap A/B'}</button><label>{de?'Gemeinsamer Zoom':'Linked zoom'} <input type="range" aria-label={de?'Vergleichszoom':'Comparison zoom'} min={1} max={8} step={0.25} value={view.zoom} disabled={!ready} onChange={e=>setView(v=>clampView({...v,zoom:Number(e.target.value)}))}/><span>{Math.round(view.zoom*100)}%</span></label><button className="text-button" disabled={!ready} onClick={()=>setView(initialView)}>{de?'Ansicht zurücksetzen':'Reset view'}</button></div>
   {error&&<p className="notice warning" role="alert">{error}</p>}
   {!error&&!ready&&!failed&&<p className="hub-hint" role="status">{de?'Zwei Originalbilder werden geladen …':'Loading two original images …'}</p>}
   {failed&&<p className="notice warning" role="alert">{de?'Ein Bild konnte nicht geladen werden oder hat sich seit der Auswahl geändert. Vergleich schließen, Galerie aktualisieren und erneut auswählen.':'An image could not load or has changed since selection. Close the comparison, refresh the gallery and select again.'}</p>}
   {error&&<button className="button secondary" onClick={()=>setTick(n=>n+1)}>{de?'Erneut prüfen':'Retry check'}</button>}
   {details&&<><div className="compare-metadata">{order.map(i=><div key={i}>{metadata(i)}</div>)}</div><div className={`compare-stages compare-${mode}`}>
     {(mode==='side'?order:[order[1]]).map((index,pane)=><div key={pane} className="compare-stage" data-pane={pane} tabIndex={0} aria-label={de?`Bildbereich ${pane+1}`:`Image viewport ${pane+1}`} style={{cursor:view.zoom>1?'grab':'default'}} onPointerDown={startPan} onPointerMove={pan} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onLostPointerCapture={()=>{drag.current=null;}} onKeyDown={e=>{if(e.target!==e.currentTarget)return;const command=shortcutFor(e.nativeEvent,shortcuts);if(command==='imageReset'||command==='imageFit'){e.preventDefault();setView(initialView);return;}if(e.ctrlKey||e.metaKey||e.altKey)return;const delta:{[key:string]:[number,number]}={ArrowLeft:[.1,0],ArrowRight:[-.1,0],ArrowUp:[0,.1],ArrowDown:[0,-.1]};if(delta[e.key]){e.preventDefault();setView(v=>clampView({...v,x:v.x+delta[e.key][0],y:v.y+delta[e.key][1]}));}else if(e.key==='+'||e.key==='-'){e.preventDefault();setView(v=>clampView({...v,zoom:v.zoom+(e.key==='+'?.25:-.25)}));}}}>
       {image(index)}
       {mode==='wipe'&&<><div className="compare-cut" style={{clipPath:`inset(0 ${100-split}% 0 0)`}}>{image(order[0])}</div><div className="compare-divider" role="slider" tabIndex={0} aria-label={de?'Trennlinie':'Wipe divider'} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(split)} style={{left:`${split}%`}} onPointerDown={e=>{e.stopPropagation();e.preventDefault();divider.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={moveDivider} onPointerUp={()=>{divider.current=null;}} onPointerCancel={()=>{divider.current=null;}} onLostPointerCapture={()=>{divider.current=null;}} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();e.stopPropagation();setSplit(v=>e.key==='Home'?0:e.key==='End'?100:Math.max(0,Math.min(100,v+(e.key==='ArrowLeft'?-1:1))));}}}><span>↔</span></div></>}
       <span className="compare-badge">{mode==='side'?(index===0?'A':'B'):`${order[0]===0?'A':'B'} | ${order[1]===0?'A':'B'}`}</span>
     </div>)}
   </div>{mode==='wipe'&&<label className="compare-wipe-control">{de?'Bildanteil links':'Left image portion'} <input type="range" aria-label={de?'Vergleichsregler':'Wipe position'} min={0} max={100} value={split} onChange={e=>setSplit(Number(e.target.value))}/><span>{Math.round(split)}%</span></label>}
   <p className="hub-hint">{de?'Ziehen verschiebt bei Zoom beide Bilder gemeinsam. Pfeiltasten im Bildbereich verschieben den Ausschnitt; +/− zoomt. Bildkürzel gelten aus den Einstellungen. Unterschiedliche Seitenverhältnisse werden unverzerrt eingepasst; keine automatische Pixel-Ausrichtung.':'Drag while zoomed to pan both images together. Arrow keys in a viewport pan; +/− zoom. Image shortcuts follow your settings. Different aspect ratios are fitted without distortion; there is no automatic pixel alignment.'}</p></>}
 </dialog>;
}
