import { useEffect,useRef,useState } from 'react';
import { flushSync } from 'react-dom';
import { galleryApi,galleryError,type GalleryDetail,type TrashItem,type TrashList } from './gallery-api';
import GalleryDialog from './GalleryDialog';
import { formatBytes } from './helpers';
export default function GalleryTrash({de,onBack}:{de:boolean;onBack:()=>void}){
 const [previewError,setPreviewError]=useState('');
 const [data,setData]=useState<TrashList|null>(null);const [offset,setOffset]=useState(0);const [tick,setTick]=useState(0);const [chosen,setChosen]=useState<string[]>([]);const [detail,setDetail]=useState<GalleryDetail|null>(null);const [previewName,setPreviewName]=useState('');const [error,setError]=useState('');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [confirm,setConfirm]=useState<{ids:string[];rootId:string}|null>(null);const running=useRef(false);const generation=useRef(0);const alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;};},[]);
 useEffect(()=>{let live=true;void galleryApi.trashList(offset).then(d=>{if(live){setData(d);setChosen([]);if(offset>=d.total&&offset)setOffset(0);}}).catch(e=>{if(live)setError(galleryError(e,de));});return()=>{live=false;};},[offset,tick,de]);
 async function preview(item:TrashItem){const id=++generation.current;setPreviewError('');setDetail(null);setError('');try{const d=await galleryApi.trashDetail(item.id);if(alive.current&&id===generation.current){setDetail(d);setPreviewName(item.originalPath);}}catch(e){if(alive.current&&id===generation.current)setError(galleryError(e,de));}}
 async function prepareEmpty(){
   if(!data||running.current)return;running.current=true;setBusy(true);setError('');
   try{const ids=new Set<string>();for(let pos=0;pos<data.total;pos+=50){const page=await galleryApi.trashList(pos);if(page.rootId!==data.rootId||page.total!==data.total)throw new Error('gallery_changed');for(const item of page.entries)ids.add(item.id);if(ids.size>20000)throw new Error('gallery_query');}if(ids.size!==data.total)throw new Error('gallery_changed');setConfirm({ids:[...ids],rootId:data.rootId});}catch(e){setError(galleryError(e,de));}finally{running.current=false;setBusy(false);}
 }
 async function apply(action:'restore'|'purge',ids:string[],rootId:string){
   if(running.current||!ids.length)return;running.current=true;setBusy(true);setError('');setNote('');generation.current++;flushSync(()=>{setDetail(null);setConfirm(null);});let completed=0;
   try{for(let i=0;i<ids.length;i+=50){const report=await galleryApi.trashAction({rootId,ids:ids.slice(i,i+50),action,confirmed:action==='purge'});completed+=report.completed.length;if(report.errors.length)throw new Error(report.errors.join('\n'));}if(alive.current)setNote(de?`${completed} Medien ${action==='purge'?'endgültig gelöscht':'wiederhergestellt'}.`:`${completed} media files ${action==='purge'?'permanently deleted':'restored'}.`);}
   catch(e){if(alive.current){setError(galleryError(e,de));setNote(de?`${completed} von ${ids.length} Schritten abgeschlossen. Vorgang angehalten; bitte die Liste prüfen.`:`Completed ${completed} of ${ids.length} steps. Operation stopped; check the list.`);}}
   finally{running.current=false;if(alive.current){setChosen([]);setBusy(false);setTick(n=>n+1);}}
 }
 return <div className="page gallery-page"><header className="page-heading"><div><div className="eyebrow">LOCAL STUDIO</div><h1>{de?'Papierkorb':'Trash'}</h1><p>{de?'Gelöschte Medien bleiben hier, bis du sie endgültig löschst. Keine automatische Leerung.':'Deleted media stay here until you permanently delete them. No automatic emptying.'}</p></div></header>
 <div className="gallery-actions"><button className="button secondary" disabled={busy} onClick={onBack}>{de?'Zurück zur Galerie':'Back to gallery'}</button><button className="text-button" disabled={busy} onClick={()=>{setError('');setTick(n=>n+1);}}>{de?'Aktualisieren':'Refresh trash'}</button><button className="button secondary" disabled={busy||!data?.total} onClick={()=>void prepareEmpty()}>{de?'Papierkorb leeren …':'Empty trash …'}</button></div>
 {error&&<p className="notice warning" role="alert">{error}</p>}{note&&<p className="notice" role="status">{note}</p>}{busy&&<p role="status">{de?'Dateiaktion läuft …':'File operation in progress …'}</p>}
 <section className="panel gallery-trash"><h2>{de?'Medien im Papierkorb':'Media in trash'} ({data?.total??'…'})</h2><div className="gallery-actions"><button className="text-button" disabled={busy||!data?.entries.length} onClick={()=>setChosen(data!.entries.map(i=>i.id))}>{de?'Seite auswählen':'Select page'}</button><button className="text-button" disabled={busy||!chosen.length} onClick={()=>setChosen([])}>{de?'Auswahl aufheben':'Clear selection'}</button><span>{chosen.length} {de?'ausgewählt':'selected'}</span></div>
 <div className="gallery-actions"><button className="button secondary" disabled={busy||!chosen.length} onClick={()=>data&&void apply('restore',chosen,data.rootId)}>{de?'Auswahl wiederherstellen':'Restore selected'}</button><button className="button secondary" disabled={busy||!chosen.length} onClick={()=>data&&setConfirm({ids:[...chosen],rootId:data.rootId})}>{de?'Endgültig löschen …':'Permanently delete …'}</button></div>
 {data&&!data.total&&<p>{de?'Der Papierkorb ist leer.':'Trash is empty.'}</p>}
 {data?.entries.map(item=><div className="gallery-trash-row" key={item.id}><input type="checkbox" aria-label={`${de?'Auswählen':'Select'}: ${item.originalPath}`} checked={chosen.includes(item.id)} disabled={busy} onChange={e=>setChosen(old=>e.target.checked?[...old,item.id]:old.filter(id=>id!==item.id))}/><button className="gallery-file" disabled={busy} onClick={()=>void preview(item)}><span><strong>{item.originalPath}</strong><small>{formatBytes(item.bytes,de?'de':'en')} · {de?'Gelöscht am':'Deleted'} {new Date(item.deletedAt).toLocaleString(de?'de':'en')}</small></span></button></div>)}
 {!!data&&data.total>50&&<div className="gallery-pagination"><button className="button secondary" disabled={busy||offset===0} onClick={()=>setOffset(n=>n-50)}>{de?'Zurück':'Previous'}</button><span>{offset+1}–{Math.min(offset+50,data.total)} / {data.total}</span><button className="button secondary" disabled={busy||offset+50>=data.total} onClick={()=>setOffset(n=>n+50)}>{de?'Weiter':'Next'}</button></div>}
 </section>
 {detail&&<section className="panel gallery-trash gallery-viewer"><h2>{previewName}</h2><button className="text-button" onClick={()=>{generation.current++;setDetail(null);}}>{de?'Vorschau schließen':'Close preview'}</button>{detail.kind==='image'?<img className="gallery-trash-image" src={detail.url} onError={()=>setPreviewError(detail.url)} alt={de?'Papierkorbvorschau':'Trash preview'}/>:detail.kind==='video'?<video src={detail.url} onError={()=>setPreviewError(detail.url)} controls preload="metadata"/>:<audio src={detail.url} onError={()=>setPreviewError(detail.url)} controls preload="metadata"/>}{previewError===detail.url&&<p className="notice warning" role="alert">{de?'Keine Vorschau möglich. Format/Codec nicht unterstützt, Datei beschädigt oder Bild größer als 32 MiB. Die Datei bleibt im Papierkorb.':'Preview unavailable. Unsupported format/codec, damaged file or image larger than 32 MiB. The file remains in trash.'}</p>}</section>}
 {confirm&&<GalleryDialog title={de?'Endgültig löschen?':'Permanently delete?'} busy={busy} onClose={()=>setConfirm(null)}><p>{de?`${confirm.ids.length} Medien werden endgültig gelöscht. Das kann nicht rückgängig gemacht werden. Zugeordnete temporäre Bildkopien und Vorschaubilder werden ebenfalls entfernt; Generierungsmetadaten bleiben erhalten.`:`${confirm.ids.length} media files will be permanently deleted. This cannot be undone. Associated temporary image copies and thumbnails are also removed; generation metadata is retained.`}</p><div className="gallery-actions"><button className="button secondary" onClick={()=>setConfirm(null)}>{de?'Abbrechen':'Cancel'}</button><button className="button primary" onClick={()=>void apply('purge',confirm.ids,confirm.rootId)}>{de?'Endgültig löschen bestätigen':'Confirm permanent deletion'}</button></div></GalleryDialog>}
 </div>;
}
