import {useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {open} from '@tauri-apps/plugin-dialog';
import {ArrowDown,ArrowUp,FolderOpen,Images,LoaderCircle,Trash2} from 'lucide-react';
import {displayPath} from './helpers';

export default function GifStudio({de}:{de:boolean}){
 const [paths,setPaths]=useState<string[]>([]),[delay,setDelay]=useState(120),[looped,setLooped]=useState(true),[name,setName]=useState('animation'),[busy,setBusy]=useState(false),[result,setResult]=useState(''),[error,setError]=useState('');
 const folder=(()=>{try{return sessionStorage.getItem('studio-gallery-folder')??'';}catch{return '';}})();
 async function choose(){const selected=await open({multiple:true,filters:[{name:de?'Bilder':'Images',extensions:['png','jpg','jpeg','webp','bmp']}],title:de?'GIF-Frames auswählen':'Choose GIF frames'});if(Array.isArray(selected))setPaths(current=>[...current,...selected].slice(0,200));}
 function move(index:number,offset:number){setPaths(value=>{const next=[...value],target=index+offset;if(target<0||target>=next.length)return value;[next[index],next[target]]=[next[target],next[index]];return next;});}
 async function create(){if(busy)return;setBusy(true);setError('');setResult('');try{setResult(await invoke<string>('gif_create',{paths,folder,name,delayMs:delay,looped}));}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <div className="page gif-studio"><header className="page-heading"><div><div className="eyebrow">GIF · LOCAL</div><h1>{de?'GIF-Studio':'GIF Studio'}</h1><p>{de?'Erstellt eine Animation aus lokalen Bildern. Dafür ist kein KI-Modell nötig.':'Creates an animation from local images. No AI model is required.'}</p></div></header><div className="gif-layout"><section className="panel"><div className="section-heading"><h2>{de?'Frames':'Frames'} · {paths.length}</h2><button className="button secondary" onClick={()=>void choose()} disabled={busy||paths.length>=200}><FolderOpen size={16}/>{de?'Bilder hinzufügen':'Add images'}</button></div>{paths.length===0?<p className="hub-hint">{de?'Wähle 1 bis 200 Bilder. Abweichende Größen werden an das erste Bild angepasst.':'Choose 1 to 200 images. Different sizes are fitted to the first image.'}</p>:<ol className="gif-frames">{paths.map((path,index)=><li key={`${path}-${index}`}><span title={path}>{displayPath(path).split(/[\\/]/).pop()}</span><button className="icon-button" aria-label={de?'Nach oben':'Move up'} disabled={index===0||busy} onClick={()=>move(index,-1)}><ArrowUp size={14}/></button><button className="icon-button" aria-label={de?'Nach unten':'Move down'} disabled={index===paths.length-1||busy} onClick={()=>move(index,1)}><ArrowDown size={14}/></button><button className="icon-button" aria-label={de?'Entfernen':'Remove'} disabled={busy} onClick={()=>setPaths(value=>value.filter((_,i)=>i!==index))}><Trash2 size={14}/></button></li>)}</ol>}</section><section className="panel gif-options"><h2>{de?'Ausgabe':'Output'}</h2><label className="field-label">{de?'Dateiname':'File name'}<input value={name} maxLength={170} onChange={e=>setName(e.target.value)}/></label><label className="field-label">{de?'Dauer je Frame (ms)':'Time per frame (ms)'}<input type="number" min={20} max={10000} value={delay} onChange={e=>setDelay(Number(e.target.value))}/></label><label className="privacy-check"><input type="checkbox" checked={looped} onChange={e=>setLooped(e.target.checked)}/>{de?'Endlosschleife':'Loop forever'}</label><p className="hub-hint">{folder?(de?`Ziel: aktueller Galerieordner „${folder}“`:`Target: current gallery folder “${folder}”`):(de?'Ziel: Galerie':'Target: Gallery')}</p><button className="button primary" disabled={busy||!paths.length||!name.trim()||delay<20||delay>10000} onClick={()=>void create()}>{busy?<LoaderCircle className="spin" size={16}/>:<Images size={16}/>}GIF {de?'erstellen':'Create'}</button>{result&&<p className="notice">{de?'Gespeichert: ':'Saved: '}{displayPath(result)}</p>}{error&&<p className="notice warning" role="alert">{error}</p>}</section></div></div>;
}
