import {forwardRef,useEffect,useImperativeHandle,useRef,useState,type PointerEvent} from 'react';
import {invoke} from '@tauri-apps/api/core';
import type {ImageReference} from './image-api';
import {setMenuContext} from './menu-context';
type Stroke={tool:'brush'|'erase'|'rectangle';size:number;points:[number,number][]};
export type EditCanvasHandle={mask:()=>string|null};
export default forwardRef<EditCanvasHandle,{reference:ImageReference|null;de:boolean;disabled:boolean;onValid:(valid:boolean)=>void}>(function ImageEditCanvas({reference,de,disabled,onValid},ref){
 const [url,setUrl]=useState(''),[error,setError]=useState(''),[whole,setWhole]=useState(false),[tool,setTool]=useState<Stroke['tool']>('brush'),[size,setSize]=useState(40),[strokes,setStrokes]=useState<Stroke[]>([]),[redo,setRedo]=useState<Stroke[]>([]),[live,setLive]=useState<Stroke|null>(null);
 const image=useRef<HTMLImageElement>(null),overlay=useRef<HTMLCanvasElement>(null),mask=useRef<HTMLCanvasElement|null>(null),gesture=useRef<Stroke|null>(null);
 const key=reference?.sha256??'',previewKey=useRef('');
 useEffect(()=>{let alive=true;previewKey.current='';setUrl('');setError('');setWhole(false);setStrokes([]);setRedo([]);setLive(null);mask.current=null;gesture.current=null;
  onValid(false);
  if(reference){try{const saved=JSON.parse(localStorage.getItem('image-edit-selection:'+key)??'[]');if(Array.isArray(saved)&&saved.length<=200&&saved.every(s=>['brush','erase','rectangle'].includes(s.tool)&&Number.isFinite(s.size)&&s.size>=4&&s.size<=300&&Array.isArray(s.points)&&s.points.length<=2000&&s.points.every((p:unknown)=>Array.isArray(p)&&p.length===2&&p.every(n=>Number.isFinite(n)&&n>=0&&n<=1))))setStrokes(saved);}catch{/* fresh selection */}
   void invoke<{preview:string}>('image_reference',{path:reference.path}).then(result=>{if(alive){previewKey.current=key;setUrl(result.preview);}}).catch(e=>{if(alive)setError(String(e));});}
  return()=>{alive=false;};
 },[key,reference?.path]);
 useEffect(()=>{if(!reference||!url||previewKey.current!==key)return;const w=reference.width,h=reference.height;const c=mask.current??document.createElement('canvas');c.width=w;c.height=h;mask.current=c;const ctx=c.getContext('2d')!;ctx.fillStyle='#000';ctx.fillRect(0,0,w,h);
  for(const stroke of [...strokes,...(live?[live]:[])]){if(!stroke.points.length)continue;ctx.fillStyle=ctx.strokeStyle=stroke.tool==='erase'?'#000':'#fff';ctx.lineWidth=stroke.size;ctx.lineCap=ctx.lineJoin='round';const p=stroke.points;
   if(stroke.tool==='rectangle'){const end=p.at(-1)!;ctx.fillRect(Math.min(p[0][0],end[0])*w,Math.min(p[0][1],end[1])*h,Math.abs(end[0]-p[0][0])*w,Math.abs(end[1]-p[0][1])*h);}
   else{ctx.beginPath();ctx.moveTo(p[0][0]*w,p[0][1]*h);for(const q of p.slice(1))ctx.lineTo(q[0]*w,q[1]*h);ctx.stroke();ctx.beginPath();ctx.arc(p[0][0]*w,p[0][1]*h,stroke.size/2,0,Math.PI*2);ctx.fill();}}
  const o=overlay.current;if(o){o.width=w;o.height=h;const data=ctx.getImageData(0,0,w,h);let any=false;for(let i=0;i<data.data.length;i+=4){const alpha=data.data[i];any ||= alpha>0;data.data[i]=160;data.data[i+1]=110;data.data[i+2]=255;data.data[i+3]=whole?0:Math.round(alpha*.45);}o.getContext('2d')!.putImageData(data,0,0);onValid(whole||any);}
  try{if(!live)localStorage.setItem('image-edit-selection:'+key,JSON.stringify(strokes));}catch{/* local draft only */}
 },[reference?.width,reference?.height,url,strokes,live,whole,key,onValid]);
 useImperativeHandle(ref,()=>({mask:()=>{if(previewKey.current!==key||!mask.current)throw new Error('image_mask');return whole?null:mask.current.toDataURL('image/png').split(',')[1];}}),[whole,key]);
 useEffect(()=>{if(disabled)return;return setMenuContext('image-selection',{priority:3,actions:{...(strokes.length?{undo:()=>{setRedo(r=>[...r,strokes.at(-1)!]);setStrokes(s=>s.slice(0,-1));}}:{}),...(redo.length?{redo:()=>{setStrokes(s=>[...s,redo.at(-1)!]);setRedo(r=>r.slice(0,-1));}}:{})}});},[disabled,strokes,redo]);
 function point(e:PointerEvent):[number,number]{const r=image.current!.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];}
 function down(e:PointerEvent){if(disabled||whole||!image.current||e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);gesture.current={tool,size,points:[point(e)]};setLive({...gesture.current});}
 function move(e:PointerEvent){const g=gesture.current;if(!g)return;if(g.points.length>=2000)return;const q=point(e);g.points=g.tool==='rectangle'?[g.points[0],q]:[...g.points,q];setLive({...g});}
 function end(e:PointerEvent){const g=gesture.current;if(!g)return;move(e);gesture.current=null;setStrokes(old=>[...old,g].slice(-200));setRedo([]);setLive(null);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}
 return <section className="image-canvas edit-canvas" aria-label={de?'Bildbereiche markieren':'Mark image regions'}><div className="image-canvas-toolbar"><strong>{de?'Bearbeitungsfläche':'Editing canvas'}</strong><span>{reference?`${reference.width} × ${reference.height}`:''}</span></div>
 <fieldset className="edit-tools" disabled={disabled||!reference}><div role="group" aria-label={de?'Bearbeitungsbereich':'Editing area'}><button type="button" aria-pressed={!whole} onClick={()=>setWhole(false)}>{de?'Markierte Bereiche':'Selected regions'}</button><button type="button" aria-pressed={whole} onClick={()=>setWhole(true)}>{de?'Ganzes Bild':'Whole image'}</button></div><div role="group" aria-label={de?'Auswahlwerkzeuge':'Selection tools'}>{(['brush','rectangle','erase'] as const).map(t=><button type="button" key={t} disabled={whole} aria-pressed={tool===t} onClick={()=>setTool(t)}>{({brush:de?'Pinsel':'Brush',rectangle:de?'Rechteck':'Rectangle',erase:de?'Radierer':'Eraser'})[t]}</button>)}</div><label>{de?'Pinselgröße':'Brush size'}<input type="range" min={4} max={300} value={size} onChange={e=>setSize(Number(e.target.value))}/><span>{size} px</span></label><button type="button" disabled={!strokes.length} onClick={()=>{setRedo(r=>[...r,strokes.at(-1)!]);setStrokes(s=>s.slice(0,-1));}}>{de?'Rückgängig':'Undo'}</button><button type="button" disabled={!redo.length} onClick={()=>{setStrokes(s=>[...s,redo.at(-1)!]);setRedo(r=>r.slice(0,-1));}}>{de?'Wiederholen':'Redo'}</button><button type="button" disabled={!strokes.length} onClick={()=>{setStrokes([]);setRedo([]);}}>{de?'Auswahl löschen':'Clear selection'}</button></fieldset>
 {error&&<p role="alert">{error}</p>}<div className="edit-image-viewport">{url?<div className="edit-image-surface" onPointerDown={down} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{gesture.current=null;setLive(null);}}><img ref={image} src={url} draggable={false} alt={de?'Bild zur Bearbeitung':'Image to edit'}/><canvas ref={overlay}/></div>:<div className="image-canvas-empty"><h2>{de?'Welches Bild möchtest du bearbeiten?':'Which image would you like to edit?'}</h2><p>{de?'Bild links öffnen, hineinziehen oder aus der Galerie wählen.':'Open or drop an image, or choose one from the gallery.'}</p></div>}</div><p className="hub-hint edit-help">{whole?(de?'Die KI darf das gesamte Bild verändern.':'AI may modify the entire image.'):(de?'Violett markiert die zu bearbeitenden Bereiche. Der unmarkierte Bereich bleibt erhalten.':'Purple marks the regions to edit. Unmarked regions are preserved.')}</p></section>;
});
