import {useEffect,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {open} from '@tauri-apps/plugin-dialog';
import {imageError,type ImageReference,type ImageRequest} from './image-api';
import {displayPath} from './helpers';
export default function ImageEditSource({request,onChange,disabled,de}:{request:ImageRequest;onChange:(patch:Partial<ImageRequest>)=>void;disabled:boolean;de:boolean}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function accept(path:string){setBusy(true);setError('');try{const result=await invoke<{reference:ImageReference}>('image_edit_source',{path});onChange({reference:result.reference,width:result.reference.width,height:result.reference.height});}catch(e){setError(imageError(e,de));}finally{setBusy(false);}}
 useEffect(()=>{const handler=(event:Event)=>{if(disabled||busy)return;const paths=(event as CustomEvent<{paths:string[]}>).detail?.paths;if(Array.isArray(paths)&&typeof paths[0]==='string')void accept(paths[0]);};window.addEventListener('studio-reference-drop',handler);return()=>window.removeEventListener('studio-reference-drop',handler);},[disabled,busy,onChange,de]);
 return <section className="image-edit-source gif-reference-drop" data-file-drop={disabled||busy?undefined:'reference'}><h2>{de?'1. Bild öffnen':'1. Open image'}</h2><p className="hub-hint">{de?'Bild hierher ziehen. PNG, JPEG, WebP oder BMP.':'Drop an image here. PNG, JPEG, WebP or BMP.'}</p><button type="button" className="button secondary" disabled={disabled||busy} onClick={()=>void (async()=>{try{const path=await open({multiple:false,filters:[{name:'Images',extensions:['png','jpg','jpeg','webp','bmp']}]});if(typeof path==='string')await accept(path);}catch(e){setError(imageError(e,de));}})()}>{busy?(de?'Bild wird vorbereitet …':'Preparing image …'):(de?'Bild öffnen':'Open image')}</button>{request.reference&&<><p className="download-path">{displayPath(request.reference.path).split(/[\\/]/).pop()} · {request.reference.width} × {request.reference.height}</p><p className="hub-hint">{de?'Eine Arbeitskopie wird auf modellkompatible Maße angepasst. Das Original bleibt unverändert.':'A working copy is resized for the model. The original is unchanged.'}</p><label className="field-label">{de?'Veränderungsstärke':'Denoising strength'}<input type="range" min={0.05} max={1} step={0.05} value={request.reference.strength} disabled={disabled||busy} onChange={e=>onChange({reference:{...request.reference!,strength:Number(e.target.value)}})}/><span>{Math.round(request.reference.strength*100)} %</span></label><button type="button" className="text-button" disabled={disabled||busy} onClick={()=>onChange({reference:null})}>{de?'Bild entfernen':'Remove image'}</button></>}{error&&<p role="alert" className="notice warning">{error}</p>}</section>;
}
