import {setMenuContext} from './menu-context';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {galleryError,type GalleryEntry,type LineageQuery} from './gallery-api';
import {appendEdit,undoEdit,redoEdit,emptyHistory,editorApi,editorActivity,type EditHistory,type EditOperation,type EditPreview} from './editor-state';
import {shortcutFor,type Shortcuts} from './shortcuts';
import './image-editor.css';
import CorrectionControls from './CorrectionControls';
import {neutralCorrections,type Corrections,type ProjectEditQuery} from './editor-state';

export default function ImageEditor({entry,rootId,de,shortcuts,maxUndo,onClose,project,onAddToProject,onSaveProject}:{entry:Pick<GalleryEntry,'name'|'path'|'fileId'|'thumbnailVersion'>;rootId:string;de:boolean;shortcuts:Shortcuts;maxUndo:number;onClose:(path?:string)=>void;project?:{query:ProjectEditQuery;operations:EditOperation[]};onAddToProject?:(ops:EditOperation[])=>Promise<ProjectEditQuery|null>;onSaveProject?:(query:ProjectEditQuery,expected:EditOperation[],ops:EditOperation[])=>Promise<boolean>}){
 const query:LineageQuery={rootId,target:{path:entry.path,fileId:entry.fileId!,version:entry.thumbnailVersion}};
 const key=project?`editor-project-v1:${project.query.id}:${project.query.assetId}:${project.query.sha256}`:`editor-v1:${rootId}:${entry.fileId}:${entry.thumbnailVersion}`;
 const initial:EditHistory=project?{operations:project.operations,cursor:project.operations.length,floor:Math.max(0,project.operations.length-maxUndo)}:emptyHistory;
 const [corrections,setCorrections]=useState<Corrections>({...neutralCorrections}),[comparing,setComparing]=useState(false),[original,setOriginal]=useState<EditPreview|null>(null);
 const bound=useRef<ProjectEditQuery|null>(project?.query??null),stored=useRef<EditOperation[]>(project?.operations??[]);
 const [projectSaved,setProjectSaved]=useState(project?JSON.stringify(project.operations):'');
 const render=(ops:EditOperation[])=>project?editorApi.projectPreview(project.query,ops):editorApi.preview(query,ops);
 const dialog=useRef<HTMLDialogElement>(null),stage=useRef<HTMLDivElement>(null),picture=useRef<HTMLImageElement>(null),gate=useRef(false);
 const [history,setHistory]=useState<EditHistory>(initial),[preview,setPreview]=useState<EditPreview|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[note,setNote]=useState(''),[saved,setSaved]=useState('');
 const [recovery,setRecovery]=useState<EditHistory|null>(()=>{try{const h=JSON.parse(localStorage.getItem(key)??'null');return h&&Array.isArray(h.operations)&&h.operations.length<=1000&&Number.isInteger(h.cursor)&&h.cursor>=0&&h.cursor<=h.operations.length&&Number.isInteger(h.floor)&&h.floor>=0&&h.floor<=h.cursor?h:null;}catch{return null;}});
 const [closing,setClosing]=useState(false),[cropMode,setCropMode]=useState(false),[crop,setCrop]=useState({x:0,y:0,width:1,height:1}),[size,setSize]=useState({width:1,height:1}),[ratio,setRatio]=useState(true),[format,setFormat]=useState<'png'|'jpeg'>('png'),[quality,setQuality]=useState(90),[zoom,setZoom]=useState(1),[actual,setActual]=useState(false);
 const [viewport,setViewport]=useState({width:800,height:600});
 useEffect(()=>{const el=stage.current;if(!el)return;const o=new ResizeObserver(()=>setViewport({width:el.clientWidth,height:el.clientHeight}));o.observe(el);return()=>o.disconnect();},[]);
 const drag=useRef<{x:number;y:number;id:number}|null>(null),pan=useRef<{x:number;y:number;left:number;top:number;id:number}|null>(null);
 const t=(a:string,b:string)=>de?a:b;
 const active=history.operations.slice(0,history.cursor);const dirty=(active.length>0||!!project)&&JSON.stringify(active)!==saved&&JSON.stringify(active)!==projectSaved;
 function persist(h:EditHistory){try{if(h.operations.length)localStorage.setItem(key,JSON.stringify(h));else localStorage.removeItem(key);editorActivity.persisted=true;}catch{editorActivity.persisted=false;setError(t('Der Entwurf konnte nicht lokal gespeichert werden. Bitte vor dem Schließen exportieren.','The draft could not be saved locally. Export before closing.'));}}
 function accept(p:EditPreview,h:EditHistory){editorActivity.draft=h.cursor>0&&JSON.stringify(h.operations.slice(0,h.cursor))!==saved;setPreview(p);setHistory(h);setCrop({x:0,y:0,width:p.width,height:p.height});setSize({width:p.width,height:p.height});setCropMode(false);setZoom(1);setActual(false);persist(h);}
 useEffect(()=>{const el=dialog.current;el?.showModal();let live=true;gate.current=true;const pending=(async()=>{const before=await render([]);const p=initial.cursor?await render(initial.operations):before;return {before,p};})();editorActivity.pending=pending;void pending.then(({before,p})=>{if(live){setOriginal(before);setPreview(p);setCrop({x:0,y:0,width:p.width,height:p.height});setSize({width:p.width,height:p.height});}}).catch(e=>{if(live)setError(galleryError(e,de));}).finally(()=>{gate.current=false;editorActivity.pending=null;if(live)setBusy(false);});return()=>{live=false;el?.close();editorActivity.draft=false;};},[]);
 useEffect(()=>{editorActivity.draft=dirty;return()=>{editorActivity.draft=false;};},[dirty]);
 async function change(next:EditHistory){if(gate.current)return;gate.current=true;setBusy(true);setError('');setNote('');const pending=render(next.operations.slice(0,next.cursor));editorActivity.pending=pending;try{accept(await pending,next);setRecovery(null);setCorrections({...neutralCorrections});}catch(e){setError(galleryError(e,de));}finally{gate.current=false;editorActivity.pending=null;setBusy(false);}}
 function apply(op:EditOperation){void change(appendEdit(history,op,maxUndo));}
 function close(){if(gate.current)return;if(dirty){setClosing(true);}else onClose();}
 async function exportImage(){if(gate.current)return;gate.current=true;setBusy(true);setError('');const pending=project?editorApi.projectExport(project.query,active,format,quality):editorApi.export(query,active,format,quality);editorActivity.pending=pending;try{const path=await pending;setSaved(JSON.stringify(active));setNote(t(`Exportiert: ${path}`,`Exported: ${path}`));persist(emptyHistory);setRecovery(null);}catch(e){setError(galleryError(e,de));}finally{gate.current=false;editorActivity.pending=null;setBusy(false);}}
 async function storeProject(){if(gate.current)return;gate.current=true;setBusy(true);setError('');const pending=(async()=>{if(bound.current){if(!await onSaveProject?.(bound.current,stored.current,active))throw new Error(t('Bearbeitung konnte nicht übernommen werden. Projektstatus prüfen.','Could not store edits. Check project status.'));}else{const q=await onAddToProject?.(active);if(!q)throw new Error(t('Projektübernahme fehlgeschlagen.','Could not add edits to project.'));bound.current=q;}stored.current=active;setProjectSaved(JSON.stringify(active));persist(emptyHistory);setRecovery(null);setNote(t('Original und Bearbeitung im Projektarbeitsstand. Editor schließen und Projektdatei mit Strg+S speichern.','Original and edits stored in project workspace. Close the editor and save the project file with Ctrl+S.'));})();editorActivity.pending=pending;try{await pending;}catch(e){setError(galleryError(e,de));}finally{gate.current=false;editorActivity.pending=null;setBusy(false);}}
 function point(e:PointerEvent){const r=picture.current!.getBoundingClientRect();return {x:Math.max(0,Math.min(preview!.width,Math.round((e.clientX-r.left)/r.width*preview!.width))),y:Math.max(0,Math.min(preview!.height,Math.round((e.clientY-r.top)/r.height*preview!.height)))};}
 function start(e:PointerEvent<HTMLDivElement>){if(!preview||busy)return;if(e.button===1){e.preventDefault();pan.current={x:e.clientX,y:e.clientY,left:stage.current!.scrollLeft,top:stage.current!.scrollTop,id:e.pointerId};e.currentTarget.setPointerCapture(e.pointerId);}else if(e.button===0&&cropMode){e.preventDefault();drag.current={...point(e),id:e.pointerId};e.currentTarget.setPointerCapture(e.pointerId);}}
 function move(e:PointerEvent<HTMLDivElement>){if(pan.current){stage.current!.scrollLeft=pan.current.left-(e.clientX-pan.current.x);stage.current!.scrollTop=pan.current.top-(e.clientY-pan.current.y);}const d=drag.current;if(d&&preview){const p=point(e);setCrop({x:Math.min(d.x,p.x),y:Math.min(d.y,p.y),width:Math.abs(p.x-d.x),height:Math.abs(p.y-d.y)});}}
 function resetView(){setZoom(1);setActual(false);if(stage.current){stage.current.scrollLeft=0;stage.current.scrollTop=0;}}
 useEffect(()=>setMenuContext('editor',{priority:2,actions:{...(!busy&&history.cursor>history.floor?{undo:()=>void change(undoEdit(history))}:{}),...(!busy&&history.cursor<history.operations.length?{redo:()=>void change(redoEdit(history))}:{}),imageFit:resetView,imageReset:resetView,imageActual:()=>{setActual(true);setZoom(1);}}}),[busy,history,preview]);
 const validCrop=preview&&crop.width>0&&crop.height>0&&crop.x+crop.width<=preview.width&&crop.y+crop.height<=preview.height;
 const validSize=size.width>0&&size.height>0&&size.width<=16384&&size.height<=16384&&size.width*size.height<=32_000_000;
 return <dialog ref={dialog} className="image-editor" aria-label={t('Bildeditor','Image editor')} onCancel={e=>{e.preventDefault();close();}} onKeyDown={e=>{
   if((e.target as HTMLElement).closest('input,select,textarea'))return;const command=shortcutFor(e.nativeEvent,shortcuts);if(['undo','redo','imageFit','imageActual','imageReset'].includes(command??'')){e.preventDefault();e.stopPropagation();if(busy)return;if(command==='undo')void change(undoEdit(history));else if(command==='redo')void change(redoEdit(history));else if(command==='imageActual'){setZoom(1);setActual(true);}else resetView();}
 }}>
 <header className="editor-heading"><div><div className="eyebrow">EDIT</div><h2>{entry.name}</h2><small>{t('Original bleibt erhalten · Bearbeitung als neue Variante','Original retained · Edits export as a new variant')}</small></div><button className="button secondary" disabled={busy} onClick={close}>{t('Editor schließen','Close editor')}</button></header>
 {error&&<p className="notice warning" role="alert">{error}</p>}{note&&<p className="notice" role="status">{note}</p>}
 {recovery&&<div className="notice editor-recovery"><span>{t('Ein lokaler Bearbeitungsentwurf ist vorhanden.','A local editing draft is available.')}</span><button className="button secondary" disabled={busy} onClick={()=>void change(recovery)}>{t('Entwurf fortsetzen','Resume draft')}</button><button className="text-button" disabled={busy} onClick={()=>{persist(emptyHistory);setRecovery(null);}}>{t('Entwurf verwerfen','Discard draft')}</button></div>}
 {closing&&<div className="notice editor-close" role="alert"><p>{editorActivity.persisted?t('Die Änderungen sind noch nicht exportiert. Entwurf behalten oder verwerfen?','Changes have not been exported. Keep or discard the draft?'):t('Der Entwurf ist nicht gespeichert. Zurückgehen und exportieren oder Änderungen verwerfen.','The draft is not saved. Go back and export, or discard changes.')}</p><button className="button secondary" onClick={()=>setClosing(false)}>{t('Weiter bearbeiten','Continue editing')}</button><button className="button secondary" onClick={()=>{persist(emptyHistory);onClose();}}>{t('Verwerfen und schließen','Discard and close')}</button>{editorActivity.persisted&&<button className="button primary" onClick={()=>onClose()}>{t('Entwurf behalten und schließen','Keep draft and close')}</button>}</div>}
 <div className="editor-toolbar"><button className="button secondary" disabled={busy||history.cursor<=history.floor} onClick={()=>void change(undoEdit(history))}>{t('Rückgängig','Undo')}</button><button className="button secondary" disabled={busy||history.cursor>=history.operations.length} onClick={()=>void change(redoEdit(history))}>{t('Wiederholen','Redo')}</button><span>{history.cursor} {t('Schritte','steps')}</span><button className="text-button" onClick={resetView}>{t('Einpassen','Fit')}</button><button className="text-button" onClick={()=>{setActual(true);setZoom(1);}}>100 %</button><label>Zoom <input aria-label="Editor zoom" type="range" min={0.25} max={4} step={0.25} value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label></div>
 <label className="editor-check"><input type="checkbox" checked={comparing} disabled={!original||busy||cropMode} onChange={e=>setComparing(e.target.checked)}/>{t('Vorher / Nachher','Before / After')}</label><div className="editor-layout"><div className="editor-stage" ref={stage} tabIndex={0} aria-label={t('Bearbeitungsfläche','Editing canvas')} onWheel={e=>{if(!e.ctrlKey)setZoom(z=>Math.max(.25,Math.min(4,z+(e.deltaY<0?.25:-.25))));}}>
 {comparing&&original&&preview?<div className="editor-comparison"><figure><figcaption>{t('Original','Original')}</figcaption><img src={original.dataUrl} alt={t('Originalvorschau','Original preview')}/></figure><figure><figcaption>{t('Bearbeitet','Edited')}</figcaption><img src={preview.dataUrl} alt={t('Bearbeitungsvergleich','Edited comparison')}/></figure></div>:preview&&<div className="editor-picture" style={{width:(actual?preview.width:Math.min(viewport.width,viewport.height*preview.width/preview.height,preview.width))*zoom,maxWidth:'none'}} onPointerDown={start} onPointerMove={move} onPointerUp={()=>{drag.current=null;pan.current=null;}} onPointerCancel={()=>{drag.current=null;pan.current=null;}} onLostPointerCapture={()=>{drag.current=null;pan.current=null;}}><img ref={picture} src={preview.dataUrl} draggable={false} alt={t('Bearbeitungsvorschau','Edit preview')}/>{cropMode&&<div className="editor-crop" style={{left:`${crop.x/preview.width*100}%`,top:`${crop.y/preview.height*100}%`,width:`${crop.width/preview.width*100}%`,height:`${crop.height/preview.height*100}%`}}/>}</div>}
 {busy&&<div className="editor-working" role="status">{t('Bild wird verarbeitet …','Processing image …')}</div>}</div>
 <aside className="editor-tools"><CorrectionControls value={corrections} onChange={setCorrections} de={de} disabled={busy||!preview||closing||!!recovery}/><button className="button secondary" disabled={busy||!preview||closing||!!recovery||Object.values(corrections).every(v=>v===0)} onClick={()=>apply({type:'adjust',...corrections})}>{t('Korrekturen anwenden','Apply corrections')}</button><p className="hub-hint">{t('Regler mit Anwenden übernehmen; jeder Schritt ist rückgängig machbar.','Commit sliders with Apply; every step can be undone.')}</p><fieldset disabled={busy||!preview||closing||!!recovery}><legend>{t('Transformieren','Transform')}</legend><div className="editor-buttons"><button className="button secondary" onClick={()=>apply({type:'rotate',clockwise:false})}>{t('90° links','90° left')}</button><button className="button secondary" onClick={()=>apply({type:'rotate',clockwise:true})}>{t('90° rechts','90° right')}</button><button className="button secondary" onClick={()=>apply({type:'flip',horizontal:true})}>{t('Horizontal spiegeln','Flip horizontal')}</button><button className="button secondary" onClick={()=>apply({type:'flip',horizontal:false})}>{t('Vertikal spiegeln','Flip vertical')}</button></div>
 <h3>{t('Zuschneiden','Crop')}</h3><button className="text-button" aria-pressed={cropMode} onClick={()=>{setComparing(false);setCropMode(v=>!v);}}>{cropMode?t('Auswahl ausblenden','Hide selection'):t('Ausschnitt im Bild ziehen','Drag crop in image')}</button><div className="editor-fields">{(['x','y','width','height'] as const).map(k=><label key={k}>{({x:'X',y:'Y',width:t('Ausschnittbreite','Crop width'),height:t('Ausschnitthöhe','Crop height')})[k]}<input type="number" min={k==='x'||k==='y'?0:1} max={k==='x'||k==='width'?preview?.width:preview?.height} value={crop[k]} onChange={e=>{setCropMode(true);setCrop(c=>({...c,[k]:Math.floor(Number(e.target.value))}));}}/></label>)}</div><button className="button secondary" disabled={!validCrop} onClick={()=>apply({type:'crop',...crop})}>{t('Ausschnitt anwenden','Apply crop')}</button>
 <h3>{t('Größe ändern','Resize')}</h3><div className="editor-fields">{(['width','height'] as const).map(k=><label key={k}>{k==='width'?t('Breite','Width'):t('Höhe','Height')}<input type="number" min={1} max={16384} value={size[k]} onChange={e=>{const n=Math.floor(Number(e.target.value));setSize(s=>({...s,[k]:n,...(ratio&&preview?{[k==='width'?'height':'width']:Math.max(1,Math.round(n*(k==='width'?preview.height/preview.width:preview.width/preview.height)))}:{})}));}}/></label>)}</div><label className="editor-check"><input type="checkbox" checked={ratio} onChange={e=>setRatio(e.target.checked)}/>{t('Seitenverhältnis beibehalten','Lock aspect ratio')}</label><button className="button secondary" disabled={!validSize} onClick={()=>apply({type:'resize',...size})}>{t('Größe anwenden','Apply size')}</button>
 {(onAddToProject||onSaveProject)&&<><h3>{t('Bearbeitbares Projekt','Editable project')}</h3><button className="button secondary" disabled={(!bound.current&&!onAddToProject)||JSON.stringify(active)===projectSaved} onClick={()=>void storeProject()}>{t('Bearbeitung ins Projekt übernehmen','Store edits in project')}</button><p className="hub-hint">{t('Original und Schritte bleiben separat und weiter bearbeitbar.','Original and steps remain separate and editable.')}</p></>}<h3>{t('Export als Variante','Export as variant')}</h3><label>Format<select aria-label="Format" value={format} onChange={e=>setFormat(e.target.value as 'png'|'jpeg')}><option value="png">PNG · Alpha</option><option value="jpeg">JPEG</option></select></label>{format==='jpeg'&&<label>{t('JPEG-Qualität','JPEG quality')}<input aria-label={t('JPEG-Qualität','JPEG quality')} type="range" min={1} max={100} value={quality} onChange={e=>setQuality(Number(e.target.value))}/><span>{quality} / 100</span></label>}<p className="hub-hint">{format==='jpeg'?t('Transparenz wird weiß hinterlegt.','Transparency is flattened on white.'):t('Transparenz bleibt erhalten.','Transparency is retained.')} {t('8-Bit-Ausgabe. ICC-Profil wird erhalten; EXIF/GPS werden entfernt.','8-bit output. ICC profile is retained; EXIF/GPS are removed.')}</p><button className="button primary" onClick={()=>void exportImage()}>{t('Als Variante exportieren','Export as variant')}</button><p className="hub-hint">{project?t('Neue Datei im Galerieordner.','New file in the gallery folder.'):t('Neue Datei im Ordner des Originals.','New file in the original’s folder.')}</p></fieldset></aside></div>
 <footer className="editor-footer"><span>{preview?`${preview.width} × ${preview.height} px`:'—'} · {preview?.profile?'ICC':t('Ohne ICC-Profil','No ICC profile')}</span><span>{t('Mausrad: Zoom · mittlere Maustaste: verschieben · Vorschau bis 1600 px, Export in voller Größe','Wheel: zoom · middle mouse: pan · Preview up to 1600 px, full-size export')}</span></footer>
 </dialog>;
}
