import {useEffect,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {open} from '@tauri-apps/plugin-dialog';
import {imageError,type ImageReference,type ImageRequest} from './image-api';
export default function ImageReferenceInput({request,onChange,de,disabled}:{request:ImageRequest;onChange:(patch:Partial<ImageRequest>)=>void;de:boolean;disabled:boolean}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState(''),[maskPreview,setMaskPreview]=useState('');const reference=request.reference;
 useEffect(()=>{let alive=true;setPreview('');if(reference)void invoke<{reference:ImageReference;preview:string}>('image_reference',{path:reference.path}).then(r=>{if(alive&&r.reference.sha256===reference.sha256)setPreview(r.preview);}).catch(()=>{});return()=>{alive=false;};},[reference?.path,reference?.sha256]);
 useEffect(()=>{let alive=true;setMaskPreview('');if(reference?.mask)void invoke<{reference:ImageReference;preview:string}>('image_reference',{path:reference.mask.path,mask:true}).then(r=>{if(alive&&r.reference.sha256===reference.mask?.sha256)setMaskPreview(r.preview);}).catch(()=>{});return()=>{alive=false;};},[reference?.mask?.path,reference?.mask?.sha256]);
 async function choose(){setBusy(true);setError('');try{const path=await open({multiple:false,filters:[{name:'PNG',extensions:['png']}],title:de?'Referenzbild wählen':'Choose reference image'});if(typeof path==='string'){const r=await invoke<{reference:ImageReference;preview:string}>('image_reference',{path});onChange({reference:r.reference,width:r.reference.width,height:r.reference.height});setPreview(r.preview);}}catch(e){setError(imageError(e,de));}finally{setBusy(false);}}
 async function chooseMask(){if(!reference)return;setBusy(true);setError('');try{const path=await open({multiple:false,filters:[{name:'PNG mask',extensions:['png']}],title:de?'Inpainting-Maske wählen':'Choose inpainting mask'});if(typeof path==='string'){const result=await invoke<{reference:ImageReference}>('image_reference',{path,mask:true});const {sha256,width,height}=result.reference;if(width!==reference.width||height!==reference.height)throw 'image_reference_parameters';onChange({reference:{...reference,mask:{path:result.reference.path,sha256,width,height}}});}}catch(e){setError(imageError(e,de));}finally{setBusy(false);}}
 return <section className="image-reference"><label className="ai-check"><input type="checkbox" disabled={disabled||busy} checked={request.vaeOnCpu??false} onChange={e=>onChange({vaeOnCpu:e.target.checked})}/>{de?'VAE auf CPU ausführen · weniger VRAM, langsamer':'Run VAE on CPU · less VRAM, slower'}</label><h3>{de?'Bild-zu-Bild · optionales Referenzbild':'Image-to-image · optional reference'}</h3><p className="hub-hint">{de?'Ohne Referenz entsteht ein Bild aus dem Prompt. Mit Referenz verändert SDXL das gewählte Bild nach deinem Prompt. PNG in 8 Bit, Breite und Höhe jeweils 512, 768 oder 1024 Pixel. Die Auswahl übernimmt diese Abmessungen. Höhere Stärke verändert das Bild stärker. Der Auftrag erhält eine geprüfte eigene Kopie; das Original bleibt unverändert. Projekte nehmen die Referenz beim Speichern mit.':'Without a reference, the prompt creates a new image. With a reference, SDXL transforms that image according to your prompt. Supports 8-bit PNG with width and height of 512, 768 or 1024 pixels. Selecting an image adopts its dimensions. Higher strength changes it more. Each job receives its own verified copy; the original is preserved. Saving a project embeds the reference.'}</p><div className="hub-actions"><button type="button" className="button secondary" disabled={disabled||busy} onClick={()=>void choose()}>{de?'Referenzbild wählen':'Choose reference image'}</button>{reference&&<button type="button" className="text-button" disabled={disabled||busy} onClick={()=>{onChange({reference:null});setError('');}}>{de?'Referenz entfernen':'Remove reference'}</button>}</div>
 {reference&&<><div className="image-mask-input"><h4>Inpainting</h4><p className="hub-hint">{de?'Optionale PNG-Maske in derselben Größe: Weiß bearbeiten, Schwarz pixelgenau beibehalten, Graustufen weich überblenden. Die Maske muss undurchsichtig sein. Referenz und Maske werden ins Projekt und in jeden Auftrag kopiert.':'Optional PNG mask of the same dimensions: edit white areas, preserve black areas pixel for pixel, blend grayscale edges. The mask must be opaque. Reference and mask are copied into the project and each job.'}</p><button type="button" className="button secondary" disabled={disabled||busy} onClick={()=>void chooseMask()}>{de?'Inpainting-Maske wählen':'Choose inpainting mask'}</button>{reference.mask&&<><p className="download-path">{reference.mask.path}</p>{maskPreview&&<img src={maskPreview} alt={de?'Inpainting-Maske':'Inpainting mask'} style={{maxWidth:180,maxHeight:180,objectFit:'contain'}}/>}<button type="button" className="text-button" disabled={disabled||busy} onClick={()=>onChange({reference:{...reference,mask:null}})}>{de?'Maske entfernen':'Remove mask'}</button></>}</div><p className="download-path">{reference.path}</p>{preview&&<img src={preview} alt={de?'Referenzbild':'Reference image'} style={{maxWidth:180,maxHeight:180,objectFit:'contain'}}/>}<label className="field-label">{de?'Veränderungsstärke':'Denoising strength'}<input aria-label={de?'Veränderungsstärke':'Denoising strength'} type="number" min={0.05} max={1} step={0.05} value={reference.strength} disabled={disabled||busy} onChange={e=>onChange({reference:{...reference,strength:Number(e.target.value)}})}/></label>{(request.width!==reference.width||request.height!==reference.height)&&<p className="notice warning">{de?'Für diese Referenz die Ausgabegröße wieder auf':'For this reference, set the output size back to'} {reference.width} × {reference.height}.</p>}</>}{error&&<p role="alert" className="notice warning">{error}</p>}
 </section>;
}
