import {useEffect,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {confirm} from '@tauri-apps/plugin-dialog';
interface Preference{modelSha256:string;modelName:string;width:number;height:number;steps:number;guidance:number;sampler:string;uses:number;custom:boolean;updatedAt:string}
export default function LearnedPreferences({de,disabled}:{de:boolean;disabled:boolean}){
 const [rows,setRows]=useState<Preference[]>([]),[draft,setDraft]=useState<Preference|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){setRows(await invoke<Preference[]>('preferences_list'));}
 useEffect(()=>{let alive=true;void invoke<Preference[]>('preferences_list').then(rows=>{if(alive)setRows(rows);}).catch(e=>{if(alive)setError(String(e));});return()=>{alive=false;};},[]);
 async function save(){if(!draft)return;setBusy(true);setError('');try{const {modelSha256,width,height,steps,guidance,sampler}=draft;await invoke('preference_save',{edit:{modelSha256,width,height,steps,guidance,sampler}});setDraft(null);await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function forget(modelSha256:string|null){if(!await confirm(modelSha256?(de?'Diese gelernte Präferenz löschen?':'Delete this learned preference?'):(de?'Alle gelernten Präferenzen zurücksetzen?':'Reset all learned preferences?'),{title:de?'Gelernte Präferenzen':'Learned preferences',kind:'warning'}))return;setBusy(true);setError('');try{await invoke('preference_forget',{modelSha256,confirmed:true});setDraft(null);await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}
 const blocked=disabled||busy;
 const dimensionLabel=(key:'width'|'height')=>key==='width'?(de?'Breite':'Width'):(de?'Höhe':'Height');
 return <section className="panel settings-section learned-preferences"><h2>{de?'Gelernte Präferenzen':'Learned preferences'}</h2><p className="hub-hint">{de?'Aus erfolgreichen Bildgenerierungen merkt sich Local Studio die Modellvariante, Nutzungshäufigkeit und zuletzt verwendeten Bildparameter. Der Assistent darf diese lokalen Daten lesen. Deine aktuelle Auswahl hat immer Vorrang; Einstellungen werden dadurch nicht automatisch geändert. Von dir bearbeitete Parameter werden beim weiteren Lernen beibehalten. Neue Generierungen können gelöschte Einträge erneut anlegen.':'Successful image generations teach Local Studio the model variant, usage count and latest image parameters. The assistant can read these local records. Your current choice always takes priority; these records never change your settings automatically. User-edited parameters are preserved during further learning. New generations can recreate deleted entries.'}</p>
 {!rows.length&&<p>{de?'Noch keine Präferenzen gelernt.':'No preferences learned yet.'}</p>}
 {rows.map(p=><article key={p.modelSha256}><h3>{p.modelName}</h3><p>{p.uses} {de?'erfolgreiche Aufträge':'successful jobs'} · {p.width} × {p.height} · {p.steps} {de?'Schritte':'steps'} · CFG {p.guidance} · {p.sampler} · {p.custom?(de?'Von dir angepasst':'Edited by you'):(de?'Zuletzt verwendet':'Last used')}</p><small>SHA-256: {p.modelSha256.slice(0,16)}</small><div className="hub-actions"><button className="button secondary" disabled={blocked} onClick={()=>setDraft({...p})}>{de?'Präferenz bearbeiten':'Edit preference'}</button><button className="text-button" disabled={blocked} onClick={()=>void forget(p.modelSha256)}>{de?'Eintrag löschen':'Delete entry'}</button></div></article>)}
 {draft&&<div className="preference-edit"><h3>{draft.modelName}</h3><div className="creative-toolbar">{(['width','height']as const).map(key=><label key={key}>{key==='width'?(de?'Breite':'Width'):(de?'Höhe':'Height')}<select aria-label={dimensionLabel(key)} value={draft[key]} disabled={blocked} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}>{[512,768,1024].map(n=><option key={n}>{n}</option>)}</select></label>)}<label>{de?'Schritte':'Steps'}<input type="number" min={1} max={60} value={draft.steps} disabled={blocked} onChange={e=>setDraft({...draft,steps:Number(e.target.value)})}/></label><label>Guidance<input type="number" min={1} max={20} step={0.1} value={draft.guidance} disabled={blocked} onChange={e=>setDraft({...draft,guidance:Number(e.target.value)})}/></label><label>Sampler<select value={draft.sampler} disabled={blocked} onChange={e=>setDraft({...draft,sampler:e.target.value})}><option>euler</option><option>dpm++2m</option></select></label></div><button className="button primary" disabled={blocked} onClick={()=>void save()}>{de?'Präferenz speichern':'Save preference'}</button><button className="text-button" disabled={blocked} onClick={()=>setDraft(null)}>{de?'Abbrechen':'Cancel'}</button></div>}
 {rows.length>0&&<button className="text-button" disabled={blocked} onClick={()=>void forget(null)}>{de?'Alle Präferenzen zurücksetzen':'Reset all preferences'}</button>}{error&&<p className="notice warning" role="alert">{de?'Präferenzen konnten nicht übernommen werden. Bitte gültige Bildparameter verwenden und erneut versuchen.':'Could not apply preferences. Use valid image parameters and try again.'}</p>}
 </section>;
}
