import {useEffect,useState} from 'react';
import {mediaApi,type MediaInfo,type MediaTask} from './media-tools';
import {creativeError} from './creative-state';
import type {ProjectAsset} from './project-api';
import {NumberField} from './CreativeControls';
export default function MediaPreparation({projectId,assets,selected,de,onInfo,onRevision}:{projectId:string;assets:ProjectAsset[];selected:string|undefined;de:boolean;onInfo:(i:MediaInfo[])=>void;onRevision:()=>void}){
 const [info,setInfo]=useState<MediaInfo[]>([]),[task,setTask]=useState<MediaTask|null>(null),[asset,setAsset]=useState(selected??''),[resolution,setResolution]=useState('auto'),[width,setWidth]=useState(960),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const t=(a:string,b:string)=>de?a:b;
 useEffect(()=>{if(selected)setAsset(selected);},[selected]);
 useEffect(()=>{let live=true;let previous='';const refresh=async()=>{try{const task=await mediaApi.status();if(!live)return;setTask(task);const key=task?`${task.id}:${task.status}`:'none';if(key!==previous){previous=key;const next=await mediaApi.info(projectId);if(live){setInfo(next);onInfo(next);onRevision();}}}catch(e){if(live)setError(creativeError(e,de));}};void refresh();const timer=setInterval(()=>void refresh(),700);return()=>{live=false;clearInterval(timer);};},[projectId,assets.length]);
 async function prepare(kind:'proxy'|'wave'){if(!asset)return;setBusy(true);setError('');try{setTask(await mediaApi.prepare(projectId,asset,kind,resolution,width));}catch(e){setError(creativeError(e,de));}finally{setBusy(false);}}
 const source=assets.find(a=>a.id===asset),row=info.find(i=>i.assetId===asset),running=task?.status==='running';
 return <details className="panel media-preparation" open><summary>{t('Proxies und Audio-Wellenformen','Proxies and audio waveforms')}</summary><div className="creative-toolbar"><label>{t('Projektmedium','Project media')}<select aria-label={t('Cache-Quellmedium','Cache source media')} value={asset} onChange={e=>setAsset(e.target.value)}><option value="">{t('Medium auswählen','Select media')}</option>{assets.filter(a=>a.kind!=='image').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>{t('Proxy-Auflösung','Proxy resolution')}<select aria-label={t('Proxy-Auflösung','Proxy resolution')} value={resolution} onChange={e=>setResolution(e.target.value)}><option value="auto">{t('Automatisch (bis 960 px)','Automatic (up to 960 px)')}</option><option value="half">1/2</option><option value="quarter">1/4</option><option value="custom">{t('Eigene Breite','Custom width')}</option></select></label>{resolution==='custom'&&<NumberField label={t('Proxy-Breite','Proxy width')} value={width} min={64} max={1920} onChange={v=>setWidth(Math.round(v))}/>}<button disabled={busy||running||source?.kind!=='video'} onClick={()=>void prepare('proxy')}>{row?.proxies.length?t('Proxy neu erstellen','Rebuild proxy'):t('Proxy erstellen','Create proxy')}</button><button disabled={busy||running||!source||source.kind==='image'} onClick={()=>void prepare('wave')}>{t('Wellenform berechnen','Compute waveform')}</button></div>
 <p>{t('Proxies erleichtern die Vorschau großer Videos. Der Export verwendet immer Originale. Wellenformen werden aus echtem Quellton berechnet; nach dem Kürzen bleiben sie zeitlich zugeordnet.','Proxies help preview large videos. Export always uses originals. Waveforms are computed from actual source audio and remain aligned after trimming.')}</p>{row?.proxies.map(p=><span className="pill" key={p.id}>{p.width} × {p.height} · {(p.bytes/1024/1024).toFixed(1)} MB</span>)}{row?.waveform&&<span className="pill">{t('Wellenform bereit','Waveform ready')}</span>}
 {task&&<div role="status">{task.name} · {task.kind==='proxy'?'Proxy':t('Wellenform','Waveform')} · {task.status}{running&&<><progress max={1} value={task.progress}/><span>{Math.floor(task.progress*100)} %</span><button onClick={()=>void mediaApi.cancel(task.id)}>{t('Medienaufbereitung abbrechen','Cancel media preparation')}</button></>}{task.error&&<p role="alert">{creativeError(task.error,de)}</p>}</div>}{error&&<p role="alert">{error}</p>}
 </details>;
}
