import { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { downloads, type DownloadPlan } from './download-api';
import { formatDate, formatGigabytes } from './helpers';
import { hubError } from './hub-i18n';
import type { Language } from './types';
interface UpdateEntry { downloadId:string; repo:string; installedRevision:string; revision:string|null; status:string; changedFiles:string[]; missingFiles:string[]; totalBytes:number|null; error:string|null; }
interface UpdateStatus {checking:boolean; checkedAt:string|null; entries:UpdateEntry[]; error:string|null;}
export default function ModelUpdates({language}:{language:Language}) {
 const de=language==='de';const [status,setStatus]=useState<UpdateStatus|null>(null),[plans,setPlans]=useState<DownloadPlan[]>([]),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[queued,setQueued]=useState<string[]>([]);
 useEffect(()=>{let alive=true,loading=false;const poll=async()=>{if(loading)return;loading=true;try{const value=await invoke<UpdateStatus>('model_updates_status');if(alive)setStatus(value);}catch(e){if(alive)setError(hubError(e,language));}finally{loading=false;}};void poll();const t=setInterval(()=>void poll(),1500);return()=>{alive=false;clearInterval(t);};},[]);
 async function check(){setBusy(true);setError('');setPlans([]);setSelected([]);try{setStatus(await invoke<UpdateStatus>('model_updates_check'));}catch(e){setError(hubError(e,language));}finally{setBusy(false);}}
 async function prepare(ids:string[]){setBusy(true);setError('');setPlans([]);try{setPlans(await invoke<DownloadPlan[]>('model_updates_prepare',{ids}));}catch(e){setError(hubError(e,language));}finally{setBusy(false);}}
 async function start(){setBusy(true);setError('');const failed:string[]=[];const pending:DownloadPlan[]=[];for(const p of plans){try{await downloads.start(p.id);setQueued(q=>[...q,p.download.repo]);}catch(e){failed.push(`${p.download.repo}: ${hubError(e,language)}`);pending.push(p);}}setPlans(pending);setSelected([]);setError(failed.join('\n'));setBusy(false);}
 const available=status?.entries.filter(e=>e.status==='available')??[];
 return <section className="panel model-updates"><h2>{de?'Modellupdates':'Model updates'}</h2><p className="hub-hint">{de?'Vergleicht die ausgewählten Dateien deiner abgeschlossenen Hugging-Face-Downloads mit dem Hauptzweig „main“. Reine Änderungen an der Modellbeschreibung zählen nicht als Gewichtsupdate. Neue Varianten landen in eigenen Ordnern; bisherige Dateien und deine Modellauswahl bleiben erhalten. Externe Modelle ohne bekannte Quelle werden nicht geprüft.':'Compares selected files from completed Hugging Face downloads with the main branch. Model-card-only changes are not weight updates. New versions use separate folders; previous files and your model selection are retained. External models without a known source cannot be checked.'}</p>
 <button className="button secondary" disabled={busy||status?.checking} onClick={()=>void check()}>{status?.checking?(de?'Wird geprüft …':'Checking …'):(de?'Modellupdates prüfen':'Check model updates')}</button>{status?.checkedAt&&<small> · {formatDate(status.checkedAt,language)}</small>}
 {status&&!status.checking&&!status.entries.length&&<p>{de?'Keine abgeschlossenen Hugging-Face-Downloads zu prüfen.':'No completed Hugging Face downloads to check.'}</p>}
 {status?.entries.map(e=><article key={e.downloadId}><label><input type="checkbox" disabled={busy||status.checking||e.status!=='available'} checked={selected.includes(e.downloadId)} onChange={v=>{setPlans([]);setSelected(ids=>v.target.checked?[...ids,e.downloadId]:ids.filter(id=>id!==e.downloadId));}}/> <strong>{e.repo}</strong> · {e.status==='available'?(de?'Update verfügbar':'Update available'):e.status==='current'?(de?'Gewichte aktuell':'Weights up to date'):e.status==='review'?(de?'Dateiauswahl überprüfen':'Review file selection'):(de?'Prüfung fehlgeschlagen':'Check failed')}</label><details><summary>{de?'Revisionen und Dateien':'Revisions and files'}</summary><p className="download-path">{e.installedRevision} → {e.revision??'—'}</p><p>{formatGigabytes(e.totalBytes,language)}</p>{e.changedFiles.map(f=><p className="download-path" key={f}>{f}</p>)}{e.missingFiles.length>0&&<p className="notice warning">{de?'Am neuen Stand fehlen: ':'Missing in the new revision: '}{e.missingFiles.join(', ')}</p>}</details>{e.error&&<p className="notice warning">{hubError(e.error,language)}</p>}</article>)}
 {available.length>0&&<div className="hub-actions"><button className="button secondary" disabled={busy||status?.checking||!selected.length} onClick={()=>void prepare(selected)}>{de?'Ausgewählte Updates vorbereiten':'Prepare selected updates'}</button><button className="button primary" disabled={busy||status?.checking||available.length>16} onClick={()=>void prepare(available.map(e=>e.downloadId))}>{de?'Alle Updates vorbereiten':'Prepare all updates'}</button>{available.length>16&&<p>{de?'Bis zu 16 Updates gemeinsam auswählen.':'Select up to 16 updates at a time.'}</p>}</div>}
 {plans.length>0&&<section className="download-plan"><h3>{de?'Updatevorschau':'Update preview'}</h3><p>{de?'Download':'Download'}: {formatGigabytes(plans.reduce((n,p)=>n+p.download.totalBytes,0),language)} · {de?'Zusätzlicher Speicher während der Übernahme':'Additional space during publication'}: {formatGigabytes(plans.reduce((n,p)=>n+p.additionalBytes,0),language)}</p>{plans.map(p=><div key={p.id}><strong>{p.download.repo}</strong><p className="download-path">{p.download.revision} · {p.download.destination}</p><p>{de?'Lizenz':'License'}: {p.download.license??(de?'Unbekannt':'Unknown')}</p></div>)}<button className="button primary" disabled={busy} onClick={()=>void start()}>{de?'Diese Updates herunterladen':'Download these updates'}</button></section>}
 {queued.length>0&&<p role="status">{de?'In der Downloadliste: ':'In the download queue: '}{queued.join(', ')}</p>}
 {(error||status?.error)&&<p role="alert" className="notice warning">{error||hubError(status?.error,language)}</p>}
 </section>;
}
