import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {listen} from '@tauri-apps/api/event';
import {LockKeyhole,ShieldCheck,X} from 'lucide-react';
import './privacy.css';
export interface PrivacyStatus {configured:boolean;enabled:boolean;locked:boolean;autoLock:boolean;kind:'pin'|'password';epoch:number;retrySeconds:number;models:string[];hasProtected:boolean;projectLocked:boolean}
const initial:PrivacyStatus={configured:false,enabled:false,locked:true,autoLock:true,kind:'pin',epoch:0,retrySeconds:0,models:[],hasProtected:false,projectLocked:false};
const context=createContext({status:initial,open:(_de:boolean)=>{},beforeLock:{current:null as null|(()=>Promise<void>)}});
export const usePrivacy=()=>useContext(context);
const normalized=(path:string)=>path.replace(/^\\\\\?\\/,'').replaceAll('/','\\').toLowerCase();
export const protectedModel=(s:PrivacyStatus,path:string)=>s.models.some(p=>normalized(p)===normalized(path));
export function useModelPrivacy(path:string){const p=usePrivacy();const [result,setResult]=useState<{path:string;epoch:number;restricted:boolean}|null>(null);useEffect(()=>{let live=true;void invoke<boolean>('privacy_model_status',{path}).then(restricted=>{if(live)setResult({path,epoch:p.status.epoch,restricted});}).catch(()=>{if(live)setResult({path,epoch:p.status.epoch,restricted:true});});return()=>{live=false;};},[path,p.status.epoch]);return result?.path===path&&result.epoch===p.status.epoch?result.restricted:protectedModel(p.status,path)||!!path;}
export function privacyError(e:unknown,de:boolean){const errors:Record<string,[string,string]>={privacy_locked:['Bitte zuerst den 18+-Bereich entsperren.','Unlock the 18+ area first.'],privacy_wrong:['PIN oder Passwort ist falsch.','Incorrect PIN or password.'],privacy_retry:['Zu viele Versuche. Bitte kurz warten und erneut versuchen.','Please wait briefly before trying again.'],privacy_age:['Bitte bestätige, dass du mindestens 18 Jahre alt bist.','Confirm that you are at least 18 years old.'],privacy_credential:['PIN: 6–12 Ziffern. Passwort: 8–128 Zeichen.','PIN: 6–12 digits. Password: 8–128 characters.'],privacy_configured:['Die Sperre ist bereits eingerichtet.','The lock is already configured.'],privacy_storage:['Die lokale Sperre konnte nicht gelesen oder gespeichert werden.','Unable to read or save the local lock.'],privacy_model:['Bitte eine vorhandene Modelldatei wählen.','Choose an existing model file.']};return errors[String(e)]?.[de?0:1]??String(e);}
export function PrivacyProvider({children}:{children:(epoch:number)=>ReactNode}){
 const [status,setStatus]=useState(initial),[ready,setReady]=useState(false),[shown,setShown]=useState(false),[de,setDe]=useState(true);
 const [kind,setKind]=useState<'pin'|'password'>('pin'),[secret,setSecret]=useState(''),[repeat,setRepeat]=useState(''),[old,setOld]=useState(''),[adult,setAdult]=useState(false),[autoLock,setAutoLock]=useState(true),[change,setChange]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const beforeLock=useRef<null|(()=>Promise<void>)>(null),dialog=useRef<HTMLDialogElement>(null),latest=useRef(initial);
 function accept(next:PrivacyStatus){latest.current=next;setStatus(next);setAutoLock(next.autoLock);setReady(true);}
 useEffect(()=>{let live=true;let off:(()=>void)|undefined;void listen<PrivacyStatus>('privacy-changed',e=>{if(live)accept(e.payload);}).then(f=>{if(live)off=f;else f();});void invoke<PrivacyStatus>('privacy_status').then(s=>{if(live)accept(s);}).catch(e=>{if(live)setError(String(e));});return()=>{live=false;off?.();};},[]);
 useEffect(()=>{if(shown)dialog.current?.showModal();else dialog.current?.close();},[shown]);
 function open(de:boolean){setDe(de);setError('');setSecret('');setRepeat('');setOld('');setAdult(false);setChange(false);setKind(latest.current.kind);setAutoLock(latest.current.autoLock);setShown(true);}
 async function act(action:()=>Promise<PrivacyStatus>,close=false){if(busy)return;setBusy(true);setError('');try{if(!latest.current.locked)await beforeLock.current?.();accept(await action());setSecret('');setRepeat('');setOld('');setChange(false);if(close)setShown(false);}catch(e){setError(privacyError(e,de));}finally{setBusy(false);}}
 async function submit(){if(!status.configured){if(secret!==repeat){setError(de?'Die Eingaben stimmen nicht überein.':'The entries do not match.');return;}await act(()=>invoke('privacy_setup',{kind,secret,adult}),true);}else if(status.locked){await act(()=>invoke('privacy_unlock',{secret}),true);}else{if(change&&secret!==repeat){setError(de?'Die Eingaben stimmen nicht überein.':'The entries do not match.');return;}await act(()=>invoke('privacy_options',{secret:old,autoLock,newSecret:change?secret:null,kind:change?kind:null}),true);}}
 const t=(a:string,b:string)=>de?a:b;
 return <context.Provider value={{status,open,beforeLock}}>{ready?children(status.epoch):<p role="status">{error||'Local Studio …'}</p>}<dialog ref={dialog} className="privacy-dialog" onCancel={e=>{if(busy)e.preventDefault();else setShown(false);}} onClose={()=>setShown(false)}><form onSubmit={e=>{e.preventDefault();void submit();}}><div className="section-heading"><h2><LockKeyhole size={20}/> {t('18+-Bereich','18+ area')}</h2><button type="button" className="icon-button" disabled={busy} aria-label={t('Schließen','Close')} onClick={()=>setShown(false)}><X size={18}/></button></div><p>{!status.configured?t('Bestätige dein Alter und richte eine lokale PIN oder ein Passwort ein.','Confirm your age and set a local PIN or password.'):status.locked?t('Entsperre geschützte Arbeitsbereiche, Medien und Metadaten.','Unlock protected workspaces, media and metadata.'):t('Der 18+-Bereich ist entsperrt.','The 18+ area is unlocked.')}</p>
 {!status.configured&&<label className="privacy-check"><input type="checkbox" checked={adult} onChange={e=>setAdult(e.target.checked)} disabled={busy}/>{t('Ich bin mindestens 18 Jahre alt.','I am at least 18 years old.')}</label>}
 {status.configured&&!status.locked&&<><label className="privacy-check"><input type="checkbox" checked={autoLock} onChange={e=>setAutoLock(e.target.checked)} disabled={busy}/>{t('18+-Bereich nach App-Neustart erneut sperren','Lock the 18+ area again after restarting the app')}</label><label>{t('Aktuelle PIN / aktuelles Passwort','Current PIN / password')}<input type="password" autoComplete="off" value={old} onChange={e=>setOld(e.target.value)} maxLength={128} disabled={busy}/></label><label className="privacy-check"><input type="checkbox" checked={change} onChange={e=>setChange(e.target.checked)} disabled={busy}/>{t('PIN / Passwort ändern','Change PIN / password')}</label></>}
 {(!status.configured||change)&&<label>{t('Sperrart','Lock type')}<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)} disabled={busy}><option value="pin">PIN</option><option value="password">{t('Passwort','Password')}</option></select></label>}
 {(!status.configured||status.locked||change)&&<label>{kind==='pin'?'PIN':t('Passwort','Password')}<input type="password" autoComplete="off" inputMode={kind==='pin'?'numeric':undefined} value={secret} onChange={e=>setSecret(e.target.value)} maxLength={kind==='pin'?12:128} autoFocus disabled={busy}/></label>}
 {(!status.configured||change)&&<><label>{t('Eingabe wiederholen','Repeat entry')}<input type="password" autoComplete="off" inputMode={kind==='pin'?'numeric':undefined} value={repeat} onChange={e=>setRepeat(e.target.value)} maxLength={kind==='pin'?12:128} disabled={busy}/></label><small>{kind==='pin'?t('6–12 Ziffern','6–12 digits'):t('8–128 Zeichen','8–128 characters')}</small></>}
 {error&&<p className="notice warning" role="alert">{error}</p>}<p className="hub-hint">{t('Die Sperre schützt die Anzeige und App-Zugriffe. Dateien auf dem Datenträger werden nicht verschlüsselt. Laufende Generierungen laufen beim Sperren weiter.','The lock protects display and access within the app. Files on disk are not encrypted. Running generations continue when you lock.')}</p><div className="privacy-actions"><button className="button primary" disabled={busy||(!status.configured&&!adult)}>{busy?t('Bitte warten …','Please wait …'):!status.configured?t('Einrichten und aktivieren','Set up and enable'):status.locked?t('Entsperren','Unlock'):t('Einstellungen speichern','Save settings')}</button>{status.configured&&!status.locked&&<><button type="button" className="button secondary" disabled={busy} onClick={()=>void act(()=>invoke('privacy_lock',{disable:false}),true)}>{t('Jetzt sperren','Lock now')}</button><button type="button" className="text-button" disabled={busy} onClick={()=>void act(()=>invoke('privacy_lock',{disable:true}),true)}>{t('18+-Modus ausschalten','Disable 18+ mode')}</button></>}</div></form></dialog></context.Provider>;
}
export function PrivacyButton({de}:{de:boolean}){const p=usePrivacy();return <button type="button" className="button secondary privacy-status" onClick={()=>p.open(de)}>{p.status.locked?<LockKeyhole size={15}/>:<ShieldCheck size={15}/>}18+ · {p.status.locked?(de?'Gesperrt':'Locked'):(de?'Entsperrt':'Unlocked')}</button>;}
export function PrivacyGate({de,children,blocked=true}:{de:boolean;children?:ReactNode;blocked?:boolean}){const p=usePrivacy();if(!blocked)return <>{children}</>;return <div className="privacy-gate"><div className="privacy-placeholder" aria-hidden="true"/><LockKeyhole size={28}/><strong>{de?'18+-Bereich gesperrt':'18+ area locked'}</strong><p>{de?'Vorschau, Eingaben und Metadaten werden erst nach dem Entsperren angezeigt.':'Preview, inputs and metadata are shown after unlocking.'}</p><button type="button" className="button primary" onClick={()=>p.open(de)}>{de?'Entsperren':'Unlock'}</button></div>;}
export function ModelPrivacy({path,de}:{path:string;de:boolean}){const p=usePrivacy(),[error,setError]=useState(''),[busy,setBusy]=useState(false);const restricted=useModelPrivacy(path);return <div className="model-privacy"><label className="privacy-check"><input type="checkbox" checked={restricted} disabled={busy} onChange={()=>{if(p.status.locked){p.open(de);return;}setBusy(true);void (async()=>{await p.beforeLock.current?.();return invoke('privacy_model_set',{path,restricted:!restricted});})().catch(e=>setError(privacyError(e,de))).finally(()=>setBusy(false));}}/>{de?'Modell als 18+ kennzeichnen':'Label model as 18+'}</label>{error&&<p role="alert">{error}</p>}</div>;}
