import {useRef,useState,type PointerEvent} from 'react';
import {length,timelineEnd,type Timeline,type Clip} from './creative-state';
import type {MediaInfo} from './media-tools';
import {moveClips,snapEdge,trimClip} from './timeline-edit';
import {TextField} from './CreativeControls';
type Gesture={id:string;x:number;edge:'in'|'out'|null;ids:string[];original:Timeline;next:Timeline};
export default function TimelineTracks({document:d,onChange,selection,onSelect,cursor,onCursor,scale,snap,media,durations,de,disabled}:{document:Timeline;onChange:(v:Timeline)=>void;selection:string[];onSelect:(v:string[])=>void;cursor:number;onCursor:(v:number)=>void;scale:number;snap:boolean;media:MediaInfo[];durations:Record<string,number>;de:boolean;disabled:boolean}){
 const [draft,setDraft]=useState<Timeline|null>(null),[guide,setGuide]=useState<number|null>(null),gesture=useRef<Gesture|null>(null);const view=draft??d,t=(a:string,b:string)=>de?a:b;
 function down(e:PointerEvent,c:Clip,edge:'in'|'out'|null){e.stopPropagation();if(e.button!==0)return;const multiple=e.ctrlKey||e.metaKey||e.shiftKey;const ids=multiple?(selection.includes(c.id)?selection.filter(id=>id!==c.id):[...selection,c.id]):selection.includes(c.id)?selection:[c.id];onSelect(ids);if(disabled||d.tracks.find(tr=>tr.id===c.trackId)?.locked||multiple)return;e.currentTarget.setPointerCapture(e.pointerId);gesture.current={id:c.id,x:e.clientX,edge,ids,original:d,next:d};}
 function move(e:PointerEvent){const g=gesture.current;if(!g)return;const delta=(e.clientX-g.x)/scale;if(g.edge){const c=g.original.clips.find(c=>c.id===g.id)!;const edited=trimClip(c,g.edge,snapEdge(g.original,c,g.edge,delta,cursor,scale,snap),durations[c.assetId]??media.find(m=>m.assetId===c.assetId)?.waveform?.duration??c.sourceOut);g.next={...g.original,clips:g.original.clips.map(a=>a.id===g.id?edited:a)};setGuide(g.edge==='in'?edited.start:edited.start+length(edited));}else{const result=moveClips(g.original,g.ids,delta,snap,cursor,scale);g.next=result.timeline;setGuide(result.guide);}setDraft(g.next);}
 function up(e:PointerEvent){if(!gesture.current)return;move(e);const g=gesture.current;gesture.current=null;setDraft(null);setGuide(null);if(JSON.stringify(g.original)!==JSON.stringify(g.next))onChange(g.next);}
 function cancel(){gesture.current=null;setDraft(null);setGuide(null);}
 function wave(c:Clip){const w=media.find(m=>m.assetId===c.assetId)?.waveform;if(!w?.peaks.length)return null;const count=Math.max(8,Math.min(250,Math.ceil(length(c)*scale/3)));const points=Array.from({length:count},(_,i)=>{const source=c.sourceIn+(i/(count-1))*(c.sourceOut-c.sourceIn),j=Math.min(w.peaks.length-1,Math.max(0,Math.floor(source/w.duration*w.peaks.length)));return w.peaks[j];});return <svg className="clip-wave" viewBox={`0 0 ${count} 40`} preserveAspectRatio="none" aria-label={t('Audio-Wellenform','Audio waveform')}><path d={points.map((v,i)=>`M${i} ${20-v*19}V${20+v*19}`).join(' ')} stroke="currentColor" fill="none" strokeWidth="1"/></svg>;}
 return <div className="timeline-scroll"><div className="timeline-ruler" style={{width:Math.max(800,(timelineEnd(view)+3)*scale)}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect();onCursor(Math.max(0,Math.min(timelineEnd(view),(e.clientX-r.left)/scale)));}} onPointerMove={e=>{if(e.buttons===1){const r=e.currentTarget.getBoundingClientRect();onCursor(Math.max(0,Math.min(timelineEnd(view),(e.clientX-r.left)/scale)));}}}>{Array.from({length:Math.min(200,Math.ceil((timelineEnd(view)+3)/5))},(_,i)=><span style={{left:i*5*scale}} key={i}>{i*5}s</span>)}</div>
 {view.tracks.map(tr=><div className="timeline-track" key={tr.id}><div className="track-header"><TextField label={tr.audio?t('Audiospur','Audio track'):t('Videospur','Video track')} value={tr.name} disabled={disabled} onChange={name=>onChange({...d,tracks:d.tracks.map(a=>a.id===tr.id?{...a,name}:a)})}/><label><input type="checkbox" disabled={disabled} checked={tr.muted} onChange={e=>onChange({...d,tracks:d.tracks.map(a=>a.id===tr.id?{...a,muted:e.target.checked}:a)})}/>{t('Aus','Off')}</label><label><input type="checkbox" disabled={disabled} checked={tr.locked} onChange={e=>onChange({...d,tracks:d.tracks.map(a=>a.id===tr.id?{...a,locked:e.target.checked}:a)})}/>{t('Sperren','Lock')}</label></div><div className="track-lane" style={{width:Math.max(800,(timelineEnd(view)+3)*scale)}}>{view.clips.filter(c=>c.trackId===tr.id).map(c=><div role="button" tabIndex={0} className={`timeline-clip ${selection.includes(c.id)?'selected':''} ${tr.audio?'audio':''}`} key={c.id} aria-label={c.name} aria-pressed={selection.includes(c.id)} style={{left:c.start*scale,width:Math.max(14,length(c)*scale)}} onPointerDown={e=>down(e,c,null)} onPointerMove={move} onPointerUp={up} onPointerCancel={cancel} onKeyDown={e=>{if(disabled||tr.locked)return;if(e.key===' '||e.key==='Enter'){e.preventDefault();onSelect(e.ctrlKey?[...new Set([...selection,c.id])]:[c.id]);}if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();onChange(moveClips(d,selection.includes(c.id)?selection:[c.id],(e.key==='ArrowLeft'?-1:1)*(e.shiftKey?10:1)/d.fps,false,cursor,scale).timeline);}}}>
 {(['in','out'] as const).map(edge=><span key={edge} className={`clip-trim ${edge}`} role="slider" tabIndex={tr.locked?-1:0} aria-label={`${edge==='in'?t('Clipanfang','Clip start'):t('Clipende','Clip end')}: ${c.name}`} aria-valuenow={edge==='in'?c.start:c.start+length(c)} aria-valuemin={0} aria-valuemax={3600} onPointerDown={e=>down(e,c,edge)} onKeyDown={e=>{if(disabled||tr.locked||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();e.stopPropagation();const next=trimClip(c,edge,(e.key==='ArrowLeft'?-1:1)/d.fps,durations[c.assetId]??c.sourceOut);onChange({...d,clips:d.clips.map(a=>a.id===c.id?next:a)});}}/>)}
 <span className="clip-name">{c.name}</span>{wave(c)}<small>{length(c).toFixed(2)} s · {c.speed}× {media.find(m=>m.assetId===c.assetId)?.proxies.length?t('· Proxy bereit','· Proxy ready'):''}</small></div>)}<div className="playhead" style={{left:cursor*scale}}/>{guide!==null&&<div className="snap-guide" style={{left:guide*scale}}/>}</div></div>)}
 </div>;
}
