import {useEffect,useState} from 'react';
import type {useProject} from './useProject';import type {useCreative} from './useCreative';
import {save} from '@tauri-apps/plugin-dialog';import {invoke} from '@tauri-apps/api/core';
import {ai,aiError,aiPhase,mergeTranscript,type AiModel,type SpeechJob} from './ai-api';
import {srtText,type Caption} from './creative-state';import {NumberField} from './CreativeControls';import AiModels from './AiModels';import './ai.css';
export default function TranscriptionPanel({workspace:w,projects:p,clipId,de}:{workspace:ReturnType<typeof useCreative>;projects:ReturnType<typeof useProject>;clipId:string|undefined;de:boolean}){
 const [models,setModels]=useState<AiModel[]>([]),[model,setModel]=useState(''),[language,setLanguage]=useState('auto'),[jobs,setJobs]=useState<SpeechJob[]>([]),[selected,setSelected]=useState(''),[captions,setCaptions]=useState<Caption[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const t=(a:string,b:string)=>de?a:b;const clip=w.data.video?.clips.find(c=>c.id===clipId),asset=p.project?.assets.find(a=>a.id===clip?.assetId);
 useEffect(()=>{if(!model&&models.length)setModel(models[0].id);},[models,model]);
 useEffect(()=>{let live=true;const poll=()=>void ai.jobs().then(j=>{if(live)setJobs(j);}).catch(e=>{if(live)setError(aiError(e,de));});poll();const timer=setInterval(poll,700);return()=>{live=false;clearInterval(timer);};},[]);
 const own=jobs.filter(j=>j.projectId===p.project?.id),job=own.find(j=>j.id===selected)??own[0];const running=jobs.some(j=>j.status==='running');
 useEffect(()=>{setCaptions(job?.status==='completed'?structuredClone(job.captions):[]);},[job?.id,job?.status]);
 async function run(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();setJobs(await ai.jobs());}catch(e){setError(aiError(e,de));}finally{setBusy(false);}}
 const already=!!job?.captions.some(c=>w.data.video?.captions.some(v=>v.id===c.id));
 return <details className="panel transcription-panel"><summary>{t('Automatische Untertitel · lokal','Automatic captions · local')}</summary><AiModels kind="speech" de={de} onModels={setModels}/>
 <p>{t('Video- oder Audioclip auswählen. Die Erkennung verarbeitet dessen Quellbereich; Zeiten berücksichtigen Start und Geschwindigkeit. Texte und Zeiten vor der Übernahme prüfen.','Select a video or audio clip. Recognition processes its source range; timestamps account for start and speed. Review text and timing before applying.')}</p>
 <div className="creative-toolbar"><label>{t('Sprachmodell','Speech model')}<select aria-label={t('Sprachmodell','Speech model')} value={model} onChange={e=>setModel(e.target.value)}><option value="">{t('Modell auswählen','Select model')}</option>{models.map(m=><option key={m.id} value={m.id}>{m.name} · {(m.bytes/1e9).toFixed(2)} GB</option>)}</select></label><label>{t('Gesprochene Sprache','Spoken language')}<select aria-label={t('Gesprochene Sprache','Spoken language')} value={language} onChange={e=>setLanguage(e.target.value)}><option value="auto">{t('Automatisch','Automatic')}</option><option value="de">Deutsch</option><option value="en">English</option></select></label><button className="button primary" disabled={busy||running||!model||!clip||!asset||asset.kind==='image'||!w.ready||p.busy} onClick={()=>void run(async()=>{await w.flush();const j=await ai.transcribe(p.get()!.id,clip!.id,model,language);setSelected(j.id);})}>{t('Clip transkribieren','Transcribe clip')}</button><span>{clip?.name??t('Kein Clip ausgewählt','No clip selected')}</span></div>
 {own.length>0&&<label>{t('Transkription','Transcription')}<select aria-label={t('Transkription','Transcription')} value={job?.id??''} onChange={e=>setSelected(e.target.value)}>{own.map(j=><option key={j.id} value={j.id}>{j.name} · {aiPhase(j.status,de)} · {j.id.slice(0,8)}</option>)}</select></label>}
 {job&&<div role="status"><p>{aiPhase(job.status==='running'?job.phase:job.status,de)} · {(job.elapsedMs/1000).toFixed(1)} s</p>{job.status==='running'&&<><progress max={1} value={job.progress??undefined}/><button className="button secondary" onClick={()=>void run(()=>ai.cancelSpeech(job.id))}>{t('Transkription abbrechen','Cancel transcription')}</button></>}{job.error&&<p role="alert">{aiError(job.error,de)}</p>}</div>}
 {job?.status==='completed'&&<><p>{captions.length} {t('erkannte Untertitel · keine automatische Sprechertrennung','recognized captions · no automatic speaker separation')}</p><div className="transcript-segments">{captions.map((c,i)=><div className="transcript-segment" key={c.id}><div className="creative-fields"><NumberField label={`${t('Beginn','Start')} ${i+1}`} value={c.start} min={0} max={3600} step={.01} onChange={start=>setCaptions(list=>list.map(a=>a.id===c.id?{...a,start}:a))}/><NumberField label={`${t('Ende','End')} ${i+1}`} value={c.end} min={0} max={3600} step={.01} onChange={end=>setCaptions(list=>list.map(a=>a.id===c.id?{...a,end}:a))}/></div><textarea aria-label={`${t('Erkannter Text','Recognized text')} ${i+1}`} maxLength={2000} value={c.text} onChange={e=>setCaptions(list=>list.map(a=>a.id===c.id?{...a,text:e.target.value}:a))}/><button className="text-button" onClick={()=>setCaptions(list=>list.filter(a=>a.id!==c.id))}>{t('Segment aus Entwurf entfernen','Remove segment from draft')}</button></div>)}</div><div className="creative-buttons"><button className="button primary" disabled={busy||already||!captions.length||!w.ready||p.busy} onClick={()=>void run(async()=>{const project=p.get();if(project?.id!==job.projectId)throw Error('ai_clip_changed');const doc=w.get();if(!doc.video)throw Error('ai_clip_changed');const sha=project.assets.find(a=>a.id===job.assetId)?.sha256??'';w.change({...doc,video:mergeTranscript(doc.video,job,captions,sha)});await w.flush();})}>{already?t('Bereits übernommen','Already applied'):t('Untertitel in Timeline übernehmen','Apply captions to timeline')}</button><button className="button secondary" disabled={busy||!captions.length} onClick={()=>void run(async()=>{if(captions.some(c=>c.end<=c.start||!c.text.trim()))throw Error('ai_speech_output');const path=await save({defaultPath:'Untertitel.srt',filters:[{name:'SRT',extensions:['srt']}]});if(path)await invoke('caption_write',{path,text:srtText(captions)});})}>{t('SRT speichern','Save SRT')}</button></div><small>{t('Änderungen am Entwurf werden beim Übernehmen im Projekt gesichert.','Draft edits are saved in the project when applied.')}</small></>}
 {error&&<p role="alert" className="notice warning">{error}</p>}</details>;
}
