import {useEffect,useRef,useState} from 'react';
import {updateApi,updateError,type UpdateStatus} from './update-api';
export default function UpdateDialog({de,version,automatic,onAutomatic,onInstall,onClose}:{de:boolean;version:string;automatic:boolean;onAutomatic:(value:boolean)=>void;onInstall:()=>void;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [status,setStatus]=useState<UpdateStatus|null>(null),[error,setError]=useState('');const t=(a:string,b:string)=>de?a:b;
 useEffect(()=>{const el=dialog.current;el?.showModal();let live=true;const poll=()=>void updateApi.status().then(s=>{if(live)setStatus(s);}).catch(e=>{if(live)setError(updateError(e,de));});poll();const timer=setInterval(poll,350);return()=>{live=false;clearInterval(timer);el?.close();};},[]);
 async function action(fn:()=>Promise<unknown>){setError('');try{await fn();setStatus(await updateApi.status());}catch(e){setError(updateError(e,de));}}
 const busy=status&&['checking','downloading','ready','installing'].includes(status.phase);
 return <dialog ref={dialog} className="image-exit-dialog update-dialog" aria-label={t('Software-Updates','Software updates')} onCancel={e=>{e.preventDefault();onClose();}}><h2>{t('Local Studio aktualisieren','Update Local Studio')}</h2><p>{t('Installierte Version','Installed version')}: {version} · {status?.portable?'Portable':t('Installiert','Installed')}</p>
 <label className="project-exit-option"><input type="checkbox" checked={automatic} onChange={e=>onAutomatic(e.target.checked)}/>{t('Beim Start automatisch nach Updates suchen','Automatically check for updates at startup')}</label>
 {status?.phase==='current'&&<p role="status">{t('Du verwendest die aktuelle Version.','You are using the latest version.')}</p>}
 {status?.phase==='checking'&&<p role="status">{t('GitHub-Release wird geprüft …','Checking the GitHub release …')}</p>}
 {status?.latest&&<><h3>{t('GitHub-Version','GitHub version')}: {status.latest.version}</h3><pre className="update-notes">{status.latest.notes}</pre></>}
 {(error||status?.error)&&<p className="notice warning" role="alert">{error||updateError(status?.error,de)}</p>}
 {status?.phase==='downloading'&&<><progress max={status.total||1} value={status.received}/><p>{(status.received/1048576).toFixed(1)} / {(status.total/1048576).toFixed(1)} MiB</p><button className="button secondary" onClick={()=>void action(updateApi.cancel)}>{t('Download abbrechen','Cancel download')}</button></>}
 {status?.phase==='ready'&&<p>{t('Signatur und Installationsdatei sind geprüft. Local Studio wird geschlossen, aktualisiert und neu gestartet. Ungespeicherte Arbeit wird zuvor berücksichtigt.','Signature and installer are verified. Local Studio will close, update and restart. Unsaved work will be handled first.')}</p>}
 {status?.portable&&<p>{t('ZIP herunterladen, App schließen und Programmdateien ersetzen. Local-Studio-Data behalten. Die portable Version installiert nichts automatisch.','Download the ZIP, close the app and replace the program files. Keep Local-Studio-Data. Portable builds never install updates automatically.')}</p>}
 <div className="image-dialog-actions"><button className="button secondary" onClick={onClose}>{t('Schließen','Close')}</button><button className="button secondary" disabled={!!busy} onClick={()=>void action(updateApi.check)}>{t('Erneut prüfen','Check again')}</button>{status?.phase==='available'&&(status.portable?<button className="button primary" onClick={()=>void action(updateApi.openDownload)}>{t('Download auf GitHub öffnen','Open download on GitHub')}</button>:<button className="button primary" onClick={()=>void action(updateApi.download)}>{t('Update herunterladen','Download update')}</button>)}{status?.phase==='ready'&&<button className="button primary" onClick={onInstall}>{t('Aktualisieren und neu starten','Update and restart')}</button>}</div><p className="hub-hint">{t('Die Prüfung verbindet sich mit GitHub. Medien, Prompts und Modelldateien werden nicht übertragen.','Checking connects to GitHub. Media, prompts and model files are not sent.')}</p></dialog>;
}
