use super::*;
use std::io::Cursor;
fn request(root:&Path,ops:Vec<Operation>)->Request{let path=root.join("source.png");let file=lock_file(&path).unwrap();let id=identity(&file).unwrap();Request{query:LineageQuery{root_id:root_id(root),target:FileTarget{path:"source.png".into(),version:thumbnails::version(root,&path,&file.metadata().unwrap(),Some(&id)),file_id:id}},operations:ops}}
fn fixture()->DynamicImage{let mut i=image::RgbaImage::new(3,2);for (n,p) in i.pixels_mut().enumerate(){*p=image::Rgba([(n*30) as u8,80,150,if n==0{0}else{255}]);}DynamicImage::ImageRgba8(i)}
#[test]fn transformations_have_exact_pixels_and_dimensions(){
 let original=fixture();let rotated=transform(original.clone(),&[Operation::Rotate{clockwise:true}]).unwrap();assert_eq!((rotated.width(),rotated.height()),(2,3));assert_eq!(rotated.to_rgba8().get_pixel(1,0),original.to_rgba8().get_pixel(0,0));
 let roundtrip=transform(rotated,&[Operation::Rotate{clockwise:false}]).unwrap();assert_eq!(roundtrip.to_rgba8(),original.to_rgba8());
 for horizontal in [true,false]{let result=transform(original.clone(),&[Operation::Flip{horizontal},Operation::Flip{horizontal}]).unwrap();assert_eq!(result.to_rgba8(),original.to_rgba8());}
 let cropped=transform(original.clone(),&[Operation::Crop{x:1,y:0,width:2,height:2}]).unwrap();assert_eq!(cropped.to_rgba8().get_pixel(0,1),original.to_rgba8().get_pixel(1,1));
 let resized=transform(original,&[Operation::Resize{width:30,height:20}]).unwrap();assert_eq!((resized.width(),resized.height()),(30,20));assert!(resized.to_rgba8().pixels().any(|p|p[3]<255));
}
#[test]fn invalid_operations_are_rejected_before_allocation(){for op in [Operation::Crop{x:u32::MAX,y:0,width:2,height:1},Operation::Crop{x:2,y:0,width:2,height:1},Operation::Resize{width:0,height:2},Operation::Resize{width:16384,height:16384}]{assert!(transform(fixture(),&[op]).is_err());}assert!(transform(fixture(),&vec![Operation::Flip{horizontal:true};1001]).is_err());assert!(transform(fixture(),&vec![Operation::Resize{width:8000,height:4000};17]).is_err());}
#[test]fn png_preserves_alpha_jpeg_flattens_white_and_quality_changes_real_encoding(){let i=fixture();let png=encode(&i,None,"png",90).unwrap();assert_eq!(image::load_from_memory(&png).unwrap().to_rgba8(),i.to_rgba8());let jpeg=encode(&i,None,"jpeg",100).unwrap();let decoded=image::load_from_memory(&jpeg).unwrap().to_rgb8();assert!(decoded.get_pixel(0,0).0.iter().all(|v|*v>245));assert_ne!(jpeg,encode(&i,None,"jpeg",10).unwrap());assert!(encode(&i,None,"jpeg",0).is_err());assert!(encode(&i,None,"tiff",90).is_err());}
#[test]fn export_preserves_original_records_recipe_and_rejects_changed_source(){let t=tempfile::tempdir().unwrap();let root=fs::canonicalize(t.path()).unwrap();let bytes=encode(&fixture(),None,"png",90).unwrap();fs::write(root.join("source.png"),&bytes).unwrap();let c=GalleryCatalog::new(&root).unwrap();let operations=vec![Operation::Rotate{clockwise:true},Operation::Crop{x:0,y:1,width:2,height:2}];let p=preview(&root,request(&root,operations.clone())).unwrap();assert_eq!((p.width,p.height),(2,2));let out=c.export_edit(&root,request(&root,operations.clone()),"png".into(),90,None).unwrap();assert_eq!(fs::read(root.join("source.png")).unwrap(),bytes);let actual=image::open(root.join(&out)).unwrap();assert_eq!(actual.to_rgba8(),transform(fixture(),&operations).unwrap().to_rgba8());
 let db=c.db.lock().unwrap();let json:String=db.query_row("SELECT json FROM lineage WHERE json_extract(json,'$.operation')='edit'",[],|r|r.get(0)).unwrap();let node:Node=serde_json::from_str(&json).unwrap();assert!(node.parent.is_some());assert_eq!(node.path,out);assert_eq!(node.edit,Some(serde_json::to_value(operations).unwrap()));assert_eq!(node.stamp,stamp(&fs::metadata(root.join(&out)).unwrap()));drop(db);
 let stale=request(&root,vec![]);fs::write(root.join("source.png"),b"changed").unwrap();assert!(c.export_edit(&root,stale,"png".into(),90,None).is_err());let mut escape=request(&root,vec![]);escape.query.target.path="../outside.png".into();assert!(preview(&root,escape).is_err());assert_eq!(fs::read_dir(&root).unwrap().flatten().filter(|e|e.path().extension().is_some_and(|s|s=="tmp")).count(),0);
}
#[test]fn high_depth_corrupt_and_unsupported_sources_are_not_silently_converted(){let t=tempfile::tempdir().unwrap();let p=t.path().join("input.png");let mut data=Cursor::new(vec![]);DynamicImage::ImageRgba16(image::ImageBuffer::new(2,2)).write_to(&mut data,ImageFormat::Png).unwrap();fs::write(&p,data.into_inner()).unwrap();assert!(decode(File::open(&p).unwrap()).err().unwrap().contains("editor_depth"));fs::write(&p,b"not an image").unwrap();assert!(decode(File::open(&p).unwrap()).is_err());let mut data=Cursor::new(vec![]);fixture().write_to(&mut data,ImageFormat::Gif).unwrap();fs::write(&p,data.into_inner()).unwrap();assert!(decode(File::open(&p).unwrap()).err().unwrap().contains("editor_format"));}

#[test]fn orientation_is_baked_once_and_exif_not_copied(){let t=tempfile::tempdir().unwrap();let path=t.path().join("oriented.jpg");let bytes=encode(&fixture(),None,"jpeg",100).unwrap();let exif=b"Exif\0\0II\x2a\0\x08\0\0\0\x01\0\x12\x01\x03\0\x01\0\0\0\x06\0\0\0\0\0\0\0";let mut source=bytes[..2].to_vec();source.extend_from_slice(&[0xff,0xe1]);source.extend_from_slice(&((exif.len()+2)as u16).to_be_bytes());source.extend_from_slice(exif);source.extend_from_slice(&bytes[2..]);fs::write(&path,&source).unwrap();let(i,p)=decode(File::open(&path).unwrap()).unwrap();assert_eq!((i.width(),i.height()),(2,3));let exported=encode(&i,p,"jpeg",90).unwrap();assert!(!exported.windows(6).any(|w|w==b"Exif\0\0"));fs::write(&path,exported).unwrap();let(i,_)=decode(File::open(path).unwrap()).unwrap();assert_eq!((i.width(),i.height()),(2,3));}
#[test]fn rgb_profile_bytes_survive_png_and_jpeg_and_non_rgb_is_rejected(){
 // Passive profile header fixture tests byte transport; it is not a colorimetry assertion.
 let mut profile=vec![0u8;132];profile[..4].copy_from_slice(&132u32.to_be_bytes());profile[16..20].copy_from_slice(b"RGB ");profile[36..40].copy_from_slice(b"acsp");let t=tempfile::tempdir().unwrap();let path=t.path().join("profile.png");
 for format in ["png","jpeg"]{let bytes=encode(&fixture(),Some(profile.clone()),format,90).unwrap();fs::write(&path,bytes).unwrap();let(_,p)=decode(File::open(&path).unwrap()).unwrap();assert_eq!(p,Some(profile.clone()));}
 profile[16..20].copy_from_slice(b"CMYK");fs::write(&path,encode(&fixture(),Some(profile),"png",90).unwrap()).unwrap();assert!(decode(File::open(path).unwrap()).err().unwrap().contains("editor_profile"));
}
#[test]fn animated_png_is_not_flattened_silently(){let t=tempfile::tempdir().unwrap();let path=t.path().join("animated.png");let mut bytes=vec![];{let mut encoder=png::Encoder::new(&mut bytes,2,2);encoder.set_color(png::ColorType::Rgba);encoder.set_animated(2,0).unwrap();let mut writer=encoder.write_header().unwrap();writer.write_image_data(&[255;16]).unwrap();writer.write_image_data(&[0;16]).unwrap();}fs::write(&path,bytes).unwrap();assert!(decode(File::open(path).unwrap()).err().unwrap().contains("editor_format"));}
